import type { WorkspaceConfiguration } from "@visulima/task-runner";

import type { OwnersEntry, VisProjectConfiguration } from "./workspace";

export interface CodeownersConfig {
    /** Sort order for generated entries — mirrors moon's `orderBy`. */
    orderBy?: "file-source" | "project-id";
    /** Workspace-level paths that apply outside any project (e.g., `.github/**`). */
    globalPaths?: Record<string, string[]>;
    /** Provider determines whether `channel` is emitted (GitHub supports it via comment). */
    provider?: "bitbucket" | "github" | "gitlab" | "other";
}

/**
 * A single resolved CODEOWNERS line, pre-sorted by path. Kept as an
 * object so callers can post-process (e.g. append sub-sections).
 */
export interface CodeownersLine {
    /** Effective path glob (workspace-root-relative). */
    path: string;
    /** Owner handles, space-separated by the writer. */
    owners: string[];
    /** Optional notification channel (added as a trailing comment). */
    channel?: string;
    /** Source project name — used for `order-by=project-id` sorting. */
    projectId?: string;
}

/**
 * Normalises an {@link OwnersEntry} path to be workspace-root-relative.
 * Owners entries live in project.json, so they are stated relative to
 * each project root. We prepend the project root to keep git-blame
 * matching simple.
 */
const toWorkspacePath = (projectRoot: string, entryPath: string): string => {
    const trimmed = entryPath.replace(/^\.?\//, "");

    if (trimmed === "" || trimmed === ".") {
        return `/${projectRoot}/`;
    }

    // Preserve wildcards and globs verbatim — they're interpreted by the
    // CODEOWNERS matcher, not by us.
    if (projectRoot === "" || projectRoot === ".") {
        return `/${trimmed}`;
    }

    return `/${projectRoot}/${trimmed}`;
};

/**
 * Computes CODEOWNERS lines from the workspace's projects and a
 * workspace-level `codeowners` block. Returns lines in the requested
 * order (default: `file-source`).
 */
export const buildCodeownersLines = (
    workspace: WorkspaceConfiguration,
    config: CodeownersConfig | undefined,
): CodeownersLine[] => {
    const lines: CodeownersLine[] = [];

    for (const [globalPath, owners] of Object.entries(config?.globalPaths ?? {})) {
        lines.push({ owners, path: globalPath });
    }

    for (const [name, project] of Object.entries(workspace.projects) as [string, VisProjectConfiguration][]) {
        const ownersList: OwnersEntry[] = project.owners ?? [];

        for (const entry of ownersList) {
            lines.push({
                channel: entry.channel,
                owners: entry.owners,
                path: toWorkspacePath(project.root ?? name, entry.path),
                projectId: name,
            });
        }
    }

    const orderBy = config?.orderBy ?? "file-source";

    if (orderBy === "project-id") {
        lines.sort((a, b) => (a.projectId ?? "").localeCompare(b.projectId ?? "") || a.path.localeCompare(b.path));
    } else {
        lines.sort((a, b) => a.path.localeCompare(b.path));
    }

    return lines;
};

const HEADER_LINES = [
    "# CODEOWNERS — generated by `vis sync codeowners`. Do not edit by hand.",
    "# Update each project's project.json `owners` field and re-run the command.",
    "",
];

/**
 * Serialises {@link CodeownersLine}s to a valid CODEOWNERS file string.
 */
export const renderCodeowners = (lines: CodeownersLine[], provider: CodeownersConfig["provider"] = "github"): string => {
    const out: string[] = [...HEADER_LINES];

    for (const line of lines) {
        const owners = line.owners.join(" ");
        const channel = line.channel ? `    # notify: ${line.channel}` : "";

        if (provider === "bitbucket") {
            // Bitbucket uses `Rule: <glob>` — different format.
            out.push(`${line.path} ${owners}${channel}`);
        } else {
            out.push(`${line.path} ${owners}${channel}`);
        }
    }

    out.push("");

    return out.join("\n");
};
