import { spawnSync } from "node:child_process";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { afterEach, beforeEach, describe, expect, it } from "vitest";

import type { HookConfig } from "../../../src/commands/hook/config";
import { HOOK_CONFIG_VERSION, writeHookConfig } from "../../../src/commands/hook/config";
import { formatListResult, listHooks, parseStageScript } from "../../../src/commands/hook/list";
import { runHookStage } from "../../../src/commands/hook/run";
import { validateHooks } from "../../../src/commands/hook/validate";

const createTemporaryGitRepo = (): { cleanup: () => void; root: string } => {
    const root = mkdtempSync(join(tmpdir(), "vis-hook-cmd-test-"));
    const originalCwd = process.cwd();

    spawnSync("git", ["init"], { cwd: root, stdio: "ignore" });
    spawnSync("git", ["config", "user.email", "test@test.test"], { cwd: root });
    spawnSync("git", ["config", "user.name", "test"], { cwd: root });
    spawnSync("git", ["config", "commit.gpgsign", "false"], { cwd: root });
    process.chdir(root);

    return {
        cleanup: () => {
            process.chdir(originalCwd);
            rmSync(root, { force: true, recursive: true });
        },
        root,
    };
};

const writeHookScript = (root: string, stage: string, body: string): void => {
    const directory = join(root, ".vis-hooks");
    const dispatcherDirectory = join(directory, "_");

    mkdirSync(dispatcherDirectory, { recursive: true });
    writeFileSync(join(directory, stage), body, { mode: 0o755 });
    writeFileSync(join(dispatcherDirectory, "h"), "#!/usr/bin/env sh\nexit 0\n", { mode: 0o755 });
    writeFileSync(join(dispatcherDirectory, stage), `#!/usr/bin/env sh\n. "$(dirname "$0")/h"\n`, { mode: 0o755 });
};

const noopLogger = { error: (): void => undefined, info: (): void => undefined, warn: (): void => undefined };

// ─── parseStageScript ───────────────────────────────────────────────

describe(parseStageScript, () => {
    it("extracts `# id: name` headers emitted by the migrator", () => {
        expect.assertions(3);

        const script = [
            "#!/usr/bin/env sh",
            "# Generated by `vis hook migrate` from prek",
            "",
            "# lint-staged: lint staged files",
            "pnpm exec lint-staged",
            "",
            "# commitlint: validate commit message",
            "pnpm exec commitlint --edit",
        ].join("\n");
        const blocks = parseStageScript(script);

        expect(blocks).toHaveLength(2);
        expect(blocks[0]).toStrictEqual({ command: "pnpm exec lint-staged", id: "lint-staged", name: "lint staged files" });
        expect(blocks[1]).toStrictEqual({ command: "pnpm exec commitlint --edit", id: "commitlint", name: "validate commit message" });
    });

    it("treats hand-written scripts (no headers) as a single (custom) block", () => {
        expect.assertions(2);

        const blocks = parseStageScript("#!/usr/bin/env sh\necho hi\n");

        expect(blocks).toHaveLength(1);
        expect(blocks[0]?.id).toBe("(custom)");
    });
});

// ─── listHooks ─────────────────────────────────────────────────────

describe(listHooks, () => {
    let temporary: { cleanup: () => void; root: string };

    beforeEach(() => {
        temporary = createTemporaryGitRepo();
    });

    afterEach(() => {
        temporary.cleanup();
    });

    it("returns an empty result when the hooks directory is missing", () => {
        expect.assertions(1);

        const result = listHooks(temporary.root, ".vis-hooks");

        expect(result.stages).toStrictEqual([]);
    });

    it("groups discovered hooks per stage alphabetically", () => {
        expect.assertions(3);

        writeHookScript(temporary.root, "pre-commit", "#!/usr/bin/env sh\n# lint-staged: run linters\npnpm run lint\n");
        writeHookScript(temporary.root, "commit-msg", "#!/usr/bin/env sh\n# commitlint: validate message\npnpm exec commitlint --edit\n");

        const result = listHooks(temporary.root, ".vis-hooks");
        const formatted = formatListResult(result);

        expect(result.stages.map((s) => s.stage)).toStrictEqual(["commit-msg", "pre-commit"]);
        expect(formatted.some((line) => line.includes("commit-msg"))).toBe(true);
        expect(formatted.some((line) => line.includes("pre-commit"))).toBe(true);
    });
});

// ─── validateHooks ──────────────────────────────────────────────────

describe(validateHooks, () => {
    let temporary: { cleanup: () => void; root: string };

    beforeEach(() => {
        temporary = createTemporaryGitRepo();
    });

    afterEach(() => {
        temporary.cleanup();
    });

    it.skipIf(process.platform === "win32")("flags missing dispatcher + hooksPath as errors", () => {
        expect.assertions(2);

        const result = validateHooks(temporary.root, ".vis-hooks");

        expect(result.ok).toBe(false);
        expect(result.issues.some((i) => i.message.includes("Dispatcher directory"))).toBe(true);
    });

    it.skipIf(process.platform === "win32")("accepts a clean install", () => {
        expect.assertions(2);

        writeHookScript(temporary.root, "pre-commit", "#!/usr/bin/env sh\necho hi\n");
        writeHookConfig(temporary.root, ".vis-hooks", {
            stages: { "pre-commit": [{ entry: "echo hi", id: "noop" }] },
            version: HOOK_CONFIG_VERSION,
        });
        spawnSync("git", ["config", "core.hooksPath", ".vis-hooks/_"], { cwd: temporary.root });

        const result = validateHooks(temporary.root, ".vis-hooks");

        expect(result.ok).toBe(true);
        expect(result.issues.every((i) => i.kind !== "error")).toBe(true);
    });

    it.skipIf(process.platform === "win32")("detects shell syntax errors in a stage script", () => {
        expect.assertions(2);

        writeHookScript(temporary.root, "pre-commit", "#!/usr/bin/env sh\nif then fi\n");
        spawnSync("git", ["config", "core.hooksPath", ".vis-hooks/_"], { cwd: temporary.root });

        const result = validateHooks(temporary.root, ".vis-hooks");

        expect(result.ok).toBe(false);
        expect(result.issues.some((i) => i.kind === "error" && i.message.includes("syntax"))).toBe(true);
    });

    it.skipIf(process.platform === "win32")("flags a missing config.json when stage scripts are present", () => {
        expect.assertions(2);

        writeHookScript(temporary.root, "pre-commit", "#!/usr/bin/env sh\nexec vis hook run pre-commit \"$@\"\n");
        spawnSync("git", ["config", "core.hooksPath", ".vis-hooks/_"], { cwd: temporary.root });

        const result = validateHooks(temporary.root, ".vis-hooks");

        expect(result.ok).toBe(false);
        expect(result.issues.some((i) => i.message.includes("config.json"))).toBe(true);
    });
});

// ─── runHookStage ───────────────────────────────────────────────────

const writeConfig = (root: string, stages: HookConfig["stages"]): void => {
    mkdirSync(join(root, ".vis-hooks"), { recursive: true });
    writeHookConfig(root, ".vis-hooks", { stages, version: HOOK_CONFIG_VERSION });
};

describe(runHookStage, () => {
    let temporary: { cleanup: () => void; root: string };

    beforeEach(() => {
        temporary = createTemporaryGitRepo();
    });

    afterEach(() => {
        temporary.cleanup();
    });

    it.skipIf(process.platform === "win32")("rejects --from-ref without --to-ref", () => {
        expect.assertions(1);

        writeConfig(temporary.root, { "pre-commit": [{ entry: "true", id: "noop" }] });

        expect(() => runHookStage(temporary.root, ".vis-hooks", { fromRef: "HEAD~1", stage: "pre-commit" }, noopLogger)).toThrow(
            /--from-ref and --to-ref must be specified together/,
        );
    });

    it.skipIf(process.platform === "win32")("rejects --last-commit combined with explicit refs", () => {
        expect.assertions(1);

        writeConfig(temporary.root, { "pre-commit": [{ entry: "true", id: "noop" }] });

        expect(() => runHookStage(temporary.root, ".vis-hooks", { fromRef: "main", lastCommit: true, stage: "pre-commit", toRef: "HEAD" }, noopLogger)).toThrow(
            /--last-commit cannot be combined/,
        );
    });

    it.skipIf(process.platform === "win32")("returns 0 when the configured stage has no matching files (no alwaysRun)", () => {
        expect.assertions(1);

        // Entry only runs against staged files; with nothing staged, dispatcher skips it.
        writeConfig(temporary.root, { "pre-commit": [{ entry: "exit 1", id: "would-fail" }] });

        const code = runHookStage(temporary.root, ".vis-hooks", { stage: "pre-commit" }, noopLogger);

        expect(code).toBe(0);
    });

    it.skipIf(process.platform === "win32")("runs an alwaysRun entry and propagates its exit code", () => {
        expect.assertions(1);

        writeConfig(temporary.root, { "pre-commit": [{ alwaysRun: true, entry: "exit 7", id: "noop", passFilenames: false }] });

        const code = runHookStage(temporary.root, ".vis-hooks", { stage: "pre-commit" }, noopLogger);

        expect(code).toBe(7);
    });

    it.skipIf(process.platform === "win32")("errors when config.json is missing", () => {
        expect.assertions(1);

        expect(() => runHookStage(temporary.root, ".vis-hooks", { stage: "pre-commit" }, noopLogger)).toThrow(/No hook config found/);
    });

    it.skipIf(process.platform === "win32")("returns 0 when the stage has no configured hooks", () => {
        expect.assertions(1);

        writeConfig(temporary.root, { "commit-msg": [{ entry: "true", id: "x" }] });

        const code = runHookStage(temporary.root, ".vis-hooks", { stage: "pre-commit" }, noopLogger);

        expect(code).toBe(0);
    });

    it.skipIf(process.platform === "win32")("runs `fail` entries when files match the filter (--all-files)", () => {
        expect.assertions(1);

        writeFileSync(join(temporary.root, "blocked.txt"), "content");
        spawnSync("git", ["add", "blocked.txt"], { cwd: temporary.root });
        spawnSync("git", ["commit", "-m", "init"], { cwd: temporary.root });

        writeConfig(temporary.root, { "pre-commit": [{ fail: "do not commit txt files", id: "no-txt" }] });

        const code = runHookStage(temporary.root, ".vis-hooks", { allFiles: true, stage: "pre-commit" }, noopLogger);

        expect(code).toBe(1);
    });

    it.skipIf(process.platform === "win32")("dispatches `check-json` builtin and surfaces duplicate-key failures", () => {
        expect.assertions(1);

        const filePath = join(temporary.root, "pkg.json");

        writeFileSync(filePath, "{\"a\": 1, \"a\": 2}\n");
        spawnSync("git", ["add", "pkg.json"], { cwd: temporary.root });

        writeConfig(temporary.root, {
            "pre-commit": [{ builtin: "check-json", files: "\\.json$", id: "check-json" }],
        });

        const code = runHookStage(temporary.root, ".vis-hooks", { stage: "pre-commit" }, noopLogger);

        expect(code).toBe(1);
    });

    it.skipIf(process.platform === "win32")("dispatches `trailing-whitespace` builtin and rewrites offending files", () => {
        expect.assertions(2);

        const filePath = join(temporary.root, "notes.txt");

        writeFileSync(filePath, "hello   \nworld\n");
        spawnSync("git", ["add", "notes.txt"], { cwd: temporary.root });

        writeConfig(temporary.root, {
            "pre-commit": [{ builtin: "trailing-whitespace", files: "\\.txt$", id: "trailing-whitespace" }],
        });

        const code = runHookStage(temporary.root, ".vis-hooks", { stage: "pre-commit" }, noopLogger);

        expect(code).toBe(1);
        expect(readFileSync(filePath, "utf8")).toBe("hello\nworld\n");
    });

    it.skipIf(process.platform === "win32")("propagates invalid-regex filter errors per-hook without aborting the stage", () => {
        expect.assertions(1);

        writeFileSync(join(temporary.root, "a.txt"), "x");
        spawnSync("git", ["add", "a.txt"], { cwd: temporary.root });

        writeConfig(temporary.root, {
            "pre-commit": [
                { entry: "true", files: "(", id: "broken-regex" },
                { alwaysRun: true, entry: "exit 0", id: "ok", passFilenames: false },
            ],
        });

        const code = runHookStage(temporary.root, ".vis-hooks", { stage: "pre-commit" }, noopLogger);

        expect(code).toBe(2);
    });
});
