import { glob as nodeGlob, globSync as nodeGlobSync } from "node:fs";
import { glob as nodeGlobAsync } from "node:fs/promises";
import { resolve } from "node:path";

import { glob as visulimaGlob, globSync as visulimaGlobSync } from "@visulima/fs";
import fastGlob from "fast-glob";
import { glob as nativeGlob, globSync as nativeGlobSync } from "glob";
import { globby, globbySync } from "globby";
import { glob as tinyGlob, globSync as tinyGlobSync } from "tinyglobby";
// eslint-disable-next-line import/no-extraneous-dependencies
import { bench, describe } from "vitest";

const fixtures = resolve("fixtures");

// Bench targets are the fixtures generated by scripts/create-fixtures.mjs:
// a deep tree a/b/c/d/e/f/g/h/i/j/ plus ~6 random *.txt files per directory,
// start.txt at the leaf, and a few seeded targets along the way.
const patterns = {
    /** Shallow: matches only the ~6 random .txt files at one level. */
    shallow: "a/b/*.txt",
    /** Specific deep file: `a/b/c/d/e/f/g/h/i/j/start.txt`. */
    specific: "**/start.txt",
    /** Broad: the vast majority of files in the fixture tree. */
    broad: "**/*.txt",
    // Everything (no ignores). Targets the upstream tinyglobby perf guard
    // (`**` / `**\/*` with empty ignore → `fdir` gets `exclude: undefined`).
    all: "**",
    /** Miss: no entries in the tree end in .xyz. */
    miss: "**/*.xyz",
} as const;

const collectAsyncIter = async (iter: AsyncIterable<string>): Promise<number> => {
    let total = 0;

    for await (const _ of iter) {
        total += 1;
    }

    return total;
};

const collectIter = (iter: Iterable<string>): number => {
    let total = 0;

    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    for (const _ of iter) {
        total += 1;
    }

    return total;
};

// node:fs.glob (callback form) wrapped into a Promise resolving to the count.
const nodeGlobCallback = (pattern: string): Promise<number> =>
    new Promise((resolvePromise, rejectPromise) => {
        // eslint-disable-next-line unicorn/no-array-callback-reference
        nodeGlob(pattern, { cwd: fixtures }, (error, matches) => {
            if (error) {
                rejectPromise(error);

                return;
            }

            resolvePromise(matches.length);
        });
    });

for (const [label, pattern] of Object.entries(patterns)) {
    describe(`glob async — ${label} (${pattern})`, () => {
        bench("@visulima/fs glob", async () => {
            await visulimaGlob(pattern, { cwd: fixtures });
        });

        bench("node:fs/promises glob", async () => {
            await collectAsyncIter(nodeGlobAsync(pattern, { cwd: fixtures }));
        });

        bench("node:fs glob (callback)", async () => {
            await nodeGlobCallback(pattern);
        });

        bench("fast-glob", async () => {
            await fastGlob(pattern, { cwd: fixtures });
        });

        bench("tinyglobby", async () => {
            await tinyGlob(pattern, { cwd: fixtures });
        });

        bench("globby", async () => {
            await globby(pattern, { cwd: fixtures });
        });

        bench("glob (node-glob)", async () => {
            await nativeGlob(pattern, { cwd: fixtures });
        });
    });

    describe(`glob sync — ${label} (${pattern})`, () => {
        bench("@visulima/fs globSync", () => {
            visulimaGlobSync(pattern, { cwd: fixtures });
        });

        bench("node:fs globSync", () => {
            collectIter(nodeGlobSync(pattern, { cwd: fixtures }) as unknown as Iterable<string>);
        });

        bench("fast-glob.sync", () => {
            fastGlob.sync(pattern, { cwd: fixtures });
        });

        bench("tinyglobby.globSync", () => {
            tinyGlobSync(pattern, { cwd: fixtures });
        });

        bench("globby.sync", () => {
            globbySync(pattern, { cwd: fixtures });
        });

        bench("glob.sync (node-glob)", () => {
            nativeGlobSync(pattern, { cwd: fixtures });
        });
    });
}
