/**
 * Error code constants for type safety.
 */
export const ErrorCodes = {
    CACHE_DIRECTORY_NOT_FOUND: "CACHE_DIRECTORY_NOT_FOUND",
    COMMAND_NOT_FOUND: "COMMAND_NOT_FOUND",
    COMMAND_VALIDATION_ERROR: "COMMAND_VALIDATION_ERROR",
    CONFLICTING_OPTIONS: "CONFLICTING_OPTIONS",
    DUPLICATE_COMMAND: "DUPLICATE_COMMAND",
    INVALID_ARGUMENT: "INVALID_ARGUMENT",
    INVALID_COMMAND_NAME: "INVALID_COMMAND_NAME",
    INVALID_INPUT: "INVALID_INPUT",
    INVALID_PLUGIN_NAME: "INVALID_PLUGIN_NAME",
    INVALID_RUNTIME: "INVALID_RUNTIME",
    INVALID_SHELL: "INVALID_SHELL",
    PLUGIN_ERROR: "PLUGIN_ERROR",
    SECURITY_ERROR: "SECURITY_ERROR",
    UNKNOWN_OPTION: "UNKNOWN_OPTION",
    UPDATE_NOTIFIER_ERROR: "UPDATE_NOTIFIER_ERROR",
    VERSION_FETCH_ERROR: "VERSION_FETCH_ERROR",
    VERSION_PARSE_ERROR: "VERSION_PARSE_ERROR",
} as const satisfies Record<string, string>;

export type ErrorCode = keyof typeof ErrorCodes;
