.github/**
plop/**
.husky/**
.nx/**
.czrc
.editorconfig
.gitattributes
.gitignore
.lintstagedrc.cjs
.lintstagedrc.cjs
.npmignore
.nxignore
.prettierignore
prettier.config.js
.secretlintignore
.secretlintrc.cjs
.textlintignore
.textlintrc
.yamllint.yaml
codecov.yml
commitlint.config.cjs
nx.json
plop.js
pnpm-lock.yaml
pnpm-workspace.yaml
taze.config.js
tsconfig.base.json
tsconfig.json
