# Always comment on PRs, always create new comments
comment:
  behavior: new
  require_changes: false

# Require a minimum coverage for the codecov/project PR check
coverage:
  status:
    patch: off
    project:
      default:
        target: 75%
        threshold: 1%
