"package: ansi":
    - changed-files:
          - any-glob-to-any-file: "packages/terminal/ansi/**/*"
"package: api-platform":
    - changed-files:
          - any-glob-to-any-file: "packages/api/api-platform/**/*"
"package: boxen":
    - changed-files:
          - any-glob-to-any-file: "packages/terminal/boxen/**/*"
"package: bytes":
    - changed-files:
          - any-glob-to-any-file: "packages/data-manipulation/bytes/**/*"
"package: cerebro":
    - changed-files:
          - any-glob-to-any-file: "packages/terminal/cerebro/**/*"
"package: colorize":
    - changed-files:
          - any-glob-to-any-file: "packages/terminal/colorize/**/*"
"package: command-line-args":
    - changed-files:
          - any-glob-to-any-file: "packages/terminal/command-line-args/**/*"
"package: connect":
    - changed-files:
          - any-glob-to-any-file: "packages/api/connect/**/*"
"package: content-safety":
    - changed-files:
          - any-glob-to-any-file: "packages/data-manipulation/content-safety/**/*"
"package: crud":
    - changed-files:
          - any-glob-to-any-file: "packages/api/crud/**/*"
"package: deep-clone":
    - changed-files:
          - any-glob-to-any-file: "packages/data-manipulation/deep-clone/**/*"
"package: disposable-email-domains":
    - changed-files:
          - any-glob-to-any-file: "packages/email/disposable-email-domains/**/*"
"package: email":
    - changed-files:
          - any-glob-to-any-file: "packages/email/email/**/*"
"package: error":
    - changed-files:
          - any-glob-to-any-file: "packages/error-debugging/error/**/*"
"package: error-handler":
    - changed-files:
          - any-glob-to-any-file: "packages/error-debugging/error-handler/**/*"
"package: find-cache-dir":
    - changed-files:
          - any-glob-to-any-file: "packages/filesystem/find-cache-dir/**/*"
"package: fmt":
    - changed-files:
          - any-glob-to-any-file: "packages/terminal/fmt/**/*"
"package: fs":
    - changed-files:
          - any-glob-to-any-file: "packages/filesystem/fs/**/*"
"package: health-check":
    - changed-files:
          - any-glob-to-any-file: "packages/api/health-check/**/*"
"package: html":
    - changed-files:
          - any-glob-to-any-file: "packages/data-manipulation/html/**/*"
"package: humanizer":
    - changed-files:
          - any-glob-to-any-file: "packages/data-manipulation/humanizer/**/*"
"package: inspector":
    - changed-files:
          - any-glob-to-any-file: "packages/error-debugging/inspector/**/*"
"package: is-ansi-color-supported":
    - changed-files:
          - any-glob-to-any-file: "packages/terminal/is-ansi-color-supported/**/*"
"package: iso-locale":
    - changed-files:
          - any-glob-to-any-file: "packages/data-manipulation/iso-locale/**/*"
"package: jsdoc-open-api":
    - changed-files:
          - any-glob-to-any-file: "packages/api/jsdoc-open-api/**/*"
"package: nuxt":
    - changed-files:
          - any-glob-to-any-file: "packages/storage/storage/src/adapter/nuxt/**/*"
"package: object":
    - changed-files:
          - any-glob-to-any-file: "packages/data-manipulation/object/**/*"
"package: ono":
    - changed-files:
          - any-glob-to-any-file: "packages/error-debugging/ono/**/*"
"package: package":
    - changed-files:
          - any-glob-to-any-file: "packages/tooling/package/**/*"
"package: pagination":
    - changed-files:
          - any-glob-to-any-file: "packages/api/pagination/**/*"
"package: pail":
    - changed-files:
          - any-glob-to-any-file: "packages/error-debugging/pail/**/*"
"package: path":
    - changed-files:
          - any-glob-to-any-file: "packages/filesystem/path/**/*"
"package: prisma-dmmf-transformer":
    - changed-files:
          - any-glob-to-any-file: "packages/tooling/prisma-dmmf-transformer/**/*"
"package: redact":
    - changed-files:
          - any-glob-to-any-file: "packages/data-manipulation/redact/**/*"
"package: source-map":
    - changed-files:
          - any-glob-to-any-file: "packages/error-debugging/source-map/**/*"
"package: storage":
    - changed-files:
          - any-glob-to-any-file: "packages/storage/storage/**/*"
"package: storage-client":
    - changed-files:
          - any-glob-to-any-file: "packages/storage/storage-client/**/*"
"package: string":
    - changed-files:
          - any-glob-to-any-file: "packages/data-manipulation/string/**/*"
"package: tabular":
    - changed-files:
          - any-glob-to-any-file: "packages/terminal/tabular/**/*"
"package: tsconfig":
    - changed-files:
          - any-glob-to-any-file: "packages/tooling/tsconfig/**/*"
"package: vite-overlay":
    - changed-files:
          - any-glob-to-any-file: "packages/error-debugging/vite-overlay/**/*"
"documentation":
    - changed-files:
          - any-glob-to-any-file: "docs/**/*"
