packages:
    - "!**/__test__/**"
    - "!**/__tests__/**"
    - "!packages/api-platform/__fixtures__/**"
    - "!packages/error/__fixtures__/**"
    - "!packages/jsdoc-open-api/__fixtures__/**"
    - "!packages/package/__fixtures__/package-json/**"
    - "!packages/package/__fixtures__/read-tsconfig/**"
    - "!packages/package/__fixtures__/which-package-manager/**"
    - "!packages/package/__fixtures__/workspaces/**"
    - "!packages/readdir/__fixtures__/**"
    - "**/__bench__/**"
    - "apps/**"
    - "examples/**"
    - "packages/**"
    - "packages/boxen/__fixtures__/package/cjs"
    - "packages/boxen/__fixtures__/package/mjs"
    - "packages/colorize/__fixtures__/package/cjs"
    - "packages/colorize/__fixtures__/package/mjs"
    - "packages/cerebro/__fixtures__/package/cjs"
    - "packages/cerebro/__fixtures__/package/mjs"
    - "packages/package/__fixtures__/package/cjs"
    - "packages/package/__fixtures__/package/mjs"
    - "packages/pail/__fixtures__/package/cjs"
    - "packages/pail/__fixtures__/package/mjs"
