packages:
    - "examples/**"
    - "packages/**/**"
    - "!**/__fixture__/**"
    - "!**/__fixtures__/**"
    - "!**/__test__/unit/**"
    - "!**/__tests__/unit/**"
    - "packages/crud/__tests__/integration/adapter/prisma"
    - "visulima"
    - "docs"
    - "storybook"
