packages:
  - '!**/__test__/**'
  - '!**/__tests__/**'
  - '!packages/api-platform/__fixtures__/**'
  - '!packages/error/__fixtures__/**'
  - '!packages/jsdoc-open-api/__fixtures__/**'
  - '!packages/package/__fixtures__/package-json/**'
  - '!packages/package/__fixtures__/read-tsconfig/**'
  - '!packages/package/__fixtures__/which-package-manager/**'
  - '!packages/package/__fixtures__/workspaces/**'
  - '!packages/readdir/__fixtures__/**'
  - apps/**
  - examples/**
  - packages/**
  - shared/**
  - packages/boxen/__bench__
  - packages/colorize/__bench__
  - packages/deep-clone/__bench__
  - packages/fmt/__bench__
  - packages/inspector/__bench__
  - packages/pail/__bench__
  - packages/string/__bench__
  - packages/tabular/__bench__
  - packages/fs/__bench__
  - packages/redact/__bench__
  - packages/colorize/__fixtures__/package/cjs
  - packages/colorize/__fixtures__/package/mjs
  - packages/cerebro/__fixtures__/package/cjs
  - packages/cerebro/__fixtures__/package/mjs
  - packages/package/__fixtures__/package/cjs
  - packages/package/__fixtures__/package/mjs
  - packages/pail/__fixtures__/package/cjs
  - packages/pail/__fixtures__/package/mjs
  - packages/boxen/__fixtures__/package/cjs
  - packages/boxen/__fixtures__/package/mjs
  - packages/path/__fixtures__/package/cjs
  - packages/path/__fixtures__/package/mjs
  - packages/redact/__fixtures__/package/cjs
  - packages/redact/__fixtures__/package/mjs
  - packages/tsconfig/__fixtures__/package/cjs
  - packages/tsconfig/__fixtures__/package/mjs

dedupeInjectedDeps: true

disallowWorkspaceCycles: true

ignoreWorkspaceCycles: false

ignoredOptionalDependencies:
  - fsevents
  - dtrace-provider

includeWorkspaceRoot: false

injectWorkspacePackages: false

linkWorkspacePackages: true

minimumReleaseAgeExclude:
  - vitest
  - '@vitest/*'
  - typescript
  - '@types/*'
  - '@tanstack/*'

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@pnpm/exe'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - '@tree-sitter-grammars/tree-sitter-yaml'
  - '@visulima/string'
  - core-js
  - core-js-pure
  - dtrace-provider
  - edgedriver
  - es5-ext
  - esbuild
  - geckodriver
  - msw
  - nx
  - oxc-resolver
  - prisma
  - rs-module-lexer
  - sharp
  - tree-sitter
  - tree-sitter-json
  - unrs-resolver
  - yarn

overrides:
  '@eslint/plugin-kit@<0.3.4': '>=0.4.0'
  axios@<1.12.0: '>=1.12.2'
  body-parser@>=2.2.0 <2.2.1: '>=2.2.1'
  chrono-node@<2.2.4: '>=2.9.0'
  cookie@<0.7.0: '>=1.0.2'
  dompurify@<3.2.4: '>=3.3.0'
  dompurify@>=3.0.0 <3.1.3: '>=3.3.0'
  esbuild@<=0.24.2: '>=0.25.11'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  glob@>=11.0.0 <11.1.0: '>=11.1.0'
  hono@<4.9.7: '>=4.10.2'
  hono@>=4.8.0 <4.9.6: '>=4.10.2'
  js-yaml@<3.14.2: '>=3.14.2'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  node-forge@<1.3.2: '>=1.3.2'
  prismjs@<1.30.0: '>=1.30.0'
  tar-fs@>=3.0.0 <3.1.1: '>=3.1.1'
  tmp@<=0.2.3: '>=0.2.5'
  vite@<=5.4.19: '>=7.1.11'
  vite@>=7.1.0 <=7.1.4: '>=7.1.11'

preferWorkspacePackages: true

saveWorkspaceProtocol: true

sharedWorkspaceLockfile: true
