packages:
  - '!**/__test__/**'
  - '!**/__tests__/**'
  - '!packages/api-platform/__fixtures__/**'
  - '!packages/error/__fixtures__/**'
  - '!packages/jsdoc-open-api/__fixtures__/**'
  - '!packages/package/__fixtures__/package-json/**'
  - '!packages/package/__fixtures__/read-tsconfig/**'
  - '!packages/package/__fixtures__/which-package-manager/**'
  - '!packages/package/__fixtures__/workspaces/**'
  - '!packages/readdir/__fixtures__/**'

  - apps/**
  - examples/**
  - packages/**

  - packages/boxen/__bench__
  - packages/colorize/__bench__
  - packages/deep-clone/__bench__
  - packages/fmt/__bench__
  - packages/inspector/__bench__
  - packages/pail/__bench__
  - packages/string/__bench__
  - packages/tabular/__bench__
  - packages/fs/__bench__
  - packages/redact/__bench__

  - packages/colorize/__fixtures__/package/cjs
  - packages/colorize/__fixtures__/package/mjs
  - packages/cerebro/__fixtures__/package/cjs
  - packages/cerebro/__fixtures__/package/mjs
  - packages/package/__fixtures__/package/cjs
  - packages/package/__fixtures__/package/mjs
  - packages/pail/__fixtures__/package/cjs
  - packages/pail/__fixtures__/package/mjs
  - packages/boxen/__fixtures__/package/cjs
  - packages/boxen/__fixtures__/package/mjs
  - packages/path/__fixtures__/package/cjs
  - packages/path/__fixtures__/package/mjs
  - packages/redact/__fixtures__/package/cjs
  - packages/redact/__fixtures__/package/mjs
  - packages/tsconfig/__fixtures__/package/cjs
  - packages/tsconfig/__fixtures__/package/mjs
onlyBuiltDependencies:
  - '@pnpm/exe'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@swc/core'
  - '@tree-sitter-grammars/tree-sitter-yaml'
  - '@visulima/string'
  - core-js
  - core-js-pure
  - dtrace-provider
  - edgedriver
  - es5-ext
  - esbuild
  - geckodriver
  - msw
  - nx
  - prisma
  - sharp
  - tree-sitter
  - tree-sitter-json
  - unrs-resolver
  - yarn
ignoredBuiltDependencies:
  - '@anolilab/eslint-config'
