packages:
  - '!**/__test__/**'
  - '!**/__tests__/**'
  - '!packages/api/api-platform/__fixtures__/**'
  - '!packages/error-debugging/error/__fixtures__/**'
  - '!packages/tooling/jsdoc-open-api/__fixtures__/**'
  - '!packages/tooling/package/__fixtures__/package-json/**'
  - '!packages/tooling/package/__fixtures__/read-tsconfig/**'
  - '!packages/tooling/package/__fixtures__/which-package-manager/**'
  - '!packages/tooling/package/__fixtures__/workspaces/**'
  - '!packages/storage/storage/src/adapter/nuxt'
  - apps/**
  - examples/**
  - examples/uploads/**
  - packages/**
  - shared/**
  - packages/terminal/boxen/__bench__
  - packages/terminal/colorize/__bench__
  - packages/data-manipulation/deep-clone/__bench__
  - packages/terminal/fmt/__bench__
  - packages/error-debugging/inspector/__bench__
  - packages/error-debugging/pail/__bench__
  - packages/data-manipulation/string/__bench__
  - packages/terminal/tabular/__bench__
  - packages/filesystem/fs/__bench__
  - packages/data-manipulation/redact/__bench__
  - packages/terminal/command-line-args/__bench__
  - packages/terminal/cerebro/__bench__
  - packages/terminal/colorize/__fixtures__/package/cjs
  - packages/terminal/colorize/__fixtures__/package/mjs
  - packages/terminal/cerebro/__fixtures__/package/cjs
  - packages/terminal/cerebro/__fixtures__/package/mjs
  - packages/tooling/package/__fixtures__/package/cjs
  - packages/tooling/package/__fixtures__/package/mjs
  - packages/error-debugging/pail/__fixtures__/package/cjs
  - packages/error-debugging/pail/__fixtures__/package/mjs
  - packages/terminal/boxen/__fixtures__/package/cjs
  - packages/terminal/boxen/__fixtures__/package/mjs
  - packages/filesystem/path/__fixtures__/package/cjs
  - packages/filesystem/path/__fixtures__/package/mjs
  - packages/data-manipulation/redact/__fixtures__/package/cjs
  - packages/data-manipulation/redact/__fixtures__/package/mjs
  - packages/tooling/tsconfig/__fixtures__/package/cjs
  - packages/tooling/tsconfig/__fixtures__/package/mjs

dedupeInjectedDeps: true

disallowWorkspaceCycles: true

ignoreWorkspaceCycles: false

ignoredOptionalDependencies:
  - fsevents
  - dtrace-provider

includeWorkspaceRoot: false

injectWorkspacePackages: false

linkWorkspacePackages: true

minimumReleaseAgeExclude:
  - vitest
  - '@vitest/*'
  - typescript
  - '@types/*'
  - '@tanstack/*'

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@pnpm/exe'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - '@tree-sitter-grammars/tree-sitter-yaml'
  - '@visulima/string'
  - aws-crt
  - core-js
  - core-js-pure
  - dtrace-provider
  - edgedriver
  - es5-ext
  - esbuild
  - geckodriver
  - msw
  - nx
  - oxc-resolver
  - prisma
  - protobufjs
  - rs-module-lexer
  - sharp
  - svelte-preprocess
  - tree-sitter
  - tree-sitter-json
  - unrs-resolver
  - vue-demi
  - yarn

overrides:
  '@eslint/plugin-kit@<0.3.4': '>=0.4.0'
  '@modelcontextprotocol/sdk@<1.24.0': '>=1.24.0'
  axios@<1.12.0: '>=1.12.2'
  body-parser@>=2.2.0 <2.2.1: '>=2.2.1'
  chrono-node@<2.2.4: '>=2.9.0'
  cookie@<0.7.0: '>=1.0.2'
  dompurify@<3.2.4: '>=3.3.0'
  dompurify@>=3.0.0 <3.1.3: '>=3.3.0'
  esbuild@<=0.24.2: '>=0.25.11'
  express@<4.22.0: '>=4.22.0'
  express@>=5.0.0 <5.2.0: '>=5.2.0'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  glob@>=11.0.0 <11.1.0: '>=11.1.0'
  hono@<4.9.7: '>=4.10.2'
  hono@>=4.8.0 <4.9.6: '>=4.10.2'
  js-yaml@<3.14.2: '>=3.14.2'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  jws@=4.0.0: '>=4.0.1'
  mdast-util-to-hast@>=13.0.0 <13.2.1: '>=13.2.1'
  next@>=16.0.0-canary.0 <16.0.7: '>=16.0.7'
  node-forge@<1.3.2: '>=1.3.2'
  prismjs@<1.30.0: '>=1.30.0'
  tar-fs@>=3.0.0 <3.1.1: '>=3.1.1'
  tmp@<=0.2.3: '>=0.2.5'
  valibot@>=0.31.0 <1.2.0: '>=1.2.0'
  vite@<=5.4.19: '>=7.1.11'
  vite@>=7.1.0 <=7.1.4: '>=7.1.11'

preferWorkspacePackages: true

saveWorkspaceProtocol: true

sharedWorkspaceLockfile: true
