packages:
    - "!**/__test__/**"
    - "!**/__tests__/**"
    - "!packages/api-platform/__fixtures__/**"
    - "!packages/error/__fixtures__/**"
    - "!packages/jsdoc-open-api/__fixtures__/**"
    - "!packages/package/__fixtures__/**"
    - "!packages/readdir/__fixtures__/**"
    - "**/__bench__/**"
    - "apps/**"
    - "examples/**"
    - "packages/**"
    - "packages/colorize/__fixtures__/package/cjs"
    - "packages/colorize/__fixtures__/package/mjs"
