packages:
    - "!**/__test__/**"
    - "!**/__tests__/**"
    - "!packages/api-platform/__fixtures__/**"
    - "!packages/error/__fixtures__/**"
    - "!packages/jsdoc-open-api/__fixtures__/**"
    - "!packages/package/__fixtures__/package/**"
    - "!packages/package/__fixtures__/which-package-manager/**"
    - "!packages/package/__fixtures__/workspaces/**"
    - "!packages/readdir/__fixtures__/foo"
    - "**/__bench__/**"
    - "docs"
    - "examples/**"
    - "packages/**"
    - "packages/colorize/__fixtures__/package/cjs"
    - "packages/colorize/__fixtures__/package/mjs"
    - "packages/package/__fixtures__/cjs"
    - "packages/package/__fixtures__/mjs"
    - "packages/readdir/__fixtures__/package/cjs"
    - "packages/readdir/__fixtures__/package/mjs"
