import { defineWorkspace } from "vitest/config";

export default defineWorkspace([
    "./apps/docs/vitest.config.ts",
    "./packages/tooling/package/vitest.config.ts",
    "./packages/terminal/boxen/vitest.config.ts",
    "./packages/error-debugging/error/vitest.config.ts",
    "./packages/filesystem/fs/vitest.config.ts",
    "./packages/terminal/colorize/vitest.config.ts",
    "./packages/data-manipulation/humanizer/vitest.config.ts",
    "./packages/api/connect/vitest.config.ts",
    "./packages/data-manipulation/string/vitest.config.ts",
    "./packages/error-debugging/source-map/vitest.config.ts",
    "./packages/api/api-platform/vitest.config.ts",
    "./packages/api/crud/vitest.config.ts",
    "./packages/api/health-check/vitest.config.ts",
    "./packages/flame/vitest.config.ts",
    "./packages/filesystem/find-cache-dir/vitest.config.ts",
    "./packages/data-manipulation/object/vitest.config.ts",
    "./packages/tooling/prisma-dmmf-transformer/vitest.config.ts",
    "./packages/data-manipulation/redact/vitest.config.ts",
    "./packages/terminal/ansi/vitest.config.ts",
    "./packages/error-debugging/pail/vitest.config.ts",
    "./packages/filesystem/path/vitest.config.ts",
    "./packages/tooling/tsconfig/vitest.config.ts",
    "./packages/terminal/fmt/vitest.config.ts",
    "./packages/terminal/cerebro/vitest.config.ts",
    "./packages/terminal/is-ansi-color-supported/vitest.config.ts",
    "./packages/terminal/tabular/vitest.config.ts",
    "./packages/data-manipulation/deep-clone/vitest.config.ts",
    "./packages/api/pagination/vitest.config.ts",
    "./packages/tooling/jsdoc-open-api/vitest.config.ts",
    "./packages/error-debugging/inspector/vitest.config.ts",
]);
