import { createConfig } from "@anolilab/eslint-config";

/** @type {import("@anolilab/eslint-config").PromiseFlatConfigComposer} */
export default createConfig(
    {
        ignores: [
            "dist",
            "node_modules",
            "coverage",
            "__fixtures__",
            "__docs__",
            "assets",
            "index.js",
            "vitest.config.ts",
            "packem.config.ts",
            ".secretlintrc.cjs",
            "package.json",
            "README.md",
            "prettier.config.js",
            "native/Cargo.toml",
            "native/deny.toml",
            "native/index.d.ts",
        ],
        typescript: {
            tsconfigPath: "./tsconfig.eslint.json",
        },
    },
    {
        rules: {
            "@stylistic/max-statements-per-line": "off",
            "@stylistic/no-extra-parens": "off",
            "@stylistic/quotes": "off",
            "@typescript-eslint/no-misused-promises": "off",
            "@typescript-eslint/no-non-null-assertion": "off",
            "@typescript-eslint/no-shadow": "off",
            "@typescript-eslint/no-unnecessary-condition": "off",
            "@typescript-eslint/no-unsafe-argument": "off",
            "@typescript-eslint/no-unsafe-assignment": "off",
            "@typescript-eslint/no-unsafe-call": "off",
            "@typescript-eslint/no-unsafe-member-access": "off",
            "@typescript-eslint/no-unsafe-return": "off",
            "@typescript-eslint/no-use-before-define": "off",
            "@typescript-eslint/prefer-nullish-coalescing": "off",
            "@typescript-eslint/prefer-promise-reject-errors": "off",
            "@typescript-eslint/require-await": "off",
            "@typescript-eslint/restrict-template-expressions": "off",
            "antfu/if-newline": "off",
            "e18e/prefer-static-regex": "off",
            "import/exports-last": "off",
            "import/no-namespace": "off",
            "import/prefer-default-export": "off",
            "jsdoc/check-indentation": "off",
            "jsdoc/check-param-names": "off",
            "jsdoc/escape-inline-tags": "off",
            "jsdoc/match-description": "off",
            "no-confusing-arrow": "off",
            "no-for-of-array/no-for-of-array": "off",
            "no-param-reassign": "off",
            "no-plusplus": "off",
            "promise/param-names": "off",
            "sonarjs/cognitive-complexity": "off",
            "sonarjs/function-return-type": "off",
            "sonarjs/no-alphabetical-sort": "off",
            "sonarjs/no-misleading-array-reverse": "off",
            "sonarjs/no-nested-conditional": "off",
            "sonarjs/no-nested-functions": "off",
            "sonarjs/no-os-command-from-path": "off",
            "sonarjs/no-undefined-argument": "off",
            "sonarjs/publicly-writable-directories": "off",
            "unicorn/no-abusive-eslint-disable": "off",
            "unicorn/no-array-callback-reference": "off",
            "unicorn/no-array-sort": "off",
            "unicorn/no-null": "off",
            "unicorn/prevent-abbreviations": "off",
            "vitest/no-conditional-expect": "off",
        },
    },
    {
        files: ["__tests__/**/*"],
        rules: {
            "no-secrets/no-secrets": "off",
            "sonarjs/no-hardcoded-secrets": "off",
            "vitest/no-conditional-in-test": "off",
            "vitest/require-top-level-describe": "off",
        },
    },
);
