/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface Finding {
  ruleId: string
  description: string
  file: string
  startLine: number
  endLine: number
  startColumn: number
  endColumn: number
  match: string
  secret: string
  entropy: number
  tags: Array<string>
  /**
   * Rule provenance — `"gitleaks"`, `"kingfisher"`, `"visulima"`, or a user string.
   * `None` for legacy rules that don't declare a source.
   */
  source?: string
  /**
   * Author-declared quality signal: `"low"`, `"medium"`, or `"high"`. Always set —
   * rules that don't declare confidence resolve to `"low"`.
   */
  confidence: string
  /**
   * Rule ids that matched the same byte span and were collapsed by the dedup
   * pass. Lets reporters surface "also: X, Y" without emitting duplicate findings.
   */
  alternateMatches: Array<string>
}

/**
 * Compile a ruleset and return rules that failed to compile, with their reason.
 * Useful for tooling that wants to validate a custom gitleaks.toml.
 */
export declare function inspectRuleset(options?: ScanOptions | undefined | null): Array<SkippedRule>

/** Return metadata for every rule compiled from the config. */
export declare function listRules(options?: ScanOptions | undefined | null): Array<RuleInfo>

export interface RuleInfo {
  id: string
  description: string
  tags: Array<string>
  keywords: Array<string>
  entropy?: number
  hasRegex: boolean
  hasPathFilter: boolean
  /**
   * `true` when the rule has no `keywords` and therefore bypasses the AC prefilter —
   * its main regex runs against every file. Surface this in tooling so users can spot
   * perf-regressing custom rules (#1675).
   */
  alwaysRuns: boolean
  source?: string
  confidence: string
}

export declare function scan(paths: Array<string>, options?: ScanOptions | undefined | null): Promise<Array<Finding>>

/** Scan a fixed list of files (e.g. from `git diff --name-only`). Bypasses the walker. */
export declare function scanFiles(files: Array<string>, options?: ScanOptions | undefined | null): Promise<Array<Finding>>

export interface ScanOptions {
  /**
   * Parsed config object (gitleaks-compatible shape). The JS wrapper is responsible
   * for loading from any format (TOML/JSON/YAML/TS/JS) via c12 and passing the result
   * here. If absent, no rules are loaded and every scan returns an empty result.
   */
  config?: any
  /** Respect .gitignore / .ignore (default: true) */
  respectGitignore?: boolean
  /** Visit dotfiles (default: false — matches ignore crate default) */
  includeHidden?: boolean
  /** Extra gitignore-syntax patterns to exclude (negation, directory markers, etc. all work). */
  extraIgnores?: Array<string>
  /**
   * Paths to additional `.gitignore`-syntax files to honor (beyond the walker's default
   * `.gitignore` / `.git/info/exclude` pickup). Useful for `.secretsignore` etc.
   */
  ignoreFiles?: Array<string>
  /** Max file size in bytes (default 10 MiB). Files above are skipped. */
  maxFileSize?: number
  /** Redact secret values in output (default: false) */
  redact?: boolean
  /** Number of rayon worker threads. 0/omitted = use rayon's global pool. */
  concurrency?: number
  /**
   * Minimum author-declared confidence required for a rule to load. Accepts
   * "low" | "medium" | "high". Unset (or "low") loads every rule — matching
   * legacy behaviour. Rules with no declared confidence are treated as "low"
   * and so are dropped whenever a higher floor is set.
   */
  minConfidence?: string
}

export declare function scanSync(paths: Array<string>, options?: ScanOptions | undefined | null): Array<Finding>

export declare function scanTextSync(content: string, file: string, options?: ScanOptions | undefined | null): Array<Finding>

export interface SkippedRule {
  ruleId: string
  reason: string
}
