/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface Finding {
    ruleId: string;
    description: string;
    file: string;
    startLine: number;
    endLine: number;
    startColumn: number;
    endColumn: number;
    match: string;
    secret: string;
    entropy: number;
    tags: Array<string>;
}

/**
 * Compile a ruleset and return rules that failed to compile, with their reason.
 * Useful for tooling that wants to validate a custom gitleaks.toml.
 */
export declare function inspectRuleset(options?: ScanOptions | undefined | null): Array<SkippedRule>;

/** Return metadata for every rule compiled from the config. */
export declare function listRules(options?: ScanOptions | undefined | null): Array<RuleInfo>;

export interface RuleInfo {
    id: string;
    description: string;
    tags: Array<string>;
    keywords: Array<string>;
    entropy?: number;
    hasRegex: boolean;
    hasPathFilter: boolean;
}

export declare function scan(paths: Array<string>, options?: ScanOptions | undefined | null): Promise<Array<Finding>>;

/** Scan a fixed list of files (e.g. from `git diff --name-only`). Bypasses the walker. */
export declare function scanFiles(files: Array<string>, options?: ScanOptions | undefined | null): Promise<Array<Finding>>;

export interface ScanOptions {
    /**
     * Path to a gitleaks-compatible TOML config. If omitted, the caller is expected
     * to provide `configToml`, otherwise no rules are loaded.
     */
    configPath?: string;
    /** Raw TOML rule string (used as-is, no file IO). */
    configToml?: string;
    /** Respect .gitignore / .ignore (default: true) */
    respectGitignore?: boolean;
    /** Visit dotfiles (default: false — matches ignore crate default) */
    includeHidden?: boolean;
    /** Extra glob patterns to exclude (rooted at each scan root) */
    extraIgnores?: Array<string>;
    /** Max file size in bytes (default 10 MiB). Files above are skipped. */
    maxFileSize?: number;
    /** Redact secret values in output (default: false) */
    redact?: boolean;
    /** Number of rayon worker threads. 0/omitted = use rayon's global pool. */
    concurrency?: number;
}

export declare function scanSync(paths: Array<string>, options?: ScanOptions | undefined | null): Array<Finding>;

export declare function scanTextSync(content: string, file: string, options?: ScanOptions | undefined | null): Array<Finding>;

export interface SkippedRule {
    ruleId: string;
    reason: string;
}
