// eslint-disable-next-line import/no-extraneous-dependencies
import ansiRegex from "ansi-regex";

/**
 * Regular expression for matching ANSI escape codes, generated by the `ansi-regex` package.
 * This regex is used by the {@link strip} function to remove ANSI codes from strings.
 * @see {@link https://github.com/chalk/ansi-regex ansi-regex repository}
 * @internal
 */
const regex = ansiRegex();

/**
 * Removes ANSI escape codes from a string.
 *
 * This function first removes OSC (Operating System Command) sequences like title strings
 * (e.g., `]0;title`) and then uses a comprehensive regex (from the `ansi-regex` package)
 * to strip all other ANSI escape codes.
 * @param input The string from which to remove ANSI escape codes.
 * @returns The input string with all ANSI escape codes stripped.
 * @example
 * ```typescript
 * import { strip } from "@visulima/ansi";
 *
 * const textWithAnsi = "\x1b[32mHello, \x1b[1mWorld!\x1b[0m";
 * const strippedText = strip(textWithAnsi);
 * console.log(strippedText); // Output: "Hello, World!"
 *
 * const titleSequence = "]0;My Window TitleSome content";
 * const strippedTitle = strip(titleSequence);
 * console.log(strippedTitle); // Output: "Some content"
 * ```
 */
// eslint-disable-next-line no-control-regex
const OSC_TITLE_REGEX = /\]0;[\s\S]*?/g;

const strip = (input: string): string => input.replace(OSC_TITLE_REGEX, "").replace(regex, "");

export default strip;
