/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Collects all files in a directory recursively, ignoring common non-source directories.
 * Returns a list of absolute file paths.
 */
export declare function collectFiles(dir: string): Array<string>

/**
 * Computes the final combined hash from task hash details using xxh3-128.
 * This produces the cache key used for lookup.
 */
export declare function computeTaskHash(details: NativeTaskHashDetails): string

/** Result of cycle detection. */
export interface CycleResult {
  /** Whether a cycle was found. */
  hasCycle: boolean
  /** The cycle as a list of task IDs, or empty if no cycle. */
  cycle: Array<string>
}

/** A single file hash result. */
export interface FileHash {
  path: string
  hash: string
}

/** Finds all cycles in the task graph. */
export declare function findAllCycles(graph: NativeTaskGraph): Array<Array<string>>

/**
 * Makes the graph acyclic by removing back edges.
 * Returns the edges that were removed.
 */
export declare function findBackEdges(graph: NativeTaskGraph): Array<Array<string>>

/** Finds a single cycle in the task graph using DFS. */
export declare function findCycle(graph: NativeTaskGraph): CycleResult

/** Gets all tasks that depend on the given task (reverse transitive dependencies). */
export declare function getDependentTasks(graph: NativeTaskGraph, taskId: string): Array<string>

/** Gets all transitive dependencies of a task. */
export declare function getTransitiveDeps(graph: NativeTaskGraph, taskId: string): Array<string>

/**
 * Computes the command hash for a task using xxh3-128.
 * Takes project name, target name, optional configuration, and sorted overrides JSON.
 */
export declare function hashCommand(project: string, target: string, configuration: string | undefined | null, overridesJson: string): string

/** Hashes an environment variable name + value pair using xxh3-128. */
export declare function hashEnvVar(name: string, value: string): string

/**
 * Computes the xxh3-128 hash of a single file.
 * Returns the hex-encoded hash string.
 *
 * Uses xxHash xxh3 (same as Nx) for maximum hashing throughput.
 * xxh3 is ~5-10x faster than SHA-256 on modern CPUs with SIMD.
 */
export declare function hashFile(filePath: string): string

/**
 * Computes xxh3-128 hashes for multiple files in parallel.
 * Takes absolute file paths, returns relative_path + hash pairs.
 */
export declare function hashFilesBatch(filePaths: Array<string>, workspaceRoot: string): Array<FileHash>

/**
 * Collects all files in a directory and computes xxh3-128 hashes for each,
 * using parallel processing via rayon for maximum throughput.
 *
 * Returns a list of { path, hash } objects where path is relative to workspace_root.
 */
export declare function hashFilesInDirectory(dir: string, workspaceRoot: string): Array<FileHash>

/**
 * Computes an xxh3-128 hash from a string.
 * Useful for hashing command strings, JSON, etc.
 */
export declare function hashString(input: string): string

/**
 * Computes a combined xxh3-128 hash from multiple strings.
 * Strings are concatenated and hashed, producing a single deterministic hash.
 */
export declare function hashStrings(inputs: Array<string>): string

/** Represents a task graph for native graph operations. */
export interface NativeTaskGraph {
  /** All task IDs in the graph. */
  taskIds: Array<string>
  /** Dependencies as pairs of [from_task_id, to_task_id]. */
  edges: Array<Array<string>>
}

/** Represents the hash details for a task. */
export interface NativeTaskHashDetails {
  /** The command hash. */
  command: string
  /** File/node hashes as key-value pairs [key, hash]. */
  nodes: Array<Array<string>>
  /** Implicit dependency hashes as key-value pairs [key, hash]. */
  implicitDeps?: Array<Array<string>>
  /** Runtime hashes as key-value pairs [key, hash]. */
  runtime?: Array<Array<string>>
}

/**
 * Performs a topological sort of the task graph.
 * Returns task IDs in topological order (dependencies first).
 */
export declare function topologicalSort(graph: NativeTaskGraph): Array<string>
