/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ApiUploadTusRouteImport } from "./routes/api.upload.tus";
import { Route as ApiUploadMultipartRouteImport } from "./routes/api.upload.multipart";

const IndexRoute = IndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => rootRouteImport,
} as any);
const ApiUploadTusRoute = ApiUploadTusRouteImport.update({
    id: "/api/upload/tus",
    path: "/api/upload/tus",
    getParentRoute: () => rootRouteImport,
} as any);
const ApiUploadMultipartRoute = ApiUploadMultipartRouteImport.update({
    id: "/api/upload/multipart",
    path: "/api/upload/multipart",
    getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
    "/": typeof IndexRoute;
    "/api/upload/multipart": typeof ApiUploadMultipartRoute;
    "/api/upload/tus": typeof ApiUploadTusRoute;
}
export interface FileRoutesByTo {
    "/": typeof IndexRoute;
    "/api/upload/multipart": typeof ApiUploadMultipartRoute;
    "/api/upload/tus": typeof ApiUploadTusRoute;
}
export interface FileRoutesById {
    __root__: typeof rootRouteImport;
    "/": typeof IndexRoute;
    "/api/upload/multipart": typeof ApiUploadMultipartRoute;
    "/api/upload/tus": typeof ApiUploadTusRoute;
}
export interface FileRouteTypes {
    fileRoutesByFullPath: FileRoutesByFullPath;
    fullPaths: "/" | "/api/upload/multipart" | "/api/upload/tus";
    fileRoutesByTo: FileRoutesByTo;
    to: "/" | "/api/upload/multipart" | "/api/upload/tus";
    id: "__root__" | "/" | "/api/upload/multipart" | "/api/upload/tus";
    fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
    IndexRoute: typeof IndexRoute;
    ApiUploadMultipartRoute: typeof ApiUploadMultipartRoute;
    ApiUploadTusRoute: typeof ApiUploadTusRoute;
}

declare module "@tanstack/react-router" {
    interface FileRoutesByPath {
        "/": {
            id: "/";
            path: "/";
            fullPath: "/";
            preLoaderRoute: typeof IndexRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/api/upload/tus": {
            id: "/api/upload/tus";
            path: "/api/upload/tus";
            fullPath: "/api/upload/tus";
            preLoaderRoute: typeof ApiUploadTusRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/api/upload/multipart": {
            id: "/api/upload/multipart";
            path: "/api/upload/multipart";
            fullPath: "/api/upload/multipart";
            preLoaderRoute: typeof ApiUploadMultipartRouteImport;
            parentRoute: typeof rootRouteImport;
        };
    }
}

const rootRouteChildren: RootRouteChildren = {
    IndexRoute: IndexRoute,
    ApiUploadMultipartRoute: ApiUploadMultipartRoute,
    ApiUploadTusRoute: ApiUploadTusRoute,
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
    interface Register {
        ssr: true;
        router: Awaited<ReturnType<typeof getRouter>>;
    }
}
