enum Editors {
    appcode = "AppCode",
    "android-studio" = "Android Studio",
    atom = "Atom",
    "atom-beta" = "Atom Beta",
    brackets = "Brackets",
    clion = "CLion",
    code = "Visual Studio Code",
    "code-insiders" = "Visual Studio Code Insiders",
    codium = "VSCodium",
    cursor = "Cursor",
    emacs = "GNU Emacs",
    emacsforosx = "GNU Emacs for Mac OS X",
    intellij = "IntelliJ IDEA",
    idea = "IntelliJ IDEA",
    nano = "GNU nano",
    neovim = "NeoVim",
    "notepad++" = "Notepad++",
    phpstorm = "PhpStorm",
    pycharm = "PyCharm",
    rider = "Rider",
    rubymine = "RubyMine",
    sublime = "SublimeText",
    textmate = "TextMate",
    vim = "Vim",
    visualstudio = "Visual Studio",
    vscode = "Visual Studio Code",
    vscodium = "VSCodium",
    webstorm = "WebStorm",
    xcode = "Xcode",
    zed = "Zed",
}

export default Editors