import { createConfig } from "@anolilab/eslint-config";

/** @type {import("@anolilab/eslint-config").PromiseFlatConfigComposer} */
export default createConfig(
    {
        ignores: [
            "dist",
            "node_modules",
            "coverage",
            "__fixtures__",
            "__docs__",
            "examples",
            "__bench__",
            "vitest.config.ts",
            "packem.config.ts",
            ".secretlintrc.cjs",
            "prettier.config.js",
            "package.json",
            "MIGRATION-GUIDE.md",
            "README.md",
        ],
        typescript: {
            tsconfigPath: "./tsconfig.eslint.json",
        },
    },
    {
        files: ["**/*.test.ts"],
        rules: {
            "@typescript-eslint/no-explicit-any": "off",
            "no-secrets/no-secrets": "off",
            "sonarjs/no-nested-functions": "off",
            "unicorn/no-null": "off",
            "vitest/require-mock-type-parameters": "off",
        },
    },
    {
        files: ["**/*.test.ts", "__tests__/**/*.ts"],
        rules: {
            "@stylistic/max-statements-per-line": "off",
            "@typescript-eslint/no-unnecessary-condition": "off",
            "@typescript-eslint/no-unsafe-assignment": "off",
            "@typescript-eslint/no-unsafe-call": "off",
            "@typescript-eslint/no-unsafe-member-access": "off",
            "@typescript-eslint/no-unsafe-return": "off",
            "@typescript-eslint/prefer-nullish-coalescing": "off",
            "@typescript-eslint/require-await": "off",
            "@typescript-eslint/unbound-method": "off",
            "e18e/prefer-static-regex": "off",
            "no-for-of-array/no-for-of-array": "off",
            "regexp/no-unused-capturing-group": "off",
            "sonarjs/no-redundant-optional": "off",
            "vitest/unbound-method": "off",
        },
    },
    {
        files: ["**/*.ts"],
        rules: {
            "@stylistic/max-statements-per-line": "off",
            "@typescript-eslint/await-thenable": "off",
            "@typescript-eslint/no-unnecessary-condition": "off",
            "@typescript-eslint/no-unnecessary-type-conversion": "off",
            "@typescript-eslint/no-unnecessary-type-parameters": "off",
            "@typescript-eslint/no-unsafe-argument": "off",
            "@typescript-eslint/no-unsafe-assignment": "off",
            "@typescript-eslint/no-unsafe-call": "off",
            "@typescript-eslint/no-unsafe-member-access": "off",
            "@typescript-eslint/no-unsafe-return": "off",
            "@typescript-eslint/prefer-nullish-coalescing": "off",
            "@typescript-eslint/prefer-promise-reject-errors": "off",
            "@typescript-eslint/require-await": "off",
            "@typescript-eslint/restrict-plus-operands": "off",
            "@typescript-eslint/restrict-template-expressions": "off",
            "@typescript-eslint/unbound-method": "off",
            "e18e/prefer-static-regex": "off",
            "no-for-of-array/no-for-of-array": "off",
            "no-underscore-dangle": "off",
            "sonarjs/different-types-comparison": "off",
            "sonarjs/no-redundant-optional": "off",
            "sonarjs/no-undefined-argument": "off",
            "unicorn/prevent-abbreviations": "off",
        },
    },
);
