import type { WorkspaceConfiguration } from "@visulima/task-runner";
import { describe, expect, it } from "vitest";

import type { VisProjectConfiguration } from "../src/config/workspace";
import { buildCodeownersLines, renderCodeowners } from "../src/util/codeowners";

describe(buildCodeownersLines, () => {
    it("should prefix paths with each project's root and sort by path (file-source)", () => {
        expect.assertions(5);

        const workspace: WorkspaceConfiguration = {
            projects: {
                "pkg-a": {
                    owners: [{ owners: ["@team-a"], path: "src/**" }],
                    root: "packages/pkg-a",
                } as VisProjectConfiguration,
                "pkg-b": {
                    owners: [{ owners: ["@team-b"], path: "src/**" }],
                    root: "packages/pkg-b",
                } as VisProjectConfiguration,
            },
        };

        const lines = buildCodeownersLines(workspace, { orderBy: "file-source" });

        expect(lines).toHaveLength(2);
        expect(lines[0]!.path).toBe("/packages/pkg-a/src/**");
        expect(lines[0]!.owners).toStrictEqual(["@team-a"]);
        expect(lines[1]!.path).toBe("/packages/pkg-b/src/**");
        expect(lines[1]!.owners).toStrictEqual(["@team-b"]);
    });

    it("should sort by project-id then path when orderBy is 'project-id'", () => {
        expect.assertions(4);

        const workspace: WorkspaceConfiguration = {
            projects: {
                "a-project": {
                    owners: [
                        { owners: ["@a-team"], path: "tests/**" },
                        { owners: ["@a-team"], path: "src/**" },
                    ],
                    root: "packages/a-project",
                } as VisProjectConfiguration,
                "z-project": {
                    owners: [{ owners: ["@z-team"], path: "lib/**" }],
                    root: "packages/z-project",
                } as VisProjectConfiguration,
            },
        };

        const lines = buildCodeownersLines(workspace, { orderBy: "project-id" });

        expect(lines).toHaveLength(3);
        expect(lines[0]!.projectId).toBe("a-project");
        expect(lines[0]!.path).toBe("/packages/a-project/src/**");
        expect(lines[2]!.projectId).toBe("z-project");
    });

    it("should include global paths from config", () => {
        expect.assertions(3);

        const workspace: WorkspaceConfiguration = {
            projects: {
                app: {
                    owners: [{ owners: ["@app-team"], path: "src/**" }],
                    root: "apps/app",
                } as VisProjectConfiguration,
            },
        };

        const lines = buildCodeownersLines(workspace, {
            globalPaths: { "/.github/**": ["@infra"], "/docs/**": ["@docs-team"] },
        });

        expect(lines).toHaveLength(3);
        expect(lines[0]!.path).toBe("/.github/**");
        expect(lines[0]!.owners).toStrictEqual(["@infra"]);
    });

    it("should return empty lines when projects have no owners", () => {
        expect.assertions(1);

        const workspace: WorkspaceConfiguration = {
            projects: {
                empty: {
                    root: "packages/empty",
                } as VisProjectConfiguration,
            },
        };

        const lines = buildCodeownersLines(workspace, undefined);

        expect(lines).toHaveLength(0);
    });
});

describe(renderCodeowners, () => {
    it("should render header, entries with owners, channel comments, and a trailing newline", () => {
        expect.assertions(6);

        const lines = [
            { owners: ["@team-a", "@team-b"], path: "/packages/foo/src/**" },
            { channel: "#alerts", owners: ["@ops"], path: "/infra/**" },
        ];

        const output = renderCodeowners(lines, "github");
        const outputLines = output.split("\n");

        expect(outputLines[0]).toBe("# CODEOWNERS — generated by `vis sync codeowners`. Do not edit by hand.");
        expect(outputLines[1]).toBe("# Update each project's project.json `owners` field and re-run the command.");
        expect(outputLines[2]).toBe("");

        expect(outputLines[3]).toBe("/packages/foo/src/** @team-a @team-b");
        expect(outputLines[4]).toBe("/infra/** @ops    # notify: #alerts");

        expect(outputLines[outputLines.length - 1]).toBe("");
    });

    it("should produce only header and trailing newline for empty lines array", () => {
        expect.assertions(2);

        const output = renderCodeowners([], "github");
        const outputLines = output.split("\n");

        expect(outputLines).toHaveLength(4);
        expect(outputLines[outputLines.length - 1]).toBe("");
    });
});
