import { spawnSync } from "node:child_process";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { afterEach, beforeEach, describe, expect, it } from "vitest";

import { formatListResult, listHooks, parseStageScript } from "../src/commands/hook/list";
import { runHookStage } from "../src/commands/hook/run";
import { validateHooks } from "../src/commands/hook/validate";

const createTemporaryGitRepo = (): { cleanup: () => void; root: string } => {
    const root = mkdtempSync(join(tmpdir(), "vis-hook-cmd-test-"));
    const originalCwd = process.cwd();

    spawnSync("git", ["init"], { cwd: root, stdio: "ignore" });
    spawnSync("git", ["config", "user.email", "test@test.test"], { cwd: root });
    spawnSync("git", ["config", "user.name", "test"], { cwd: root });
    spawnSync("git", ["config", "commit.gpgsign", "false"], { cwd: root });
    process.chdir(root);

    return {
        cleanup: () => {
            process.chdir(originalCwd);
            rmSync(root, { force: true, recursive: true });
        },
        root,
    };
};

const writeHookScript = (root: string, stage: string, body: string): void => {
    const directory = join(root, ".vis-hooks");
    const dispatcherDirectory = join(directory, "_");

    mkdirSync(dispatcherDirectory, { recursive: true });
    writeFileSync(join(directory, stage), body, { mode: 0o755 });
    writeFileSync(join(dispatcherDirectory, "h"), "#!/usr/bin/env sh\nexit 0\n", { mode: 0o755 });
    writeFileSync(join(dispatcherDirectory, stage), `#!/usr/bin/env sh\n. "$(dirname "$0")/h"\n`, { mode: 0o755 });
};

const noopLogger = { info: (): void => undefined, warn: (): void => undefined };

// ─── parseStageScript ───────────────────────────────────────────────

describe(parseStageScript, () => {
    it("extracts `# id: name` headers emitted by the migrator", () => {
        expect.assertions(3);

        const script = ["#!/usr/bin/env sh", "# Generated by `vis hook migrate` from prek", "", "# lint-staged: lint staged files", "pnpm exec lint-staged", "", "# commitlint: validate commit message", "pnpm exec commitlint --edit"].join(
            "\n",
        );
        const blocks = parseStageScript(script);

        expect(blocks).toHaveLength(2);
        expect(blocks[0]).toStrictEqual({ command: "pnpm exec lint-staged", id: "lint-staged", name: "lint staged files" });
        expect(blocks[1]).toStrictEqual({ command: "pnpm exec commitlint --edit", id: "commitlint", name: "validate commit message" });
    });

    it("treats hand-written scripts (no headers) as a single (custom) block", () => {
        expect.assertions(2);

        const blocks = parseStageScript("#!/usr/bin/env sh\necho hi\n");

        expect(blocks).toHaveLength(1);
        expect(blocks[0]?.id).toBe("(custom)");
    });
});

// ─── listHooks ─────────────────────────────────────────────────────

describe(listHooks, () => {
    let temporary: { cleanup: () => void; root: string };

    beforeEach(() => {
        temporary = createTemporaryGitRepo();
    });

    afterEach(() => {
        temporary.cleanup();
    });

    it("returns an empty result when the hooks directory is missing", () => {
        expect.assertions(1);

        const result = listHooks(temporary.root, ".vis-hooks");

        expect(result.stages).toStrictEqual([]);
    });

    it("groups discovered hooks per stage alphabetically", () => {
        expect.assertions(3);

        writeHookScript(temporary.root, "pre-commit", "#!/usr/bin/env sh\n# lint-staged: run linters\npnpm run lint\n");
        writeHookScript(temporary.root, "commit-msg", "#!/usr/bin/env sh\n# commitlint: validate message\npnpm exec commitlint --edit\n");

        const result = listHooks(temporary.root, ".vis-hooks");
        const formatted = formatListResult(result);

        expect(result.stages.map((s) => s.stage)).toStrictEqual(["commit-msg", "pre-commit"]);
        expect(formatted.some((line) => line.includes("commit-msg"))).toBe(true);
        expect(formatted.some((line) => line.includes("pre-commit"))).toBe(true);
    });
});

// ─── validateHooks ──────────────────────────────────────────────────

describe(validateHooks, () => {
    let temporary: { cleanup: () => void; root: string };

    beforeEach(() => {
        temporary = createTemporaryGitRepo();
    });

    afterEach(() => {
        temporary.cleanup();
    });

    it.skipIf(process.platform === "win32")("flags missing dispatcher + hooksPath as errors", () => {
        expect.assertions(2);

        const result = validateHooks(temporary.root, ".vis-hooks");

        expect(result.ok).toBe(false);
        expect(result.issues.some((i) => i.message.includes("Dispatcher directory"))).toBe(true);
    });

    it.skipIf(process.platform === "win32")("accepts a clean install", () => {
        expect.assertions(2);

        writeHookScript(temporary.root, "pre-commit", "#!/usr/bin/env sh\necho hi\n");
        spawnSync("git", ["config", "core.hooksPath", ".vis-hooks/_"], { cwd: temporary.root });

        const result = validateHooks(temporary.root, ".vis-hooks");

        expect(result.ok).toBe(true);
        expect(result.issues.every((i) => i.kind !== "error")).toBe(true);
    });

    it.skipIf(process.platform === "win32")("detects shell syntax errors in a stage script", () => {
        expect.assertions(2);

        writeHookScript(temporary.root, "pre-commit", "#!/usr/bin/env sh\nif then fi\n");
        spawnSync("git", ["config", "core.hooksPath", ".vis-hooks/_"], { cwd: temporary.root });

        const result = validateHooks(temporary.root, ".vis-hooks");

        expect(result.ok).toBe(false);
        expect(result.issues.some((i) => i.kind === "error" && i.message.includes("syntax"))).toBe(true);
    });

    it.skipIf(process.platform === "win32")("flags a missing prek-runner.mjs when a script references it", () => {
        expect.assertions(2);

        writeHookScript(temporary.root, "pre-commit", "#!/usr/bin/env sh\nnode \"$(dirname \"$0\")/.builtins/prek-runner.mjs\" --builtin trailing-whitespace\n");
        spawnSync("git", ["config", "core.hooksPath", ".vis-hooks/_"], { cwd: temporary.root });

        const result = validateHooks(temporary.root, ".vis-hooks");

        expect(result.ok).toBe(false);
        expect(result.issues.some((i) => i.message.includes("prek-runner.mjs"))).toBe(true);
    });
});

// ─── runHookStage ───────────────────────────────────────────────────

describe(runHookStage, () => {
    let temporary: { cleanup: () => void; root: string };

    beforeEach(() => {
        temporary = createTemporaryGitRepo();
    });

    afterEach(() => {
        temporary.cleanup();
    });

    it.skipIf(process.platform === "win32")("rejects --from-ref without --to-ref", () => {
        expect.assertions(1);

        writeHookScript(temporary.root, "pre-commit", "#!/usr/bin/env sh\nexit 0\n");

        expect(() =>
            runHookStage(temporary.root, ".vis-hooks", { fromRef: "HEAD~1", stage: "pre-commit" }, noopLogger),
        ).toThrow(/--from-ref requires --to-ref/);
    });

    it.skipIf(process.platform === "win32")("translates --last-commit into HEAD~1..HEAD env vars", () => {
        expect.assertions(1);

        writeHookScript(
            temporary.root,
            "pre-commit",
            "#!/usr/bin/env sh\nif [ \"$VIS_HOOK_FROM_REF\" = \"HEAD~1\" ] && [ \"$VIS_HOOK_TO_REF\" = \"HEAD\" ]; then exit 7; else exit 0; fi\n",
        );

        const code = runHookStage(temporary.root, ".vis-hooks", { lastCommit: true, stage: "pre-commit" }, noopLogger);

        expect(code).toBe(7);
    });

    it.skipIf(process.platform === "win32")("rejects --last-commit combined with explicit refs", () => {
        expect.assertions(1);

        writeHookScript(temporary.root, "pre-commit", "#!/usr/bin/env sh\nexit 0\n");

        expect(() =>
            runHookStage(temporary.root, ".vis-hooks", { fromRef: "main", lastCommit: true, stage: "pre-commit", toRef: "HEAD" }, noopLogger),
        ).toThrow(/--last-commit cannot be combined/);
    });

    it.skipIf(process.platform === "win32")("runs the named stage script and returns its exit code", () => {
        expect.assertions(1);

        writeHookScript(temporary.root, "pre-commit", "#!/usr/bin/env sh\nexit 0\n");

        const code = runHookStage(temporary.root, ".vis-hooks", { stage: "pre-commit" }, noopLogger);

        expect(code).toBe(0);
    });

    it.skipIf(process.platform === "win32")("errors when the script is missing", () => {
        expect.assertions(1);

        expect(() => runHookStage(temporary.root, ".vis-hooks", { stage: "pre-commit" }, noopLogger)).toThrow(/No script found/);
    });

    it.skipIf(process.platform === "win32")("forwards --all-files to the child via VIS_HOOK_ALL_FILES", () => {
        expect.assertions(1);

        writeHookScript(
            temporary.root,
            "pre-commit",
            "#!/usr/bin/env sh\nif [ \"$VIS_HOOK_ALL_FILES\" = \"1\" ]; then exit 42; else exit 0; fi\n",
        );

        // We need the hook script to actually run directly; runHookStage invokes it via `sh -e`
        const code = runHookStage(temporary.root, ".vis-hooks", { allFiles: true, stage: "pre-commit" }, noopLogger);

        expect(code).toBe(42);
    });
});

// ─── runner integration: --all-files + --builtin ─────────────────────

describe("prek-runner --all-files", () => {
    let temporary: { cleanup: () => void; root: string };

    beforeEach(() => {
        temporary = createTemporaryGitRepo();
    });

    afterEach(() => {
        temporary.cleanup();
    });

    it.skipIf(process.platform === "win32")("runs the builtin against all tracked files, not only staged", async () => {
        expect.assertions(3);

        // Write a runner to disk and call it directly, mirroring what a migrated hook does.
        const { PREK_RUNNER_FILENAME, PREK_RUNNER_SOURCE } = await import("../src/commands/hook/prek-builtins");

        mkdirSync(join(temporary.root, ".vis-hooks", ".builtins"), { recursive: true });
        writeFileSync(join(temporary.root, ".vis-hooks", ".builtins", PREK_RUNNER_FILENAME), PREK_RUNNER_SOURCE, { mode: 0o755 });

        // Commit one file so it's tracked but not staged when we run the hook.
        // A .txt file so the trailing-whitespace builtin doesn't apply the
        // markdown hard-break preservation rule.
        writeFileSync(join(temporary.root, "tracked.txt"), "some text   \n");
        spawnSync("git", ["add", "tracked.txt"], { cwd: temporary.root });
        const commit = spawnSync("git", ["commit", "-m", "init"], { cwd: temporary.root, encoding: "utf8" });

        expect(commit.status, `git commit failed: ${commit.stderr}`).toBe(0);

        const runnerPath = join(temporary.root, ".vis-hooks", ".builtins", PREK_RUNNER_FILENAME);
        const defaultRun = spawnSync("node", [runnerPath, "--builtin", "trailing-whitespace"], { cwd: temporary.root, encoding: "utf8" });

        expect(defaultRun.status).toBe(0); // nothing staged → no-op

        const allFilesRun = spawnSync("node", [runnerPath, "--all-files", "--builtin", "trailing-whitespace"], { cwd: temporary.root, encoding: "utf8" });

        expect(allFilesRun.status).toBe(1); // trailing-whitespace fixed the file
    });
});
