/**
 * Tests for `detectLockfileDrift` — the one-time pre-flight warning
 * surfaced before aube rewrites a non-aube lockfile.
 *
 * Uses real tmp dirs (not mocks) because `detectPm` walks the
 * filesystem looking for lockfile markers. Each test materializes
 * the minimal fixture (a single lockfile + a `package.json` so
 * `detectPm` walks correctly) and asserts the resolver's verdict.
 */

import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { afterEach, beforeEach, describe, expect, it } from "vitest";

import { detectLockfileDrift } from "../src/pm-runner";

let workspace: string;

beforeEach(() => {
    workspace = mkdtempSync(join(tmpdir(), "vis-aube-drift-"));
    writeFileSync(join(workspace, "package.json"), JSON.stringify({ name: "fixture", version: "0.0.0" }));
});

afterEach(() => {
    rmSync(workspace, { force: true, recursive: true });
});

describe(detectLockfileDrift, () => {
    it("returns undefined when the resolved installer is not aube (the warning only applies to aube workspaces)", () => {
        expect.assertions(1);

        writeFileSync(join(workspace, "pnpm-lock.yaml"), "lockfileVersion: '9.0'\n");

        const drift = detectLockfileDrift(workspace, { name: "pnpm", version: "10.0.0" });

        expect(drift).toBeUndefined();
    });

    it("returns undefined for greenfield workspaces — no lockfile, no drift to warn about", () => {
        expect.assertions(1);

        // Only package.json present, no lockfile.
        const drift = detectLockfileDrift(workspace, { name: "aube", version: "latest" });

        expect(drift).toBeUndefined();
    });

    it("warns when aube is the resolved installer and a pnpm lockfile is present", () => {
        expect.assertions(2);

        writeFileSync(join(workspace, "pnpm-lock.yaml"), "lockfileVersion: '9.0'\n");

        const drift = detectLockfileDrift(workspace, { name: "aube", version: "latest" });

        expect(drift).toBeDefined();
        expect(drift).toContain("pnpm lockfile");
    });

    it("warns when aube is the resolved installer and a yarn lockfile is present", () => {
        expect.assertions(1);

        writeFileSync(join(workspace, "yarn.lock"), "# THIS IS AN AUTOGENERATED FILE\n");

        const drift = detectLockfileDrift(workspace, { name: "aube", version: "latest" });

        expect(drift).toContain("yarn lockfile");
    });

    it("warns when aube is the resolved installer and an npm lockfile is present", () => {
        expect.assertions(1);

        writeFileSync(join(workspace, "package-lock.json"), "{}");

        const drift = detectLockfileDrift(workspace, { name: "aube", version: "latest" });

        expect(drift).toContain("npm lockfile");
    });

    it("warns when aube is the resolved installer and a bun lockfile is present", () => {
        expect.assertions(1);

        writeFileSync(join(workspace, "bun.lock"), "{}");

        const drift = detectLockfileDrift(workspace, { name: "aube", version: "latest" });

        expect(drift).toContain("bun lockfile");
    });

    it("includes both the `--no-aube` escape and the install.backend pinning suggestion in the warning", () => {
        expect.assertions(2);

        writeFileSync(join(workspace, "pnpm-lock.yaml"), "lockfileVersion: '9.0'\n");

        const drift = detectLockfileDrift(workspace, { name: "aube", version: "latest" });

        expect(drift).toContain("--no-aube");
        expect(drift).toContain("install.backend");
    });
});
