/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as ImprintRouteImport } from './routes/imprint'
import { Route as CodeOfConductRouteImport } from './routes/code-of-conduct'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PackagesIndexRouteImport } from './routes/packages/index'
import { Route as RNameRouteImport } from './routes/r/$name'
import { Route as PackagesSlugRouteImport } from './routes/packages/$slug'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiOgRouteImport } from './routes/api/og'
import { Route as LlmsDotmdxDocsSplatRouteImport } from './routes/llms[.]mdx.docs.$'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprintRoute = ImprintRouteImport.update({
  id: '/imprint',
  path: '/imprint',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeOfConductRoute = CodeOfConductRouteImport.update({
  id: '/code-of-conduct',
  path: '/code-of-conduct',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesIndexRoute = PackagesIndexRouteImport.update({
  id: '/packages/',
  path: '/packages/',
  getParentRoute: () => rootRouteImport,
} as any)
const RNameRoute = RNameRouteImport.update({
  id: '/r/$name',
  path: '/r/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesSlugRoute = PackagesSlugRouteImport.update({
  id: '/packages/$slug',
  path: '/packages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgRoute = ApiOgRouteImport.update({
  id: '/api/og',
  path: '/api/og',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDotmdxDocsSplatRoute = LlmsDotmdxDocsSplatRouteImport.update({
  id: '/llms.mdx/docs/$',
  path: '/llms.mdx/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/changelog': typeof ChangelogRoute
  '/code-of-conduct': typeof CodeOfConductRoute
  '/imprint': typeof ImprintRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/og': typeof ApiOgRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/packages/$slug': typeof PackagesSlugRoute
  '/r/$name': typeof RNameRoute
  '/packages/': typeof PackagesIndexRoute
  '/llms.mdx/docs/$': typeof LlmsDotmdxDocsSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/changelog': typeof ChangelogRoute
  '/code-of-conduct': typeof CodeOfConductRoute
  '/imprint': typeof ImprintRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/og': typeof ApiOgRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/packages/$slug': typeof PackagesSlugRoute
  '/r/$name': typeof RNameRoute
  '/packages': typeof PackagesIndexRoute
  '/llms.mdx/docs/$': typeof LlmsDotmdxDocsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/changelog': typeof ChangelogRoute
  '/code-of-conduct': typeof CodeOfConductRoute
  '/imprint': typeof ImprintRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/og': typeof ApiOgRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/packages/$slug': typeof PackagesSlugRoute
  '/r/$name': typeof RNameRoute
  '/packages/': typeof PackagesIndexRoute
  '/llms.mdx/docs/$': typeof LlmsDotmdxDocsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brand'
    | '/changelog'
    | '/code-of-conduct'
    | '/imprint'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/privacy'
    | '/sitemap.xml'
    | '/api/og'
    | '/api/search'
    | '/docs/$'
    | '/packages/$slug'
    | '/r/$name'
    | '/packages/'
    | '/llms.mdx/docs/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brand'
    | '/changelog'
    | '/code-of-conduct'
    | '/imprint'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/privacy'
    | '/sitemap.xml'
    | '/api/og'
    | '/api/search'
    | '/docs/$'
    | '/packages/$slug'
    | '/r/$name'
    | '/packages'
    | '/llms.mdx/docs/$'
  id:
    | '__root__'
    | '/'
    | '/brand'
    | '/changelog'
    | '/code-of-conduct'
    | '/imprint'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/privacy'
    | '/sitemap.xml'
    | '/api/og'
    | '/api/search'
    | '/docs/$'
    | '/packages/$slug'
    | '/r/$name'
    | '/packages/'
    | '/llms.mdx/docs/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandRoute: typeof BrandRoute
  ChangelogRoute: typeof ChangelogRoute
  CodeOfConductRoute: typeof CodeOfConductRoute
  ImprintRoute: typeof ImprintRoute
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiOgRoute: typeof ApiOgRoute
  ApiSearchRoute: typeof ApiSearchRoute
  DocsSplatRoute: typeof DocsSplatRoute
  PackagesSlugRoute: typeof PackagesSlugRoute
  RNameRoute: typeof RNameRoute
  PackagesIndexRoute: typeof PackagesIndexRoute
  LlmsDotmdxDocsSplatRoute: typeof LlmsDotmdxDocsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprint': {
      id: '/imprint'
      path: '/imprint'
      fullPath: '/imprint'
      preLoaderRoute: typeof ImprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code-of-conduct': {
      id: '/code-of-conduct'
      path: '/code-of-conduct'
      fullPath: '/code-of-conduct'
      preLoaderRoute: typeof CodeOfConductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/': {
      id: '/packages/'
      path: '/packages'
      fullPath: '/packages/'
      preLoaderRoute: typeof PackagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$name': {
      id: '/r/$name'
      path: '/r/$name'
      fullPath: '/r/$name'
      preLoaderRoute: typeof RNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/$slug': {
      id: '/packages/$slug'
      path: '/packages/$slug'
      fullPath: '/packages/$slug'
      preLoaderRoute: typeof PackagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og': {
      id: '/api/og'
      path: '/api/og'
      fullPath: '/api/og'
      preLoaderRoute: typeof ApiOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.mdx/docs/$': {
      id: '/llms.mdx/docs/$'
      path: '/llms.mdx/docs/$'
      fullPath: '/llms.mdx/docs/$'
      preLoaderRoute: typeof LlmsDotmdxDocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandRoute: BrandRoute,
  ChangelogRoute: ChangelogRoute,
  CodeOfConductRoute: CodeOfConductRoute,
  ImprintRoute: ImprintRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiOgRoute: ApiOgRoute,
  ApiSearchRoute: ApiSearchRoute,
  DocsSplatRoute: DocsSplatRoute,
  PackagesSlugRoute: PackagesSlugRoute,
  RNameRoute: RNameRoute,
  PackagesIndexRoute: PackagesIndexRoute,
  LlmsDotmdxDocsSplatRoute: LlmsDotmdxDocsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
