import { createConfig } from "@anolilab/eslint-config";

/** @type {import("@anolilab/eslint-config").PromiseFlatConfigComposer} */
export default createConfig(
    {
        ignores: [
            "dist",
            "node_modules",
            "coverage",
            "__fixtures__",
            "__docs__",
            "examples",
            "vitest.config.ts",
            "packem.config.ts",
            ".secretlintrc.cjs",
            "prettier.config.js",
            "package.json",
            "README.md",
            "prettier.config.js",
            "__bench__/fixtures",
            "__bench__/scripts",
        ],
        typescript: {
            tsconfigPath: "./tsconfig.eslint.json",
        },
    },
    {
        files: ["**/*.test.ts"],
        rules: {
            "@typescript-eslint/no-explicit-any": "off",
            "no-secrets/no-secrets": "off",
            "sonarjs/no-nested-functions": "off",
            "unicorn/no-null": "off",
        },
    },
    {
        files: ["__bench__/**/*.ts"],
        rules: {
            "@typescript-eslint/naming-convention": "off",
            "sonarjs/no-unused-vars": "off",
            "unused-imports/no-unused-vars": "off",
        },
    },
    {
        files: ["src/**/*.ts"],
        rules: {
            "@stylistic/max-statements-per-line": "off",
            "@stylistic/no-extra-parens": "off",
            "@typescript-eslint/await-thenable": "off",
            "@typescript-eslint/no-confusing-void-expression": "off",
            "@typescript-eslint/no-require-imports": "off",
            "@typescript-eslint/no-unnecessary-condition": "off",
            "@typescript-eslint/no-unnecessary-type-parameters": "off",
            "@typescript-eslint/no-unsafe-assignment": "off",
            "@typescript-eslint/no-unsafe-call": "off",
            "@typescript-eslint/no-unsafe-member-access": "off",
            "@typescript-eslint/no-unsafe-return": "off",
            "@typescript-eslint/prefer-nullish-coalescing": "off",
            "@typescript-eslint/require-await": "off",
            "@typescript-eslint/restrict-plus-operands": "off",
            "@typescript-eslint/restrict-template-expressions": "off",
            "@typescript-eslint/unbound-method": "off",
            "e18e/prefer-static-regex": "off",
            "global-require": "off",
            "jsdoc/no-undefined-types": "off",
            "no-confusing-arrow": "off",
            "no-for-of-array/no-for-of-array": "off",
            "preserve-caught-error": "off",
            "sonarjs/deprecation": "off",
            "sonarjs/different-types-comparison": "off",
            "sonarjs/function-return-type": "off",
            "sonarjs/no-commented-code": "off",
            "sonarjs/no-nested-conditional": "off",
            "sonarjs/no-redundant-optional": "off",
            "sonarjs/unused-named-groups": "off",
            "unicorn/no-new-array": "off",
            "unicorn/no-null": "off",
        },
    },
    {
        files: ["__tests__/**/*.ts"],
        rules: {
            "@stylistic/max-statements-per-line": "off",
            "@stylistic/no-extra-parens": "off",
            "@typescript-eslint/await-thenable": "off",
            "@typescript-eslint/no-confusing-void-expression": "off",
            "@typescript-eslint/no-require-imports": "off",
            "@typescript-eslint/no-unnecessary-condition": "off",
            "@typescript-eslint/no-unsafe-argument": "off",
            "@typescript-eslint/no-unsafe-assignment": "off",
            "@typescript-eslint/no-unsafe-call": "off",
            "@typescript-eslint/no-unsafe-member-access": "off",
            "@typescript-eslint/no-unsafe-return": "off",
            "@typescript-eslint/require-await": "off",
            "@typescript-eslint/restrict-template-expressions": "off",
            "@typescript-eslint/unbound-method": "off",
            "e18e/ban-dependencies": "off",
            "e18e/prefer-static-regex": "off",
            "global-require": "off",
            "no-for-of-array/no-for-of-array": "off",
            "sonarjs/no-commented-code": "off",
            "sonarjs/no-nested-conditional": "off",
            "unicorn/no-new-array": "off",
        },
    },
    {
        ignores: ["__bench__/walk.bench.ts", "__bench__/find-up.bench.ts", "__bench__/file-ops.bench.ts"],
    },
);
