// Static overlap analysis for the combined ruleset. Groups rules by an inferred
// provider slug so we can see at a glance which vendors are covered by both
// upstreams (redundant firings at scan time), and which are exclusive to one.
//
// Pure and side-effect-free — the build script passes in the parsed combined
// config and writes the returned markdown to `data/overlap.md`.

// Provider slug conventions in the two upstream sources:
//   * gitleaks   — `<provider>-<subtype>`  (e.g. "aws-access-token")
//   * kingfisher — `kingfisher.<provider>.<n>` (e.g. "kingfisher.aws.1")
//
// We canonicalise both to the bare provider token, lowercase, with a handful
// of equivalences for the obvious spelling drift between the two projects.
const PROVIDER_ALIASES = new Map([
    ["adafruitio", "adafruit"],
    ["alibabacloud", "alibaba"],
    ["amazonmws", "aws"],
    ["amazonoauth", "aws"],
    ["awsaccesskey", "aws"],
    ["awssessionkey", "aws"],
    ["ciscomeraki", "cisco"],
    ["defined", "definednetworking"],
    ["definednet", "definednetworking"],
    ["dockerhub", "docker"],
    ["drone", "droneci"],
    ["gcpapikey", "gcp"],
    ["gcpoauth", "gcp"],
    ["gcpserviceaccount", "gcp"],
    ["githubapp", "github"],
    ["gitlabci", "gitlab"],
    ["gitlabpat", "gitlab"],
    ["gitlabptt", "gitlab"],
    ["googleapi", "google"],
    ["googleoauth", "google"],
    ["microsoft", "msteams"],
    ["microsoftteamswebhook", "msteams"],
    ["new", "newrelic"],
    ["npmaccesstoken", "npm"],
    ["octopus", "octopusdeploy"],
    ["postmanapi", "postman"],
    ["sendgridapi", "sendgrid"],
    ["slackapp", "slack"],
    ["slackbot", "slack"],
    ["slackuser", "slack"],
    ["slackwebhook", "slack"],
    ["sonar", "sonarqube"],
    ["sonarcloud", "sonarqube"],
]);

const normalizeProvider = (slug) => {
    const lower = slug.toLowerCase();

    return PROVIDER_ALIASES.get(lower) ?? lower;
};

export const inferProvider = (ruleId) => {
    if (typeof ruleId !== "string") {
        return "unknown";
    }

    if (ruleId.startsWith("kingfisher.")) {
        const parts = ruleId.split(".");

        return normalizeProvider(parts[1] ?? "unknown");
    }

    const dash = ruleId.indexOf("-");

    return normalizeProvider(dash === -1 ? ruleId : ruleId.slice(0, dash));
};

const formatRow = (cells) => `| ${cells.join(" | ")} |`;

const mdEscape = (text) => text.replaceAll("|", String.raw`\|`);

const byProviderName = (a, b) => a.provider.localeCompare(b.provider);

const byRuleId = (a, b) => a.localeCompare(b);

const listRuleIds = (rules) =>
    rules
        .map((r) => `\`${r.id}\``)
        .toSorted(byRuleId)
        .join(", ");

const bucketForSource = (source) => {
    if (source === "gitleaks") {
        return "gitleaks";
    }

    if (source === "kingfisher") {
        return "kingfisher";
    }

    return "other";
};

/**
 * Analyze a combined ruleset config and return a markdown overlap report.
 * Deterministic output — same input produces byte-identical report.
 * @param {{ rules?: Array<{ id?: string; source?: string }> }} combined Combined config, as emitted by `build-rules.mjs`.
 * @returns {string} Markdown report text.
 */
export const analyzeOverlap = (combined) => {
    const rules = Array.isArray(combined?.rules) ? combined.rules : [];
    const byProvider = new Map();

    for (const rule of rules) {
        if (typeof rule?.id !== "string") {
            continue;
        }

        const provider = inferProvider(rule.id);
        const entry = byProvider.get(provider) ?? { gitleaks: [], kingfisher: [], other: [] };
        const bucket = bucketForSource(rule.source);

        entry[bucket].push(rule);
        byProvider.set(provider, entry);
    }

    const providers = [...byProvider.entries()].map(([provider, entry]) => {
        return {
            gitleaks: entry.gitleaks,
            kingfisher: entry.kingfisher,
            other: entry.other,
            provider,
        };
    });

    const both = providers.filter((p) => p.gitleaks.length > 0 && p.kingfisher.length > 0).toSorted(byProviderName);
    const onlyGitleaks = providers.filter((p) => p.gitleaks.length > 0 && p.kingfisher.length === 0).toSorted(byProviderName);
    const onlyKingfisher = providers.filter((p) => p.gitleaks.length === 0 && p.kingfisher.length > 0).toSorted(byProviderName);

    const totalRules = rules.length;
    const gitleaksRules = rules.filter((r) => r.source === "gitleaks").length;
    const kingfisherRules = rules.filter((r) => r.source === "kingfisher").length;
    const overlapRules = both.reduce((sum, p) => sum + p.gitleaks.length + p.kingfisher.length, 0);

    const lines = [
        "# Rule overlap report",
        "",
        "Generated by `scripts/analyze-overlap.mjs` during `build:rules`. Groups every rule by an",
        "inferred provider slug (first token of the rule ID, with a handful of spelling-drift aliases).",
        "",
        "This is a **structural** overlap — rules grouped under the same provider may still target",
        "different credential shapes (e.g. `aws-access-token` vs an AWS MWS auth token). At scan time,",
        "the native layer's span-based dedup collapses findings that land on the exact same bytes;",
        "overlap that doesn't collide on a span is genuinely complementary coverage.",
        "",
        "## Summary",
        "",
        `- **Total rules:** ${totalRules} (gitleaks: ${gitleaksRules}, kingfisher: ${kingfisherRules})`,
        `- **Providers covered by both sources:** ${both.length} (involving ${overlapRules} rules)`,
        `- **Gitleaks-only providers:** ${onlyGitleaks.length}`,
        `- **Kingfisher-only providers:** ${onlyKingfisher.length}`,
        "",
        "## Providers covered by both sources",
        "",
        formatRow(["Provider", "Gitleaks rules", "Kingfisher rules"]),
        formatRow(["---", "---", "---"]),
    ];

    for (const p of both) {
        lines.push(formatRow([mdEscape(p.provider), String(p.gitleaks.length), String(p.kingfisher.length)]));
    }

    lines.push("", "### Overlapping rule IDs", "");

    for (const p of both) {
        lines.push(`- **${p.provider}** — gitleaks: ${listRuleIds(p.gitleaks)}; kingfisher: ${listRuleIds(p.kingfisher)}`);
    }

    lines.push("", "## Gitleaks-only providers", "");

    for (const p of onlyGitleaks) {
        lines.push(`- **${p.provider}** (${p.gitleaks.length}) — ${listRuleIds(p.gitleaks)}`);
    }

    lines.push("", "## Kingfisher-only providers", "");

    for (const p of onlyKingfisher) {
        lines.push(`- **${p.provider}** (${p.kingfisher.length}) — ${listRuleIds(p.kingfisher)}`);
    }

    lines.push("");

    return lines.join("\n");
};
