/**
 * Arabic banned words
 *
 * Sources:
 * - Curated list
 * - https://github.com/coffee-and-fun/google-profanity-words
 * - https://github.com/viddexa/safetext
 */
const words: ReadonlyArray<string> = [
    "kus",
    "kuss",
    "kos ommak",
    "ibn el sharmouta",
    "ibn el sharmuta",
    "sharmouta",
    "sharmuta",
    "sharmota",
    "manyak",
    "manyaka",
    "khawal",
    "khawala",
    "zanji",
    "abeed",
    "abd",
    "yahudi",
    "kuffar",
    "luti",
    "shaz",
    "kalb",
    "ibn el kalb",
    "khara",
    "ayreh feek",
    "telhas tizi",
    "kol khara",
    "wiskha",
    "gahba",
    "ightisab",
    "لعنة",
    "اللعنة",
    "خرا",
    "خراء",
    "قحبة",
    "شرموطة",
    "زب",
    "كس",
    "ابن زنا",
    "ابن حرام",
    "كلب",
    "يا كلب",
    "حمار",
    "يا حمار",
    "يا ابن الكلب",
    "يلعن أبوك",
    "يلعن شكلك",
    "تفو",
    "تفو عليك",
    "قذر",
    "قرف",
    "تبا",
    "انقلع",
    "اخرس",
    "2adeeb",
    "3abeet",
    "3agala",
    "3ahera",
    "3akroot",
    "3arbagy",
    "3ars",
    "3as",
    "3asba",
    "3ass",
    "3attay",
    "3ayba",
    "3eer",
    "3el2",
    "3ezgetek",
    "5anith",
    "5anza",
    "5anzeer",
    "5anzer",
    "5ara",
    "5awal",
    "5oneeth",
    "5oneth",
    "5orm",
    "5ra",
    "7akeer",
    "7alama",
    "7amka",
    "7aqeer",
    "7aywan",
    "7omar",
    "9a7ba",
    "a nagrik",
    "a seleta bok",
    "a'airy eb gathek",
    "a'akrout",
    "a'ars",
    "a'ers",
    "a7a",
    "aad aleh",
    "abn al kalaaab",
    "abn alkahba",
    "abn balla't aleora",
    "abn elghbeh",
    "abous ksa lmemee",
    "abu ayoura",
    "abul eyora",
    "ad l mehaleh",
    "adabsez",
    "adoosik",
    "adreb pipa",
    "aere feek",
    "ah. kesi",
    "ahbal",
    "ahot rijly btizak",
    "air",
    "air ab wjhak",
    "air b emmak el mfanda'a",
    "airi",
    "airi be tizak",
    "airi bebzezat ekhtak",
    "airi bshafrat kes emmak",
    "airi feek",
    "airy",
    "airy bteezk",
    "airy fi rasak",
    "airy fic",
    "airy qalbak",
    "aji nahwik",
    "akbar zamel ala wajh alard",
    "akho el sharmootah",
    "akhou el sharmoota",
    "akhu al manukeh",
    "akhu el sharmuta",
    "akhu shlukeh",
    "akol khara",
    "akroot",
    "ala'abi",
    "alaa zibay",
    "alhs khuswani",
    "alif er eb nos tezak",
    "allah dialk kayrde3 zebbi",
    "allah i naal dine mok",
    "allah mamhuun",
    "allahi yekhrib beitak",
    "althady",
    "an nhwik",
    "ana howa rab dialk",
    "ana neek rasak",
    "ane chek",
    "anech akhtk",
    "anech amk",
    "aneek ummak",
    "anik ardak",
    "anta jameel",
    "anta kalbee",
    "ars",
    "arsa",
    "arthali zebbi ya kahba",
    "asai ti'e",
    "asba",
    "asba ala sormek",
    "assam alaykom",
    "atsheer mukhik",
    "attay",
    "attaï",
    "awlad il kara",
    "ayaar",
    "ayel motasawel",
    "ayeree fee wij imaak",
    "ayre",
    "ayre b tezik",
    "ayre belli bazzarak",
    "ayre brabbak",
    "ayri belli tara ak",
    "ba neekak",
    "ba8l",
    "baa'boos",
    "baaboos",
    "baaroor",
    "bad",
    "bade naykak l fejle",
    "bade neek ra'ebtak",
    "badeen",
    "badi aneek kosik",
    "baghl",
    "bah-shi rejlee fee teez imak",
    "bah-shi rejlee fee teezak",
    "bakraa",
    "bakri",
    "bala'a il a'air",
    "bala'aa al eyre",
    "balaab ala imak",
    "balah el err",
    "balboul",
    "balla' el air",
    "ballaa' el air",
    "bandook",
    "banik immak",
    "banjote",
    "bara naik",
    "baranek",
    "barboog",
    "barbook",
    "barbooqa",
    "barra nayiek",
    "bashokh alaa imak",
    "bashokh aleek",
    "bassas",
    "batrona",
    "batroun",
    "baydati fik",
    "bayra",
    "bazr",
    "bde amroj fe 3enak",
    "bedadti yeltmo wshik",
    "bedak tentak",
    "bedan",
    "bedat",
    "bedi fawit eyri bi tizik",
    "bedi hit kombrisa be tizak",
    "bedi masmes bazbozek",
    "bedi neck tizzak",
    "bedi neek eli khalafak",
    "bedi nik bzez emak",
    "bedi nik kesik",
    "bedi nik tiz emak l mamhoneh",
    "bedi nikak",
    "beef strokie",
    "beit sharamit",
    "berkaka",
    "bertouche",
    "besht",
    "beskeletta",
    "betetrakab",
    "beyetnak",
    "beyetrakab",
    "bez",
    "bezaz",
    "bghitini nahwik",
    "bidi a neek- neekik- neekak",
    "bidi zib- bidi aerr",
    "bin almukhanifa",
    "bin gahba",
    "bin'nt himaar",
    "bizaz",
    "blaa el aeer",
    "bmasesk",
    "bniik boksh tizzak",
    "boofta",
    "bou aswad",
    "bous tize",
    "btetnak",
    "bzazlha",
    "chalb",
    "charmouta",
    "cheb",
    "chlb",
    "chub la anichick",
    "coos okt al laglesh",
    "cos",
    "cos omak maafina",
    "coso5tak",
    "cosomak",
    "da ana hanekak",
    "da' ara",
    "da-goom-be",
    "da3ara",
    "da3era",
    "dahri a'lik",
    "dai'sh",
    "dakcdook",
    "dakcdookca",
    "dakhlah killah",
    "darat",
    "dayer ki zebbi",
    "dayoos",
    "dayooth",
    "dayoth",
    "dayouth",
    "deen abook",
    "deen omak",
    "deiouse",
    "dewangee",
    "dhasho",
    "dhasho b teezak",
    "dilla",
    "din dialkom dial zwaml",
    "doom-boog il err",
    "doonie",
    "doul fodjfoh",
    "drat",
    "duroot",
    "dyoos",
    "e8tesab",
    "eacha",
    "ebn al-gahbe",
    "ebn al-manyooke",
    "ebn al-sharmoota",
    "ebn alblaa3aa",
    "ebn el sharmoota",
    "ebn el-mara",
    "eer fe omok",
    "eghtesab",
    "ekhtak bade neeka",
    "ekil zeg",
    "el-sheitan alaykom",
    "elhas kussi",
    "emak dlale",
    "emshi nik ommek",
    "engata'lek nountek",
    "ent khanzeer",
    "enta khanzeer",
    "enta khawal",
    "entak seflo",
    "eri b rasak",
    "eri be ketabak",
    "ethwel",
    "eyre b wejjak chou meref",
    "eyre fik",
    "ezgetek",
    "fakahtk",
    "fakahtoki",
    "faq'haa",
    "far5",
    "farasa",
    "farg",
    "faseel",
    "fash5",
    "fash5a",
    "fashkh",
    "firshaeh",
    "frkh",
    "fuck me baby",
    "gah ba",
    "gahaba",
    "gahba d yemak",
    "gahbeh",
    "gahhba",
    "gamoosa",
    "gamosa",
    "garage al aeir",
    "garager",
    "gath mal hmar",
    "gawad",
    "gawwad",
    "gema3",
    "gewad",
    "ghaben",
    "ghabi",
    "ghati il face oo doos il race",
    "ghouzo",
    "gird",
    "hadbahak",
    "hafyaan",
    "hajia",
    "hakeer",
    "haker",
    "hamama",
    "haneikak",
    "hanekak",
    "haqeer",
    "hatchoun yemak",
    "hawi",
    "haygan",
    "haywan",
    "hbeela",
    "hbiba",
    "hbila",
    "hey berboog",
    "himar",
    "hittou fi teesak",
    "hmar",
    "hmar kelb tfou",
    "hoi mouk",
    "homar",
    "horia",
    "humar",
    "hway",
    "hway zwamel",
    "hwi muk",
    "hwiha",
    "hwini",
    "hynityou",
    "i love you soo much bitch",
    "iben el mentakeh",
    "ibin al sayer naal",
    "ibin al tarka",
    "ibin al yamani",
    "ibin himaar",
    "ibin shlukeh",
    "ibn al 3ahra",
    "ibn al aahra",
    "ibn al ghahba",
    "ibn al khara",
    "ibn el ahba",
    "ibn el caleb",
    "ibn el-kalb",
    "ibn el-sharmoota",
    "ibn gahba",
    "ibn haram",
    "ibn himar",
    "ibn il chalb",
    "ibn il sharmoota",
    "ibn il sharmota",
    "ibn il tinayich",
    "ibnl kondara",
    "ibyn ballait el ere",
    "ihmar",
    "ila an abu taaris ohtak",
    "ila an sharafak",
    "ilhas teeze",
    "imak ibtintak",
    "imak wahdi btoklo",
    "imlowatt",
    "inta shaz",
    "ja3b",
    "jamal",
    "jamalick cil jahash",
    "jarrar",
    "jeefah",
    "jru",
    "ka7ba",
    "kaboul",
    "kahba di omo",
    "kahwad",
    "kaifa haluka",
    "kakhba",
    "kalb ibnal kalb",
    "kalet",
    "kaneeth",
    "kanker zemmer",
    "kanmseh lkhra bil9or2an lkarih",
    "karakhaneh",
    "karrak",
    "kawad",
    "kawad darak",
    "kawed",
    "kawwad",
    "kawwazi",
    "kbirt lkhab",
    "kel khrak omak",
    "kelb a swag",
    "kerfa",
    "kes ekhtak",
    "kes emmak",
    "kes en neck eighty",
    "kes okhtik bi ayre",
    "kes omok",
    "kess emak",
    "kess emmak",
    "kess ihktak",
    "kess oumok",
    "kh-osh fi teezi",
    "khajaf",
    "khalil aire wa kloo",
    "khaneeth",
    "khaneeth el oood",
    "khanez",
    "khanith",
    "khanneeth",
    "khanza",
    "khanzeer",
    "khanzer",
    "khara aleik",
    "khara b ibleesek",
    "kharay alek",
    "kharaye feek",
    "khareg",
    "khawal or shaz",
    "khawwar karrak",
    "khchi sebaak f tremtek",
    "khood",
    "khorong",
    "khosh fi teizi",
    "khrnteh",
    "kis ardhich",
    "kis em eli nafadak",
    "kis em ick",
    "kis khaltak",
    "kis naychik",
    "kisik d'arda",
    "kiss",
    "kiss ekhtak",
    "kiss wayhek",
    "kod ras aerri",
    "kol airi",
    "kol ayre",
    "kol eyre",
    "kol zabri",
    "kolaveri didi",
    "koll zakk",
    "kool khara",
    "koom bee",
    "koos",
    "koos akhotkha hatsola'at",
    "koos imek",
    "koosich jayef",
    "koosich simeen",
    "kos abo",
    "kos ahlak manayek",
    "kos amk",
    "kos em yele bazarak mentak",
    "kos okhtak",
    "kos omak",
    "kos omak ebn sharmota",
    "kos omak ya ibn al sharmoot",
    "kos sittak",
    "kosma yara",
    "koso5tak",
    "kosomak",
    "koss omak",
    "kowwad",
    "kss okht elee nafadak aars",
    "kulsoum",
    "kus allah",
    "kus el kurd",
    "kus emakh",
    "kus ohtak",
    "kus okhtish",
    "kus omak",
    "kus omok",
    "kus ummak",
    "kusomak",
    "kuss omak qimae",
    "kussik emaffin",
    "la rovize",
    "la39",
    "la7s",
    "labawy",
    "labwa",
    "lehbeela",
    "lehbila",
    "lhass baydeteh",
    "lhwa dwa",
    "llah dialk kaymoss liya zabbi",
    "llah dialk ngalsso ala zabbi",
    "looti",
    "louat",
    "louteh",
    "louty",
    "lubia",
    "m'zroob",
    "m3arras",
    "ma'aras",
    "ma3rasa",
    "maabol",
    "maabol del hla",
    "maalish lulu",
    "madhara",
    "mahbool",
    "majdoube",
    "makwa",
    "malhat",
    "malla ras eyr yaleh 3alek",
    "mamsoo5",
    "mamsookh",
    "mamsoukh",
    "mamsoukha",
    "manek",
    "mani fehem zeb man fi zaaket",
    "manuke khara",
    "manukey",
    "manyok",
    "manyoka",
    "manyoke",
    "manyook",
    "mara",
    "marioah",
    "mart al tkawid",
    "mas5a",
    "mas5ota",
    "masaho",
    "masasa",
    "mass zebbi",
    "masteje",
    "matny",
    "maybon",
    "maybona",
    "mayboon",
    "mayboona",
    "mazloula",
    "mchi thawa",
    "mehaijeh",
    "menaswen",
    "mennuke",
    "metfarswa3",
    "metfarswaa'",
    "metnaak",
    "metnak",
    "metnaka",
    "metrama",
    "mfal2as",
    "mfal2asa",
    "mfannes",
    "mfannesa",
    "miboun",
    "miloud weld habiba",
    "mishtaheek",
    "mkauda",
    "mngala",
    "mo3ak",
    "mo5anath",
    "mok 9a7ba",
    "mok ka7ba",
    "mok kahba",
    "mos hozy wa enta sakt",
    "mos zbi",
    "mos zibby",
    "mos zibi wa enta sakt",
    "moss",
    "moss ayri",
    "moss eri",
    "moss eyri",
    "moss zabri",
    "moss zibi",
    "mossi eri",
    "mossli krarzi",
    "mosss ereee",
    "mostankaa al chaba",
    "mota5alef",
    "motakhalef",
    "motasawel",
    "mothaa",
    "mozza",
    "mqawda elik",
    "mrtoo ao mltoo",
    "ms5ota",
    "mus airy",
    "mus zubi ya ibn al kalb",
    "muss zebby",
    "naahachoun yemak",
    "naan dirabek",
    "naan zok omek",
    "naghal",
    "nahwi lik titiza dialk",
    "nahwik",
    "nahwik min lour",
    "naiek",
    "nakech",
    "nam",
    "namm",
    "naqal",
    "naqsh",
    "narcoossee",
    "nayaak ghbar",
    "naych raask",
    "nayek ekhtak",
    "nayek emmak",
    "nayek hareemek",
    "nayik zeb",
    "nayket bat",
    "nboul lik fi wajhek",
    "neek",
    "neek hallak",
    "neek nafsek",
    "neek rasi",
    "neekni",
    "neekni sahrawi",
    "neekni wlaa tneek hargeti",
    "neik",
    "neka",
    "neka7",
    "nekah sahraoe",
    "nekni ana sharyaana",
    "nela aboka",
    "nethell",
    "nfokho",
    "nghtasbek",
    "nhabtik chicha",
    "nik jedak",
    "nikit immak",
    "nikkabuk",
    "niklek bzezlek",
    "niklik omik",
    "nikmok",
    "njibo fik",
    "nkhshih fik bla dfal",
    "nock nullah",
    "nouna",
    "nouri al maliki",
    "nrsam lik tabone fwajhek",
    "ntak",
    "ntokbek",
    "nwaan",
    "nwassaaha lik",
    "nyak al nana tab3ak",
    "oja gu chinnj",
    "okhoo el gahbaa",
    "okht al tkawid",
    "okht' el teney-yich",
    "okul khara ya ibn el kalb",
    "omak mesasa",
    "ommak fasya",
    "ommek malhet kbir",
    "ookal khara",
    "qah'ba",
    "qahabah",
    "qahbi",
    "qalab wighek",
    "qaraqir",
    "qawad",
    "qird",
    "qlawi",
    "qodok",
    "qooq",
    "qooq ukhtak",
    "qooq ummak",
    "qusamak",
    "qybah",
    "raas el 3asba",
    "raas il zub",
    "rab dialk kan7wih min zkko",
    "raey isbayan",
    "ras al-air",
    "rass el zebb",
    "rassol dialk akbar zaml",
    "rassol lkalb kayrde3 zbouba",
    "rbayb rabbak zwiml",
    "rkab ayre",
    "roh intak",
    "rooh entak",
    "rooh etnak",
    "rou7 wa nek 7alek",
    "rouh entak",
    "rouh nik omek",
    "rouh wa sittin erd ma'ak",
    "rozsomack",
    "salgot",
    "sambool",
    "sambool fi fqa'htak",
    "sambool maa ybool",
    "sambooli maa indi ghairoo",
    "sayeb zebi",
    "scaget",
    "seer tkaffat",
    "shaarat mook",
    "shadome",
    "shahwa",
    "shakl il nahaan",
    "shaksh",
    "shalaga",
    "shaloteya",
    "shanbora",
    "sharag",
    "sharameet",
    "sharmoot",
    "sharmoota",
    "sharmootah",
    "sharmootta",
    "sharmot",
    "sharmotah",
    "shayet",
    "shayta",
    "shbi dirrabek",
    "sheikha",
    "shim baydati",
    "shlekke",
    "shlok'keh",
    "shlokeh",
    "shloomfuss",
    "shof hal kisas",
    "shoof kalba tneekak",
    "shoowathi",
    "shrbe mneh",
    "shufte binta",
    "shufte cos",
    "sidd bih",
    "sir lanhwi lik rabbak",
    "sir oula ghan houik",
    "sir t'hwi kahbat mok",
    "sir taawad",
    "sir thawa",
    "sir tkaoud",
    "sir tkawed",
    "skayrey",
    "skayreyya",
    "so7ak",
    "so7akeyya",
    "sobisa",
    "soowa",
    "sopessa",
    "sorm",
    "sormaha",
    "sormak",
    "sowa",
    "spontchi",
    "ssossi",
    "sur muk",
    "surm",
    "surum",
    "ta'a erdaa",
    "ta'a mea'oo",
    "ta77an",
    "taa' mos",
    "tabaarek yadaak",
    "tabbon mok",
    "tabon",
    "tabon dyal bok",
    "tabon dyemak",
    "tabonak",
    "tabonek",
    "tabonek wassee",
    "taboon",
    "taboonak",
    "taboonek",
    "taboune mok",
    "tahhan",
    "tarma",
    "teezak",
    "teezak maftouh",
    "teezha",
    "teezhom",
    "teezo",
    "teiz",
    "tel has tisee",
    "telab be resli",
    "telhas airi",
    "telhas bekhsh zobe",
    "telhas bekhshi",
    "telhas bokhshi",
    "telhas ma tina'a",
    "telhas ras airi",
    "telhas teezi",
    "telhas zebbi",
    "telhass tizi",
    "terma",
    "tetzaber",
    "tezak",
    "tfo ala kos omak",
    "tilhahs teezi",
    "tilhas tizi",
    "tina",
    "tint rabbok",
    "tintaki",
    "tizak",
    "tizak hamra",
    "tkaffat",
    "tobon imak",
    "um el eyura",
    "umka sharmota",
    "us kut",
    "w3ra",
    "wa'ala zeu",
    "wa3ra",
    "waa abooy",
    "waa faqri",
    "wald dhroot",
    "wald il 16",
    "wald il dhuroot",
    "wald il hawyaa",
    "wald il klaab",
    "wald il qahbaa",
    "wald il qaraqir",
    "wald il qawad",
    "wald il zinaa",
    "wald qahbat qureesh",
    "weld elgahba",
    "wilad el shawarig",
    "wild el gahba",
    "would al kahba",
    "wskh",
    "wskha",
    "wuled el kakhbah",
    "wydad",
    "ya a'andeen zak omek",
    "ya aars",
    "ya abn al shrmota",
    "ya abo somar",
    "ya air",
    "ya akho l mentakeh",
    "ya ars",
    "ya arse",
    "ya ba'ara",
    "ya balla'a el air",
    "ya batroneh",
    "ya bgal",
    "ya bint el-haram",
    "ya bint el-khinzir",
    "ya bokhesh",
    "ya ebn el mara",
    "ya ebn el wskha",
    "ya ebn jiranak",
    "ya ebn l bala'a",
    "ya ebn l looti",
    "ya ebn l mesealeh",
    "ya ebn l mintakeh",
    "ya ehmar",
    "ya gawad",
    "ya gizma",
    "ya hayawan",
    "ya ibn el jahsh",
    "ya ibn el labwa",
    "ya ibn el sarma",
    "ya ibn elfashkha",
    "ya ibn il daa'reh",
    "ya ibn il sharmoota",
    "ya kahba",
    "ya kus",
    "ya louteh",
    "ya miboun",
    "ya mnashef",
    "ya motakhalef",
    "ya noori",
    "ya walden kabah",
    "ya wati",
    "ya weld elgahba",
    "ya zebala",
    "ya zebbala",
    "yaa raabi",
    "yaatik namm",
    "yakhrab baytak",
    "yalean maytink",
    "yalla maal saham",
    "ybn el-mitneka",
    "yddek fi zob",
    "yefdah ardak",
    "yekhrib betak",
    "yel'aan naik emak",
    "yel'an deen omak",
    "yel'an ekht yali khalafak bi ayree akit manyookee",
    "yelaan abook arsa",
    "yelan abo taarees immak",
    "yelan abo taareesak",
    "yelan abook ars",
    "yelan el kees hali khalakak",
    "yelan fatsak",
    "yelan ta'aris ardak",
    "yena'an kusha ommak",
    "yetzaber",
    "yl3an taboon mok",
    "yla'an haramak",
    "your ass is red",
    "zaaka",
    "zab",
    "zabbour",
    "zabour omek",
    "zabzoub",
    "zac",
    "zacomak",
    "zaghnaboot",
    "zak",
    "zakomak",
    "zamel",
    "zamel bok",
    "zaml bok",
    "zammel",
    "zanboor",
    "zeb",
    "zebak",
    "zebala",
    "zebi fek",
    "zeby",
    "zeby 3aleek",
    "zeby f bo'ak",
    "zeby f tezak",
    "zeg",
    "zega",
    "zegg",
    "zegga",
    "zep",
    "zib",
    "zibbe",
    "zibi",
    "zip",
    "zippak",
    "zippy",
    "zizi",
    "zmal",
    "zob kbeer",
    "zobbi be ommok",
    "zobi kbeer",
    "zobr",
    "zobrak",
    "zobry",
    "zok",
    "zouk",
    "zrba abteezk",
    "zubih",
    "zubra",
    "zuk",
    "zwamel",
    "zwimel",
    "أ",
    "أحط رجل",
    "أطرش",
    "أعمى",
    "أهبل",
    "ا",
    "اء",
    "ابعتل",
    "ابن الاحبة",
    "ابن البلاعة",
    "ابن الحمار",
    "ابن الشرموطة",
    "ابن العاهرة",
    "ابن العرص",
    "ابن الفشخة",
    "ابن القحبة",
    "ابن اللبوة",
    "ابن المتناكة",
    "ابن المرا",
    "ابن المرة",
    "ابن الممحونة",
    "ابن النيك",
    "ابن الوسخة",
    "ابن حمار",
    "ابن عاهر",
    "ابن كلب",
    "ابو ر",
    "ابو شخة",
    "ابو شخه",
    "ابو فص",
    "ابو قرعة",
    "اتن",
    "احا",
    "احترم نفسك",
    "احتلام",
    "احلي كث",
    "احمق",
    "احه",
    "احيه",
    "اختك",
    "اخذك",
    "اخو القحبه",
    "اذهب الى الجح",
    "اصبع على صرمك",
    "اصمت",
    "اطرش",
    "اطفح",
    "اطفح بالسم الهار",
    "اطفح بسم الهار",
    "اعمى",
    "اغب",
    "اغتصاب",
    "افسخك",
    "اقرع",
    "اقلب وجهك",
    "الأحمق",
    "الحس ط",
    "الحس مكوت",
    "الحمار",
    "الخرائ",
    "الزب",
    "السافل",
    "الساقط",
    "الش",
    "العايب",
    "العربان",
    "العرص",
    "العمى",
    "القحبة",
    "القرف",
    "الكحبة",
    "الكحبه",
    "الكس",
    "الكلبة",
    "اللعنة عل",
    "الله",
    "الله لا",
    "الله ياخ",
    "الن",
    "امروج فى ع",
    "امش",
    "امك",
    "امك شرموطه",
    "ان",
    "انت شاذ",
    "انت عبيط",
    "انت غبي",
    "انتا كلبى",
    "انذال",
    "انذل",
    "انعل ابو",
    "انكح",
    "انكحك",
    "انيك",
    "انيكك",
    "اه ك",
    "اهبل",
    "اونطي",
    "اير",
    "ايري",
    "ايري ب",
    "ايري ف",
    "ب",
    "بابوك",
    "باترون",
    "باختك",
    "بارا نا",
    "بالسم الهار",
    "بامك",
    "ببخش ط",
    "ببز",
    "بحشى رجلى فى ط",
    "بخ",
    "بد",
    "بز",
    "بزاز",
    "بزرك",
    "بستك",
    "بسم الهار",
    "بشخ عل",
    "بشخ على امك",
    "بط",
    "بظر",
    "بعبص",
    "بعبوص",
    "بعص",
    "بغ",
    "بغاي",
    "بلطج",
    "بن",
    "بن كلب",
    "بنت الحمار",
    "بنت الشرموطة",
    "بنت العاهرة",
    "بنت العرص",
    "بنت الفشخة",
    "بنت القحبة",
    "بنت اللبوة",
    "بنت المتناكة",
    "بنت الممحونة",
    "بنت المنتاكة",
    "بنت الوسخة",
    "بنت حمار",
    "بنت كلب",
    "بندوق",
    "به",
    "بها",
    "بهيمة",
    "بوس ط",
    "بيضان",
    "ة",
    "ة الزفت دة",
    "تافه",
    "تتناك",
    "تتناك فى ط",
    "تتناك فى كسها",
    "تجليخ",
    "ترهيط",
    "تزغيب",
    "تمص",
    "تناك فى ط",
    "تنتاك",
    "تنتاك فى ط",
    "تنتاك فى كسها",
    "ثدي",
    "جلخ",
    "جماع",
    "حرامي",
    "حقير",
    "حلبتها",
    "حلبتو",
    "حلمات",
    "حلمة",
    "حمير",
    "حه",
    "حيوان",
    "خدك",
    "خراي",
    "خرة",
    "خرى",
    "خري",
    "خسيس",
    "خنثي",
    "خنيث",
    "خوازيق",
    "خول",
    "داشر",
    "داعر",
    "دعارة",
    "دلخ",
    "ديوث",
    "ديود",
    "ر",
    "رى بط",
    "ز",
    "ز امك",
    "زا لامك",
    "زات اختك",
    "زبار",
    "زبالة",
    "زباله",
    "زبر",
    "زبه",
    "زبي",
    "زراط",
    "زق",
    "زك",
    "زك و بركض ف",
    "زناة",
    "زناطير",
    "زه",
    "زها",
    "زى",
    "ساذج",
    "سافل",
    "سحاق",
    "سحاقية",
    "سربوط",
    "سرموتا",
    "سفالة",
    "سكس",
    "سكسي",
    "سى",
    "سيكس",
    "سيكسي",
    "شاذ",
    "شرج",
    "شرمها",
    "شرموط",
    "شرموطه",
    "شلقة",
    "شلكة",
    "شهوة",
    "صايع",
    "صياعة",
    "ض",
    "ضاتى",
    "ضرب عشرة",
    "طان عل",
    "طز في",
    "طيز",
    "عاهر",
    "عاهرة",
    "عايبة",
    "عبيط",
    "عديم الشرف",
    "عرص",
    "عط",
    "عيال الحرام",
    "غتصب",
    "ف",
    "فاجر",
    "فاسق",
    "فجور",
    "فرج",
    "فوت ا",
    "فى وجه امك",
    "قحاب",
    "قحب",
    "قضيب",
    "قضيب كبير",
    "قضيبي",
    "قلبك",
    "ك",
    "ك العاف",
    "ك امك",
    "ك بزاز امك",
    "ك فى الط",
    "ك فى الكس",
    "ك كسك",
    "ك كوسك",
    "كحبة",
    "كذاب",
    "كس اختك",
    "كس امك",
    "كس عرضك",
    "كسمك",
    "كسمكم",
    "كسها",
    "كك",
    "كل خرا",
    "كل خرة",
    "كلام",
    "كم",
    "كول خر",
    "ل",
    "ل بن",
    "لان كتاب",
    "لبوة",
    "لة",
    "لحس",
    "لعق",
    "لعنك",
    "لعين",
    "لقحاب",
    "لواط",
    "لوطي",
    "م",
    "مأجور",
    "مبادل",
    "مبعوص",
    "مة",
    "متخوزق",
    "متناك",
    "متناكة",
    "مجنون",
    "مخانيث",
    "مخنث",
    "مدلس",
    "مص",
    "معوهر",
    "مفسوخ",
    "مفلقسة",
    "مكسكس",
    "مكوتها",
    "ملعون",
    "ممحون",
    "منايك",
    "منيك",
    "منيوك",
    "ن",
    "ناكك",
    "نجس",
    "نعل ابوك",
    "نعل ابوكم",
    "نك",
    "نكت اخته",
    "نكت امه",
    "نياكة",
    "نياكه",
    "نيك",
    "واطي",
    "وسخ",
    "ولد القحبة",
    "ولد القحبه",
    "يا هبيلة",
    "يلعن",
] as const;

export default words;
