/**
 * English banned words
 *
 * Sources:
 * - Curated list
 * - https://github.com/coffee-and-fun/google-profanity-words
 * - https://github.com/viddexa/safetext
 */
const words: ReadonlyArray<string> = [
    "nigger",
    "nigga",
    "niggers",
    "niggas",
    "negro",
    "negroid",
    "coon",
    "coons",
    "darkie",
    "darkies",
    "jigaboo",
    "jigaboos",
    "spook",
    "sambo",
    "pickaninny",
    "mammy",
    "jungle bunny",
    "porch monkey",
    "tar baby",
    "uncle tom",
    "chink",
    "chinks",
    "chinaman",
    "gook",
    "gooks",
    "slant-eye",
    "zipperhead",
    "ching chong",
    "orientals",
    "wetback",
    "wetbacks",
    "beaner",
    "beaners",
    "spic",
    "spics",
    "greaser",
    "greasers",
    "illegal alien",
    "kike",
    "kikes",
    "hebe",
    "heeb",
    "yid",
    "wop",
    "wops",
    "dago",
    "dagos",
    "guido",
    "guinea",
    "mick",
    "micks",
    "paddy",
    "paddies",
    "polack",
    "polacks",
    "raghead",
    "ragheads",
    "towelhead",
    "towelheads",
    "sandnigger",
    "sandniggers",
    "camel jockey",
    "hajji",
    "cracker",
    "crackers",
    "honky",
    "honkey",
    "redneck trash",
    "white trash",
    "redskin",
    "redskins",
    "injun",
    "squaw",
    "abo",
    "abos",
    "boong",
    "boongs",
    "coonass",
    "half-breed",
    "half breed",
    "mulatto",
    "faggot",
    "faggots",
    "fag",
    "fags",
    "dyke",
    "dykes",
    "homo",
    "homos",
    "queer",
    "queers",
    "tranny",
    "trannies",
    "shemale",
    "shemales",
    "he-she",
    "ladyboy",
    "ladyboys",
    "sissy",
    "pansy",
    "pansies",
    "sodomite",
    "sodomites",
    "butt pirate",
    "retard",
    "retards",
    "retarded",
    "tard",
    "tards",
    "spaz",
    "spazz",
    "spastic",
    "cripple",
    "cripples",
    "gimp",
    "gimps",
    "mongoloid",
    "mongoloids",
    "imbecile",
    "imbeciles",
    "moron",
    "infidel",
    "infidels",
    "heathen",
    "heathens",
    "christ killer",
    "christ killers",
    "bitch",
    "bitches",
    "cunt",
    "cunts",
    "whore",
    "whores",
    "slut",
    "sluts",
    "skank",
    "skanks",
    "twat",
    "twats",
    "ho",
    "hoe",
    "fuck",
    "fucker",
    "fuckers",
    "fucking",
    "motherfucker",
    "motherfuckers",
    "fuckface",
    "clusterfuck",
    "shit",
    "shithead",
    "shitheads",
    "bullshit",
    "horseshit",
    "dipshit",
    "shitface",
    "piece of shit",
    "ass",
    "asshole",
    "assholes",
    "jackass",
    "dumbass",
    "cock",
    "cocksucker",
    "cocksuckers",
    "dick",
    "dickhead",
    "dickheads",
    "prick",
    "pricks",
    "pussy",
    "pussies",
    "cum",
    "cumshot",
    "jizz",
    "wank",
    "wanker",
    "wankers",
    "blowjob",
    "handjob",
    "rimjob",
    "dildo",
    "dildos",
    "vibrator",
    "tits",
    "titties",
    "boobs",
    "boobies",
    "fellatio",
    "cunnilingus",
    "anal",
    "anus",
    "masturbate",
    "masturbation",
    "orgasm",
    "erection",
    "ejaculate",
    "ejaculation",
    "pornography",
    "porn",
    "hentai",
    "xxx",
    "kill yourself",
    "kys",
    "go die",
    "rape",
    "raping",
    "rapist",
    "rapists",
    "molest",
    "molester",
    "molestation",
    "pedophile",
    "pedophiles",
    "paedophile",
    "paedophiles",
    "lynch",
    "lynching",
    "genocide",
    "ethnic cleansing",
    "gas the",
    "gas chamber",
    "death threat",
    "i will kill you",
    "bomb threat",
    "nazi",
    "nazis",
    "neo-nazi",
    "neonazi",
    "white power",
    "white supremacy",
    "white supremacist",
    "heil hitler",
    "sieg heil",
    "aryan",
    "aryan nation",
    "aryan brotherhood",
    "kkk",
    "ku klux klan",
    "blood and soil",
    "fourteen words",
    "1488",
    "14/88",
    "subhuman",
    "subhumans",
    "untermensch",
    "vermin",
    "parasite",
    "parasites",
    "cockroach",
    "cockroaches",
    "animal",
    "animals",
    "ape",
    "apes",
    "monkey",
    "monkeys",
    "bastard",
    "bastards",
    "douche",
    "douchebag",
    "douchebags",
    "scumbag",
    "scumbags",
    "piss off",
    "go to hell",
    "stfu",
    "gtfo",
    "2 girls 1 cup",
    "2g1c",
    "4r5e",
    "5h1t",
    "5hit",
    "a55",
    "a_s_s",
    "acrotomophilia",
    "alabama hot pocket",
    "alaskan pipeline",
    "anilingus",
    "apeshit",
    "ar5e",
    "arrse",
    "arse",
    "arsehole",
    "ass-fucker",
    "ass-hat",
    "ass-pirate",
    "assbag",
    "assbandit",
    "assbanger",
    "assbite",
    "assclown",
    "asscock",
    "asscracker",
    "asses",
    "assface",
    "assfucker",
    "assfukka",
    "assgoblin",
    "asshat",
    "asshead",
    "asshopper",
    "assjacker",
    "asslick",
    "asslicker",
    "assmonkey",
    "assmunch",
    "assmuncher",
    "asspirate",
    "assshole",
    "asssucker",
    "asswad",
    "asswhole",
    "asswipe",
    "auto erotic",
    "autoerotic",
    "b!tch",
    "b00bs",
    "b17ch",
    "b1tch",
    "babeland",
    "baby batter",
    "baby juice",
    "ball gag",
    "ball gravy",
    "ball kicking",
    "ball licking",
    "ball sack",
    "ball sucking",
    "ballbag",
    "balls",
    "ballsack",
    "bampot",
    "bangbros",
    "bareback",
    "barely legal",
    "barenaked",
    "bastardo",
    "bastinado",
    "bbw",
    "bdsm",
    "beastial",
    "beastiality",
    "beastility",
    "beaver cleaver",
    "beaver lips",
    "bellend",
    "bestial",
    "bestiality",
    "bi+ch",
    "biatch",
    "big black",
    "big breasts",
    "big knockers",
    "big tits",
    "bimbos",
    "birdlock",
    "bitcher",
    "bitchers",
    "bitchin",
    "bitching",
    "black cock",
    "blonde action",
    "blonde on blonde action",
    "bloody",
    "blow job",
    "blow your load",
    "blowjobs",
    "blue waffle",
    "blumpkin",
    "boiolas",
    "bollock",
    "bollocks",
    "bollok",
    "bollox",
    "bondage",
    "boner",
    "boob",
    "boobie",
    "booobs",
    "boooobs",
    "booooobs",
    "booooooobs",
    "booty call",
    "breasts",
    "brown showers",
    "brunette action",
    "buceta",
    "bugger",
    "bukkake",
    "bulldyke",
    "bullet vibe",
    "bum",
    "bung hole",
    "bunghole",
    "bunny fucker",
    "busty",
    "butt",
    "butt-pirate",
    "buttcheeks",
    "butthole",
    "buttmunch",
    "buttplug",
    "c0ck",
    "c0cksucker",
    "camel toe",
    "camgirl",
    "camslut",
    "camwhore",
    "carpet muncher",
    "carpetmuncher",
    "cawk",
    "chinc",
    "choad",
    "chocolate rosebuds",
    "chode",
    "cipa",
    "circlejerk",
    "cl1t",
    "cleveland steamer",
    "clit",
    "clitface",
    "clitoris",
    "clits",
    "clover clamps",
    "cnut",
    "cock-sucker",
    "cockbite",
    "cockburger",
    "cockface",
    "cockhead",
    "cockjockey",
    "cockknoker",
    "cockmaster",
    "cockmongler",
    "cockmongruel",
    "cockmonkey",
    "cockmunch",
    "cockmuncher",
    "cocknose",
    "cocknugget",
    "cocks",
    "cockshit",
    "cocksmith",
    "cocksmoker",
    "cocksuck",
    "cocksucked",
    "cocksucking",
    "cocksucks",
    "cocksuka",
    "cocksukka",
    "cok",
    "cokmuncher",
    "coksucka",
    "coochie",
    "coochy",
    "cooter",
    "coprolagnia",
    "coprophilia",
    "cornhole",
    "cox",
    "crap",
    "creampie",
    "cumbubble",
    "cumdumpster",
    "cumguzzler",
    "cumjockey",
    "cummer",
    "cumming",
    "cums",
    "cumslut",
    "cumtart",
    "cunilingus",
    "cunillingus",
    "cunnie",
    "cuntface",
    "cunthole",
    "cuntlick",
    "cuntlicker",
    "cuntlicking",
    "cuntrag",
    "cyalis",
    "cyberfuc",
    "cyberfuck",
    "cyberfucked",
    "cyberfucker",
    "cyberfuckers",
    "cyberfucking",
    "d1ck",
    "dammit",
    "damn",
    "date rape",
    "daterape",
    "deep throat",
    "deepthroat",
    "dendrophilia",
    "dickbag",
    "dickbeater",
    "dickface",
    "dickhole",
    "dickjuice",
    "dickmilk",
    "dickmonger",
    "dickslap",
    "dicksucker",
    "dickwad",
    "dickweasel",
    "dickweed",
    "dickwod",
    "dike",
    "dingleberries",
    "dingleberry",
    "dink",
    "dinks",
    "dirsa",
    "dirty pillows",
    "dirty sanchez",
    "dlck",
    "dog style",
    "dog-fucker",
    "doggie style",
    "doggiestyle",
    "doggin",
    "dogging",
    "doggy style",
    "doggystyle",
    "dolcett",
    "domination",
    "dominatrix",
    "dommes",
    "donkey punch",
    "donkeyribber",
    "doochbag",
    "dookie",
    "doosh",
    "double dong",
    "double penetration",
    "dp action",
    "dry hump",
    "duche",
    "dumb",
    "dumbshit",
    "dumshit",
    "dvda",
    "eat my ass",
    "ecchi",
    "ejaculated",
    "ejaculates",
    "ejaculating",
    "ejaculatings",
    "ejakulate",
    "erotic",
    "erotism",
    "escort",
    "eunuch",
    "f u c k",
    "f u c k e r",
    "f4nny",
    "f_u_c_k",
    "fagbag",
    "fagg",
    "fagging",
    "faggit",
    "faggitt",
    "faggs",
    "fagot",
    "fagots",
    "fagtard",
    "fanny",
    "fannyflaps",
    "fannyfucker",
    "fanyy",
    "fart",
    "farted",
    "farting",
    "farty",
    "fatass",
    "fcuk",
    "fcuker",
    "fcuking",
    "fecal",
    "feck",
    "fecker",
    "felatio",
    "felch",
    "felching",
    "fellate",
    "feltch",
    "female squirting",
    "femdom",
    "figging",
    "fingerbang",
    "fingerfuck",
    "fingerfucked",
    "fingerfucker",
    "fingerfuckers",
    "fingerfucking",
    "fingerfucks",
    "fingering",
    "fistfuck",
    "fistfucked",
    "fistfucker",
    "fistfuckers",
    "fistfucking",
    "fistfuckings",
    "fistfucks",
    "fisting",
    "flamer",
    "flange",
    "fook",
    "fooker",
    "fool",
    "foot fetish",
    "footjob",
    "frotting",
    "fuck buttons",
    "fucka",
    "fucked",
    "fuckhead",
    "fuckheads",
    "fuckin",
    "fuckings",
    "fuckingshitmotherfucker",
    "fuckme",
    "fucks",
    "fucktards",
    "fuckwhit",
    "fuckwit",
    "fudge packer",
    "fudgepacker",
    "fuk",
    "fuker",
    "fukker",
    "fukkin",
    "fuks",
    "fukwhit",
    "fukwit",
    "futanari",
    "fux",
    "fux0r",
    "g-spot",
    "gang bang",
    "gangbang",
    "gangbanged",
    "gangbangs",
    "gay sex",
    "gayass",
    "gaybob",
    "gaydo",
    "gaylord",
    "gaysex",
    "gaytard",
    "gaywad",
    "genitals",
    "giant cock",
    "girl on",
    "girl on top",
    "girls gone wild",
    "goatcx",
    "goatse",
    "god damn",
    "god-dam",
    "god-damned",
    "goddamn",
    "goddamned",
    "gokkun",
    "golden shower",
    "goo girl",
    "gooch",
    "goodpoop",
    "goregasm",
    "gringo",
    "grope",
    "group sex",
    "guro",
    "hand job",
    "hard core",
    "hardcore",
    "hardcoresex",
    "hell",
    "heshe",
    "hoar",
    "hoare",
    "hoer",
    "homoerotic",
    "hooker",
    "hore",
    "horniest",
    "horny",
    "hot carl",
    "hot chick",
    "hotsex",
    "how to kill",
    "how to murder",
    "huge fat",
    "humping",
    "incest",
    "intercourse",
    "jack off",
    "jack-off",
    "jackoff",
    "jail bait",
    "jailbait",
    "jap",
    "jelly donut",
    "jerk",
    "jerk off",
    "jerk-off",
    "jiggaboo",
    "jiggerboo",
    "jism",
    "jiz",
    "jizm",
    "juggs",
    "kawk",
    "kinbaku",
    "kinkster",
    "kinky",
    "kiunt",
    "knob",
    "knobbing",
    "knobead",
    "knobed",
    "knobend",
    "knobhead",
    "knobjocky",
    "knobjokey",
    "kock",
    "kondum",
    "kondums",
    "kooch",
    "kootch",
    "kum",
    "kumer",
    "kummer",
    "kumming",
    "kums",
    "kunilingus",
    "kunt",
    "kyke",
    "l3i+ch",
    "l3itch",
    "labia",
    "leather restraint",
    "leather straight jacket",
    "lemon party",
    "lesbo",
    "lezzie",
    "lmfao",
    "lolita",
    "lovemaking",
    "lust",
    "lusting",
    "m0f0",
    "m0fo",
    "m45terbate",
    "ma5terb8",
    "ma5terbate",
    "make me come",
    "male squirting",
    "masochist",
    "master-bate",
    "masterb8",
    "masterbat*",
    "masterbat3",
    "masterbate",
    "masterbation",
    "masterbations",
    "menage a trois",
    "milf",
    "minge",
    "missionary position",
    "mo-fo",
    "mof0",
    "mofo",
    "mothafuck",
    "mothafucka",
    "mothafuckas",
    "mothafuckaz",
    "mothafucked",
    "mothafucker",
    "mothafuckers",
    "mothafuckin",
    "mothafucking",
    "mothafuckings",
    "mothafucks",
    "mother fucker",
    "motherfuck",
    "motherfucked",
    "motherfuckin",
    "motherfucking",
    "motherfuckings",
    "motherfuckka",
    "motherfucks",
    "mound of venus",
    "mr hands",
    "muff",
    "muff diver",
    "muffdiver",
    "muffdiving",
    "mutha",
    "muthafecker",
    "muthafuckker",
    "muther",
    "mutherfucker",
    "n1gga",
    "n1gger",
    "nambla",
    "nawashi",
    "nig nog",
    "nigg3r",
    "nigg4h",
    "niggah",
    "niggaz",
    "niglet",
    "nimphomania",
    "nipple",
    "nipples",
    "nob",
    "nob jokey",
    "nobhead",
    "nobjocky",
    "nobjokey",
    "nsfw images",
    "nude",
    "nudity",
    "numbnuts",
    "nutsack",
    "nympho",
    "nymphomania",
    "octopussy",
    "omorashi",
    "one cup two girls",
    "one guy one jar",
    "orgasim",
    "orgasims",
    "orgasms",
    "orgy",
    "p0rn",
    "paki",
    "panooch",
    "panties",
    "panty",
    "pawn",
    "pecker",
    "peckerhead",
    "pedobear",
    "pegging",
    "penis",
    "penisfucker",
    "phone sex",
    "phonesex",
    "phuck",
    "phuk",
    "phuked",
    "phuking",
    "phukked",
    "phukking",
    "phuks",
    "phuq",
    "pigfucker",
    "pimpis",
    "pis",
    "pises",
    "pisin",
    "pising",
    "pisof",
    "piss",
    "piss pig",
    "pissed",
    "pisser",
    "pissers",
    "pisses",
    "pissflap",
    "pissflaps",
    "pissin",
    "pissing",
    "pissoff",
    "pisspig",
    "playboy",
    "pleasure chest",
    "pole smoker",
    "polesmoker",
    "pollock",
    "ponyplay",
    "poo",
    "poof",
    "poon",
    "poonani",
    "poonany",
    "poontang",
    "poop",
    "poop chute",
    "poopchute",
    "porno",
    "pornos",
    "prince albert piercing",
    "pron",
    "pthc",
    "pube",
    "pubes",
    "punanny",
    "punany",
    "punta",
    "pusies",
    "pusse",
    "pussi",
    "pussylicking",
    "pussys",
    "pusy",
    "puto",
    "queaf",
    "queef",
    "queerbait",
    "queerhole",
    "quim",
    "raging boner",
    "rectum",
    "renob",
    "reverse cowgirl",
    "rimjaw",
    "rimming",
    "rosy palm",
    "rosy palm and her 5 sisters",
    "ruski",
    "rusty trombone",
    "s hit",
    "s&m",
    "s.o.b.",
    "s_h_i_t",
    "sadism",
    "sadist",
    "santorum",
    "scat",
    "schlong",
    "scissoring",
    "screwing",
    "scroat",
    "scrote",
    "scrotum",
    "semen",
    "sex",
    "sexo",
    "sexy",
    "sh!+",
    "sh!t",
    "sh1t",
    "shag",
    "shagger",
    "shaggin",
    "shagging",
    "shaved beaver",
    "shaved pussy",
    "shi+",
    "shibari",
    "shit-ass",
    "shit-bag",
    "shit-bagger",
    "shit-brain",
    "shit-breath",
    "shit-cunt",
    "shit-dick",
    "shit-eating",
    "shit-face",
    "shit-faced",
    "shit-fit",
    "shit-head",
    "shit-heel",
    "shit-hole",
    "shit-house",
    "shit-load",
    "shit-pot",
    "shit-spitter",
    "shit-stain",
    "shitass",
    "shitbag",
    "shitbagger",
    "shitblimp",
    "shitbrain",
    "shitbreath",
    "shitcunt",
    "shitdick",
    "shite",
    "shiteating",
    "shited",
    "shitey",
    "shitfaced",
    "shitfit",
    "shitfuck",
    "shitfull",
    "shitheel",
    "shithole",
    "shithouse",
    "shiting",
    "shitings",
    "shitload",
    "shitpot",
    "shits",
    "shitspitter",
    "shitstain",
    "shitted",
    "shitter",
    "shitters",
    "shittiest",
    "shitting",
    "shittings",
    "shitty",
    "shity",
    "shiz",
    "shiznit",
    "shota",
    "shrimping",
    "skeet",
    "slanteye",
    "slutbag",
    "smeg",
    "smegma",
    "smut",
    "snatch",
    "snowballing",
    "sodomize",
    "sodomy",
    "son-of-a-bitch",
    "spac",
    "spick",
    "splooge",
    "splooge moose",
    "spooge",
    "spread legs",
    "spunk",
    "strap on",
    "strapon",
    "strappado",
    "strip club",
    "style doggy",
    "suck",
    "sucker",
    "sucks",
    "suicide girls",
    "sultry women",
    "swastika",
    "swinger",
    "t1tt1e5",
    "t1tties",
    "tainted love",
    "taste my",
    "tea bagging",
    "teets",
    "teez",
    "testical",
    "testicle",
    "threesome",
    "throating",
    "thundercunt",
    "tied up",
    "tight white",
    "tit",
    "titfuck",
    "titt",
    "tittie5",
    "tittiefucker",
    "titty",
    "tittyfuck",
    "tittywank",
    "titwank",
    "tongue in a",
    "topless",
    "tosser",
    "tribadism",
    "tub girl",
    "tubgirl",
    "turd",
    "tushy",
    "tw4t",
    "twathead",
    "twatlips",
    "twatty",
    "twink",
    "twinkie",
    "two girls one cup",
    "twunt",
    "twunter",
    "undressing",
    "upskirt",
    "urethra play",
    "urophilia",
    "v14gra",
    "v1gra",
    "va-j-j",
    "vag",
    "vagina",
    "venus mound",
    "viagra",
    "violet wand",
    "vjayjay",
    "vorarephilia",
    "voyeur",
    "vulva",
    "w00se",
    "wang",
    "wanky",
    "wet dream",
    "whoar",
    "willies",
    "willy",
    "wrapping men",
    "wrinkled starfish",
    "xrated",
    "xx",
    "yaoi",
    "yellow showers",
    "yiffy",
    "zoophilia",
    "🖕",
    "amphetamines",
    "ass fuck",
    "ass hole",
    "badass",
    "bangbus",
    "beeyotch",
    "bimbo",
    "bloody hell",
    "bust a nut",
    "buttmuch",
    "butts",
    "chink eye",
    "chink eyes",
    "cialis",
    "cockfucker",
    "coonnass",
    "cuck",
    "cucked",
    "cucking",
    "cumshots",
    "darn",
    "dicking",
    "dicks",
    "dirty",
    "do her",
    "douches",
    "dumb ass",
    "dumb cunt",
    "dumb fuck",
    "dumb shit",
    "dumbcunt",
    "dumbfuck",
    "dummy",
    "erect",
    "faggy",
    "fat ass",
    "fatso",
    "flip the bird",
    "flipping the bird",
    "fuck off",
    "fuck you",
    "fuckass",
    "fuckhole",
    "fuckpig",
    "fucktard",
    "fur fag",
    "furfag",
    "gang banged",
    "gay",
    "gay lord",
    "get high",
    "goodass",
    "hardcore sex",
    "heroin",
    "high as a kite",
    "idiot",
    "idiots",
    "lesbian",
    "lesbians",
    "livesex",
    "made love",
    "make love",
    "making love",
    "masterbat",
    "masterbater",
    "masterbating",
    "masturbating",
    "masturbator",
    "mong",
    "mother fuckers",
    "mother fuckin",
    "mother fucking",
    "nigguh",
    "nigguhs",
    "nsfw",
    "nutten",
    "on drugs",
    "opium",
    "paedophilia",
    "pedophilia",
    "penetrate",
    "penetration",
    "pikey",
    "poffters",
    "pole humper",
    "poofter",
    "poopy mcpoop face",
    "pornographer",
    "pussie",
    "puta",
    "sexcam",
    "sexual",
    "sexuality",
    "sexually",
    "shit licker",
    "shitlicker",
    "shitnugget",
    "smartass",
    "son of a bitch",
    "stripping",
    "thumbzilla",
    "trannie",
    "voyeurweb",
    "voyuer",
    "wanksta",
    "wankster",
    "worldsex",
] as const;

export default words;
