/**
 * Spanish banned words
 *
 * Sources:
 * - Curated list
 * - https://github.com/coffee-and-fun/google-profanity-words
 * - https://github.com/viddexa/safetext
 */
const words: ReadonlyArray<string> = [
    "negro de mierda",
    "sudaca",
    "sudacas",
    "moro",
    "moros",
    "gitano",
    "gitanos",
    "indio",
    "india",
    "cholo",
    "chola",
    "gringo",
    "gringos",
    "maricon",
    "maricones",
    "marica",
    "joto",
    "jotos",
    "puto",
    "puta",
    "putas",
    "putos",
    "zorra",
    "zorras",
    "ramera",
    "rameras",
    "perra",
    "perras",
    "golfa",
    "golfas",
    "coño",
    "cojones",
    "carajo",
    "mierda",
    "pendejo",
    "pendejos",
    "pendeja",
    "cabron",
    "cabrones",
    "cabrona",
    "hijo de puta",
    "hijoputa",
    "hijueputa",
    "chingar",
    "chingada",
    "chingado",
    "verga",
    "polla",
    "pollas",
    "culo",
    "follar",
    "joder",
    "retrasado",
    "retrasados",
    "subnormal",
    "mogolico",
    "mogolicos",
    "2 chicas 1 taza",
    "2g1c",
    "4r5e",
    "5h1t",
    "5 hit",
    "a55",
    "acrotomofilia",
    "bolsillo caliente de alabama",
    "oleoducto de alaska",
    "anal",
    "anilingus",
    "ano",
    "una mierda",
    "ar5e",
    "gilipollas",
    "follador de culo",
    "culo-gorro",
    "culo-pirata",
    "bolsa de culo",
    "bandido",
    "assbanger",
    "mordida",
    "payaso",
    "rompeculos",
    "culos",
    "cara de culo",
    "enculada",
    "asno duende",
    "idiota",
    "estúpido",
    "imbéciles",
    "asaltante",
    "ladrón de traseros",
    "lamer el culo",
    "lameculos",
    "culo mono",
    "mascador de culos",
    "aspirar",
    "chupador de culos",
    "asswipe",
    "auto erótico",
    "autoerotico",
    "b00bs",
    "b17ch",
    "babeland",
    "masa para bebes",
    "jugo de bebe",
    "mordaza de bola",
    "salsa de bolas",
    "patear la pelota",
    "pelota lamiendo",
    "saco de pelota",
    "chupando bolas",
    "bolsa de pelota",
    "pelotas",
    "saco de bolas",
    "bampot",
    "bang bros",
    "a pelo",
    "apenas legal",
    "desnudo",
    "bastardo",
    "bastinado",
    "bbw",
    "bdsm",
    "frijol",
    "frijoles",
    "bestial",
    "bestialidad",
    "cuchillo de castor",
    "labios de castor",
    "campana",
    "grande y negro",
    "pechos grandes",
    "grandes aldabas",
    "grandes tetas",
    "tontas",
    "cerradura de pájaro",
    "quejándose",
    "gallo negro",
    "acción rubia",
    "rubia sobre rubia acción",
    "sangriento",
    "mamada",
    "sopla tu carga",
    "mamadas",
    "gofre azul",
    "tonto",
    "boiolas",
    "bollok",
    "bollox",
    "esclavitud",
    "metedura de pata",
    "teta",
    "bobo",
    "tetas",
    "booooooobs",
    "llamada de botín",
    "senos",
    "duchas marrones",
    "acción morena",
    "buceta",
    "tío",
    "bukkake",
    "bullyke",
    "vibra de bala",
    "agujero de tapón",
    "boca de tonel",
    "conejito hijo de puta",
    "tetona",
    "culata",
    "trasero-pirata",
    "nalgas",
    "ojete",
    "masticar trasero",
    "dedo de camello",
    "camgirl",
    "puta de la cam",
    "camwhore",
    "masticador de alfombras",
    "mascador de alfombras",
    "graznar",
    "chinchilla",
    "grieta",
    "choad",
    "capullos de rosa de chocolate",
    "chode",
    "cipá",
    "círculo idiota",
    "cl1t",
    "vapor de cleveland",
    "clítoris",
    "abrazaderas de trébol",
    "racimo de mierda",
    "nuez",
    "chupapollas",
    "mordedura de gallo",
    "hamburguesa",
    "cara de gallo",
    "cabeza de gallo",
    "jockey",
    "aldaba",
    "maestro de gallos",
    "traficante de gallos",
    "cockmongruel",
    "mono gallo",
    "gallo",
    "comepollas",
    "nariz de gallo",
    "pepita",
    "herrero",
    "fumador de pollas",
    "mamar",
    "mamando",
    "pollasuka",
    "coca",
    "cocinando",
    "coksucka",
    "coochie",
    "chulo",
    "mapache",
    "mapaches",
    "cooter",
    "coprolagnia",
    "coprofilia",
    "cornhole",
    "timonel",
    "tonterías",
    "cremita",
    "semen",
    "desmoronamiento",
    "basurero",
    "devorador de semen",
    "corrida",
    "cummer",
    "correrse",
    "se corre",
    "cunilingus",
    "cunillingus",
    "cunnilingus",
    "cara de chocho",
    "lamer el coño",
    "lamecoños",
    "lamiendo coños",
    "cuntrag",
    "coños",
    "cyalis",
    "cyberfuc",
    "cyberfuck",
    "cibernético",
    "ciberfuckers",
    "d1ck",
    "maldita sea",
    "maldición",
    "moreno",
    "violación en una cita",
    "cita",
    "garganta profunda",
    "dendrofilia",
    "bolsa de pene",
    "batidor de pollas",
    "cara de pene",
    "jugo de polla",
    "dickleche",
    "traficante de pollas",
    "bofetada",
    "comadreja",
    "dickweed",
    "dique",
    "consolador",
    "consoladores",
    "moras",
    "zarzamora",
    "borrachos",
    "dirección",
    "almohadas sucias",
    "sucio sanchez",
    "dlck",
    "estilo perro",
    "follador de perros",
    "estilo perrito",
    "persiguiendo",
    "a cuatro patas",
    "dolcett",
    "dominación",
    "dominatriz",
    "domos",
    "ponche de burro",
    "burro",
    "bolsa de basura",
    "chiflado",
    "doosh",
    "doble polla",
    "doble penetración",
    "ducha",
    "acción doble penetración",
    "joroba seca",
    "estupideces",
    "dvda",
    "come mi culo",
    "ecchi",
    "eyacular",
    "eyaculado",
    "eyacula",
    "eyaculando",
    "eyaculación",
    "erótico",
    "erotismo",
    "escolta",
    "eunuco",
    "f4nny",
    "maricón",
    "mariconear",
    "maricas",
    "fannyflaps",
    "fannyfucker",
    "fanyy",
    "pedo",
    "tirado un pedo",
    "tirando pedos",
    "gordo",
    "fecal",
    "feck",
    "felación",
    "felch",
    "felching",
    "fieltro",
    "chorros femeninos",
    "dominación femenina",
    "fijándose",
    "pistola con la mano",
    "follar con los dedos",
    "dedo follado",
    "follador de dedos",
    "folladores de dedos",
    "follando con los dedos",
    "folla con los dedos",
    "digitación",
    "follar con el puño",
    "puño follado",
    "follador de puños",
    "folladores de puños",
    "follando con el puño",
    "follando con los puños",
    "folla con los puños",
    "puño",
    "lanzallamas",
    "brida",
    "buscar",
    "buscador de",
    "fetichismo de pies",
    "paja de pies",
    "frotándose",
    "botones de mierda",
    "jodido",
    "hijos de puta",
    "imbécil",
    "maldito",
    "malditos",
    "mierdamierdahijo de puta",
    "fóllame",
    "folla",
    "empaquetador de dulces",
    "empacador de chocolate",
    "fuk",
    "fuker",
    "fukker",
    "fukkin",
    "fuks",
    "fukwhit",
    "fukwit",
    "futanari",
    "fux0r",
    "punto g",
    "orgia",
    "gangbanged",
    "orgias",
    "sexo gay",
    "culo gay",
    "gaybob",
    "gaydo",
    "señor gay",
    "tardo gay",
    "gaywad",
    "genitales",
    "polla gigante",
    "chica en",
    "niña en la cima",
    "las chicas se volvieron locas",
    "cabracx",
    "cabra",
    "gokkun",
    "baño de oro",
    "buena chica",
    "gooch",
    "buena caca",
    "bien",
    "goregasmo",
    "ir a tientas",
    "sexo en grupo",
    "guido",
    "guro",
    "trabajo manual",
    "paja",
    "núcleo duro",
    "duro",
    "sexo duro",
    "heeb",
    "infierno",
    "hentai",
    "el ella",
    "ho",
    "hoar",
    "hoare",
    "azada",
    "homo",
    "homoerótico",
    "cariño",
    "honky",
    "horre",
    "más caliente",
    "córneo",
    "caliente carl",
    "chica caliente",
    "sexo caliente",
    "como matar",
    "como asesinar",
    "gordo enorme",
    "follando",
    "incesto",
    "coito",
    "masturbar",
    "cebo de la cárcel",
    "jailbait",
    "japón",
    "rosquilla de gelatina",
    "hacerse una paja",
    "masturbarse",
    "jigaboo",
    "jiggerboo",
    "esperma",
    "jism",
    "juggs",
    "kawk",
    "pozo",
    "kinbaku",
    "pervertido",
    "rizado",
    "kiunt",
    "mando",
    "perillas",
    "nudoso",
    "perilla",
    "cabeza de chorlito",
    "bromista",
    "golpe",
    "kondum",
    "kondums",
    "chiflar",
    "coquetear",
    "kum",
    "kúmer",
    "kummer",
    "cumming",
    "kums",
    "kunilingus",
    "kunt",
    "kyke",
    "l3i+ch",
    "picazón",
    "labios",
    "restricción de cuero",
    "chaqueta recta de cuero",
    "fiesta de limon",
    "lesbo",
    "lesbiana",
    "lmfao",
    "lolita",
    "haciendo el amor",
    "lujuria",
    "codiciando",
    "m0f0",
    "m0fo",
    "m45terbato",
    "ma5terb8",
    "ma5terbato",
    "hazme llegar",
    "chorros masculinos",
    "masoquista",
    "maestro-bate",
    "maestrob8",
    "maestro murciélago*",
    "masterbat3",
    "masterbate",
    "masterbación",
    "masterbaciones",
    "menaje",
    "asesinato",
    "asno",
    "bola de grasa",
    "bollera",
    "cabrón",
    "caca",
    "cagada",
    "cagadón",
    "cagón",
    "chupada",
    "chupatrancas",
    "chupetón",
    "cipote",
    "concha",
    "concha de tu madre",
    "coprofagía",
    "coprófago",
    "drogas",
    "enano mental",
    "facha",
    "feminazi",
    "fiesta de salchichas",
    "follada",
    "follador",
    "gilipichis",
    "hacer una paja",
    "hediondo",
    "heroína",
    "heterito",
    "hija de la gran puta",
    "hija de la grandísima puta",
    "hija de puta",
    "hijaputa",
    "hijo de la gran puta",
    "hijo de la grandísima puta",
    "jilipollas",
    "kapullo",
    "maciza",
    "macizorra",
    "maldita",
    "mamón",
    "mariconazo",
    "martillo",
    "nazi",
    "niñata",
    "niñato",
    "orina",
    "pezón",
    "pinche",
    "pis",
    "prostituta",
    "putón",
    "racista",
    "sexo",
    "sexo oral",
    "soplagaitas",
    "soplapollas",
    "sádico",
    "tetas grandes",
    "tonto del culo",
    "tontísimo",
    "travesti",
    "trio",
    "trío",
    "tía buena",
    "vete a la mierda",
    "vete a tomar por culo",
    "vulva",
] as const;

export default words;
