/**
 * French banned words
 *
 * Sources:
 * - Curated list
 * - https://github.com/coffee-and-fun/google-profanity-words
 * - https://github.com/viddexa/safetext
 */
const words: ReadonlyArray<string> = [
    "negre",
    "negres",
    "negresse",
    "bougnoule",
    "bougnoules",
    "bicot",
    "bicots",
    "raton",
    "ratons",
    "melon",
    "melons",
    "bridé",
    "brides",
    "chinetoque",
    "niakwe",
    "youpin",
    "youpins",
    "youtre",
    "pd",
    "pede",
    "pedes",
    "tapette",
    "tapettes",
    "gouine",
    "gouines",
    "tantouse",
    "travelo",
    "travelos",
    "pute",
    "putes",
    "putain",
    "salope",
    "salopes",
    "connard",
    "connards",
    "connasse",
    "connasses",
    "enculé",
    "encule",
    "enculer",
    "baiser",
    "nique",
    "niquer",
    "niqueur",
    "fils de pute",
    "nique ta mere",
    "merde",
    "bordel",
    "foutre",
    "con",
    "conne",
    "bite",
    "bites",
    "couilles",
    "chatte",
    "chattes",
    "branleur",
    "branleurs",
    "branleuse",
    "mongol",
    "mongole",
    "debile",
    "attardé",
    "salaud",
    "chiant",
    "enfoiré",
    "casse‑toi",
    "ferme ta gueule",
    "va te faire foutre",
    "ta gueule",
    "couille",
    "couillon",
    "bâtard",
    "gros con",
    "cul",
    "trou du cul",
    "1mb3c1l3",
    "1mbec1l3",
    "1mbec1le",
    "1mbéc1l3",
    "1mbéc1le",
    "35p1ng01n",
    "35p1ngo1n",
    "35ping0in",
    "35pingoin",
    "35png0n",
    "35pngon",
    "3mm3rd3r",
    "3mm3rd3u53",
    "3mm3rd3ur",
    "3mm3rd3us3",
    "3mm@nch3",
    "3mm@nche",
    "3mm@nché",
    "3mmanch3",
    "3mmanche",
    "3mmanché",
    "3mp@f3",
    "3mp@fe",
    "3mp@fé",
    "3mp@p@0ut3",
    "3mp@p@0ute",
    "3mp@p@0uté",
    "3mp@p@out3",
    "3mp@p@oute",
    "3mp@p@outé",
    "3mpaf3",
    "3mpafe",
    "3mpafé",
    "3mpapa0ut3",
    "3mpapa0ute",
    "3mpapa0uté",
    "3mpapaout3",
    "3mpapaoute",
    "3mpapaouté",
    "3ncul3",
    "3ncul3r",
    "3ncul3ur",
    "3ncule",
    "3nculé",
    "3nf01r3",
    "3nf01re",
    "3nf01ré",
    "3nf0ir3",
    "3nf0ire",
    "3nf0iré",
    "3nf0r3",
    "3nf0re",
    "3nf0ré",
    "3nflur3",
    "3nfo1r3",
    "3nfo1re",
    "3nfo1ré",
    "3nfoir3",
    "3nfoire",
    "3nfoiré",
    "3nfor3",
    "3nfore",
    "3nforé",
    "3nv@53l1n3ur",
    "3nv@53lin3ur",
    "3nv@53ln3ur",
    "3nv@s3l1n3ur",
    "3nv@s3lin3ur",
    "3nv@s3ln3ur",
    "3nva53l1n3ur",
    "3nva53lin3ur",
    "3nva53ln3ur",
    "3nvas3l1n3ur",
    "3nvas3lin3ur",
    "3nvas3ln3ur",
    "3p@15",
    "3p@1s",
    "3p@5",
    "3p@i5",
    "3p@is",
    "3p@s",
    "3pa15",
    "3pa1s",
    "3pa5",
    "3pai5",
    "3pais",
    "3pas",
    "3sp1ng01n",
    "3sp1ngo1n",
    "3sping0in",
    "3spingoin",
    "3spng0n",
    "3spngon",
    "3tr0n",
    "3tron",
    "50tt153ux",
    "50tt15eux",
    "50tt53ux",
    "50tt5eux",
    "50tti53ux",
    "50tti5eux",
    "50u5-m3rd3",
    "50u5-merde",
    "53nt-l@-p1553",
    "53nt-l@-p553",
    "53nt-l@-pi553",
    "53nt-la-p1553",
    "53nt-la-p553",
    "53nt-la-pi553",
    "5@g0u1n",
    "5@g0uin",
    "5@g0un",
    "5@gou1n",
    "5@gouin",
    "5@goun",
    "5@l0p",
    "5@l0p3",
    "5@l0p@rd",
    "5@l0pe",
    "5@l3",
    "5@l@ud",
    "5@le",
    "5@lop",
    "5@lop3",
    "5@lop@rd",
    "5@lope",
    "5@tr0u1ll3",
    "5@tr0u1lle",
    "5@tr0uill3",
    "5@tr0uille",
    "5@tr0ull3",
    "5@tr0ulle",
    "5@trou1ll3",
    "5@trou1lle",
    "5@trouill3",
    "5@trouille",
    "5@troull3",
    "5@troulle",
    "5ag0u1n",
    "5ag0uin",
    "5ag0un",
    "5agou1n",
    "5agouin",
    "5agoun",
    "5al0p",
    "5al0p3",
    "5al0pard",
    "5al0pe",
    "5al3",
    "5alaud",
    "5ale",
    "5alop",
    "5alop3",
    "5alopard",
    "5alope",
    "5atr0u1ll3",
    "5atr0u1lle",
    "5atr0uill3",
    "5atr0uille",
    "5atr0ull3",
    "5atr0ulle",
    "5atrou1ll3",
    "5atrou1lle",
    "5atrouill3",
    "5atrouille",
    "5atroull3",
    "5atroulle",
    "5chb3b",
    "5chbeb",
    "5chl3u",
    "5chleu",
    "5chn0c",
    "5chn0ck",
    "5chn0qu3",
    "5chn0que",
    "5chnoc",
    "5chnock",
    "5chnoqu3",
    "5chnoque",
    "5ent-l@-p155e",
    "5ent-l@-p55e",
    "5ent-l@-pi55e",
    "5ent-la-p155e",
    "5ent-la-p55e",
    "5ent-la-pi55e",
    "5ott153ux",
    "5ott15eux",
    "5ott53ux",
    "5ott5eux",
    "5otti53ux",
    "5otti5eux",
    "5ou5-m3rd3",
    "5ou5-merde",
    "5t3@r1qu3",
    "5t3@riqu3",
    "5t3@rqu3",
    "5t3ar1qu3",
    "5t3ariqu3",
    "5t3arqu3",
    "5te@r1qu3",
    "5te@r1que",
    "5te@riqu3",
    "5te@rique",
    "5te@rque",
    "5tear1qu3",
    "5tear1que",
    "5teariqu3",
    "5tearique",
    "5tearqu3",
    "5tearque",
    "5té@r1qu3",
    "5té@r1que",
    "5té@riqu3",
    "5té@rique",
    "5té@rqu3",
    "5té@rque",
    "5téar1qu3",
    "5téar1que",
    "5téariqu3",
    "5téarique",
    "5téarqu3",
    "5téarque",
    "@brut",
    "@brut1",
    "@bruti",
    "@nd0u1ll3",
    "@nd0u1lle",
    "@nd0uill3",
    "@nd0uille",
    "@nd0ull3",
    "@nd0ulle",
    "@ndou1ll3",
    "@ndou1lle",
    "@ndouill3",
    "@ndouille",
    "@ndoull3",
    "@ndoulle",
    "@v0rt0n",
    "@vorton",
    "abortuaire",
    "abrut",
    "abrut1",
    "abruti",
    "acrotomophilie",
    "acré gué",
    "aller aux putes",
    "aller libérer mandela",
    "aller niquer sa mère",
    "aller se faire empapaouter",
    "aller se faire enculer",
    "aller se faire foutre",
    "aller se faire mettre",
    "allez vous faire foutre",
    "allez, va t’en",
    "ambisexuel",
    "ambosexuel",
    "amène ta mère pourque je te refasse",
    "and0u1ll3",
    "and0u1lle",
    "and0uill3",
    "and0uille",
    "and0ull3",
    "and0ulle",
    "andou1ll3",
    "andou1lle",
    "andouill3",
    "andouille",
    "andoull3",
    "andoulle",
    "angishore",
    "archifoutre",
    "argya",
    "arracher",
    "arriver comme le marquis de couille-verte",
    "asphalteuse",
    "astiquer",
    "av0rt0n",
    "avale mes couilles",
    "avale mes couilles grosse pute",
    "avoir de la chatte",
    "avoir de la merde dans les yeux",
    "avoir de la moule",
    "avoir des couilles",
    "avoir des couilles au cul",
    "avoir du cul",
    "avoir du poil au cul",
    "avoir la gueule dans le cul",
    "avoir la tête dans le cul",
    "avoir le cul bordé de médailles",
    "avoir le cul bordé de nouilles",
    "avoir le feu au cul",
    "avoir le papier qui colle aux bonbons",
    "avoir le trou du cul en chou-fleur",
    "avoir les couilles",
    "avoir les nerfs",
    "avoir les rideaux qui collent aux fenêtres",
    "avoir les yeux en trou de bite",
    "avoir les yeux en trou de pine",
    "avoir l’air con",
    "avoir plein le cul",
    "avoir un balai dans le cul",
    "avortement",
    "avortements",
    "avorteur",
    "avorton",
    "b0rd3l",
    "b0rdel",
    "b0uff0n",
    "b0ugn0ul",
    "b0ugn0ul13",
    "b0ugn0ul153r",
    "b0ugn0ul15@t10n",
    "b0ugn0ul15at10n",
    "b0ugn0ul15er",
    "b0ugn0ul1e",
    "b0ugn0ul1s3r",
    "b0ugn0ul1s@t10n",
    "b0ugn0ul1sat10n",
    "b0ugn0ul1ser",
    "b0ugn0ul3",
    "b0ugn0ul53r",
    "b0ugn0ul5@t0n",
    "b0ugn0ul5at0n",
    "b0ugn0ul5er",
    "b0ugn0ule",
    "b0ugn0uli3",
    "b0ugn0uli53r",
    "b0ugn0uli5@ti0n",
    "b0ugn0uli5ati0n",
    "b0ugn0uli5er",
    "b0ugn0ulie",
    "b0ugn0ulis3r",
    "b0ugn0ulis@ti0n",
    "b0ugn0ulisati0n",
    "b0ugn0uliser",
    "b0ugn0uls3r",
    "b0ugn0uls@t0n",
    "b0ugn0ulsat0n",
    "b0ugn0ulser",
    "b0ugr3",
    "b0ugre",
    "b0uk@k",
    "b0ukak",
    "b0un0ul",
    "b0un10ul",
    "b0uni0ul",
    "b0urd1ll3",
    "b0urd1lle",
    "b0urdill3",
    "b0urdille",
    "b0urdll3",
    "b0urdlle",
    "b0us3ux",
    "b0useux",
    "b1@tch",
    "b1atch",
    "b1c0t",
    "b1cot",
    "b1t3",
    "b1t3mb015",
    "b1t3mb01s",
    "b1t3mbo15",
    "b1t3mbo1s",
    "b1te",
    "b1temb015",
    "b1temb01s",
    "b1tembo15",
    "b1tembo1s",
    "b3@uf",
    "b3auf",
    "b@t@rd",
    "b@tch",
    "bachie coupe",
    "bagouse",
    "baisable",
    "baise",
    "baise moi",
    "baise moi mor",
    "baise tes mort les suceur de bite",
    "baise toi",
    "baiser comme des lapins",
    "baiser comme un lapin",
    "baiser fanny",
    "baiseur",
    "baiseur de chien",
    "baiseurs",
    "baisée",
    "balancer la sauce",
    "balayette",
    "bander",
    "bander comme un cerf",
    "bander comme un taureau",
    "bander comme un turc",
    "bander comme un âne",
    "baptême",
    "bar à putes",
    "barabbas",
    "bat",
    "batch",
    "batte",
    "bc0t",
    "bcot",
    "be@uf",
    "beau cave",
    "beauf",
    "benzer",
    "berlingue",
    "bestialité",
    "bi@tch",
    "bibite",
    "bic0t",
    "biffle",
    "biffler",
    "bifle",
    "bifler",
    "bigornette",
    "bique",
    "bise",
    "bit3",
    "bit3mb0i5",
    "bit3mb0is",
    "bit3mboi5",
    "bit3mbois",
    "bitemb0i5",
    "bitemb0is",
    "bitemboi5",
    "bitembois",
    "bitte",
    "bivouaquer dans la crevasse",
    "biétaze",
    "bloblos",
    "bolosser",
    "bombe atomique",
    "bon ariens",
    "bon coup",
    "bon sang",
    "bonasse",
    "bondance",
    "bonnasse",
    "bonne",
    "bonyeu",
    "bord3l",
    "bordel de merde",
    "bordel à cul",
    "bordel à cul de pompe à merde",
    "bordel à cul pompe à merde",
    "bosnioule",
    "bosser",
    "botter le cul",
    "boucaque",
    "bouffable",
    "bouffer la chatte",
    "bouffer le cul",
    "bouffon",
    "bougnoul",
    "bougnoul13",
    "bougnoul153r",
    "bougnoul15@t1on",
    "bougnoul15at1on",
    "bougnoul15er",
    "bougnoul1e",
    "bougnoul1s3r",
    "bougnoul1s@t1on",
    "bougnoul1sat1on",
    "bougnoul1ser",
    "bougnoul3",
    "bougnoul53r",
    "bougnoul5@ton",
    "bougnoul5aton",
    "bougnoul5er",
    "bougnouli3",
    "bougnouli53r",
    "bougnouli5@tion",
    "bougnouli5ation",
    "bougnouli5er",
    "bougnoulie",
    "bougnoulis3r",
    "bougnoulis@tion",
    "bougnoulisation",
    "bougnouliser",
    "bougnouls3r",
    "bougnouls@ton",
    "bougnoulsaton",
    "bougnoulser",
    "bougr3",
    "bougre",
    "bouk@k",
    "boukak",
    "boule",
    "boun1oul",
    "bounioul",
    "bounioule",
    "bounoul",
    "bourd1ll3",
    "bourd1lle",
    "bourdill3",
    "bourdille",
    "bourdll3",
    "bourdlle",
    "bourrer le mou",
    "bourriquer",
    "bourré",
    "bourrée",
    "bous3ux",
    "bouseux",
    "bout",
    "bout crime",
    "bout de bon dieu",
    "bout de calvaire",
    "bout de crime",
    "bout de crisse",
    "bout de sacre",
    "boutons",
    "boyau cullier",
    "br153-burn35",
    "br15e-burne5",
    "br1s3-burn3s",
    "br1se-burnes",
    "br53-burn35",
    "br5e-burne5",
    "br@nl3r",
    "br@nl3ur",
    "br@nler",
    "br@nleur",
    "br@nqu3",
    "br@nque",
    "brackmard",
    "branl3r",
    "branl3ur",
    "branlage",
    "branle-couille",
    "branler",
    "branler le mammouth",
    "branlette",
    "branlette espagnole",
    "branlette intellectuelle",
    "branleur de chiens morts",
    "branlo",
    "branlotter",
    "branlée",
    "branqu3",
    "branque",
    "bri53-burn35",
    "bri5e-burne5",
    "bride",
    "bris3-burn3s",
    "brise-burnes",
    "briser les noix",
    "broutage",
    "broute-minou",
    "brouter",
    "brouter le cresson",
    "brouter le gazon",
    "brouter les couilles",
    "brouteur",
    "brouteuse",
    "broutte-minou",
    "brs3-burn3s",
    "brse-burnes",
    "brã»le en enfer",
    "brêle",
    "brûle en enfer",
    "brûle en l'enfer",
    "bt3",
    "bt3mb05",
    "bt3mb0s",
    "bt3mbo5",
    "bt3mbos",
    "bte",
    "btemb05",
    "btemb0s",
    "btembo5",
    "btembos",
    "bushed",
    "bât@rd",
    "bâtard, tu vas me le payer",
    "bâtarde",
    "bâton",
    "c'est des conneries",
    "c'est plate",
    "c'est quoi ce bordel",
    "c'est vraiment de ta faute",
    "c0ch3",
    "c0che",
    "c0n",
    "c0n5",
    "c0n@553",
    "c0n@55e",
    "c0n@rd",
    "c0n@ss3",
    "c0n@sse",
    "c0na553",
    "c0na55e",
    "c0nard",
    "c0nass3",
    "c0nasse",
    "c0nch13r",
    "c0nch1er",
    "c0nch3r",
    "c0ncher",
    "c0nchi3r",
    "c0nchier",
    "c0nn3",
    "c0nn@553",
    "c0nn@55e",
    "c0nn@rd",
    "c0nn@rd3",
    "c0nn@rde",
    "c0nn@ss3",
    "c0nn@sse",
    "c0nna553",
    "c0nna55e",
    "c0nnard",
    "c0nnard3",
    "c0nnarde",
    "c0nnass3",
    "c0nnasse",
    "c0nne",
    "c0ns",
    "c0u1ll0n",
    "c0u1ll0nn3r",
    "c0u1ll3",
    "c0u1ll3s",
    "c0uill0n",
    "c0uill0nn3r",
    "c0uill0nner",
    "c0uill3",
    "c0uill3s",
    "c0uille",
    "c0uilles",
    "c0un1fl3",
    "c0un1fle",
    "c0unfl3",
    "c0unfle",
    "c0unifl3",
    "c0unifle",
    "c0urt@ud",
    "c0urtaud",
    "c@553-b0nb0n",
    "c@553-bonbon",
    "c@553-c0u1ll3",
    "c@553-c0u1ll35",
    "c@553-c0uill3",
    "c@553-c0uill35",
    "c@553-c0ull3",
    "c@553-c0ull35",
    "c@553-cou1ll3",
    "c@553-cou1ll35",
    "c@553-couill3",
    "c@553-couill35",
    "c@553-coull3",
    "c@553-coull35",
    "c@55e-b0nb0n",
    "c@55e-bonbon",
    "c@55e-c0u1lle",
    "c@55e-c0u1lle5",
    "c@55e-c0uille",
    "c@55e-c0uille5",
    "c@55e-c0ulle",
    "c@55e-c0ulle5",
    "c@55e-cou1lle",
    "c@55e-cou1lle5",
    "c@55e-couille",
    "c@55e-couille5",
    "c@55e-coulle",
    "c@55e-coulle5",
    "c@c0u",
    "c@cou",
    "c@fr3",
    "c@fre",
    "c@ld0ch3",
    "c@ld0che",
    "c@ldoch3",
    "c@ldoche",
    "c@ss3-b0nb0n",
    "c@ss3-bonbon",
    "c@ss3-c0u1ll3",
    "c@ss3-c0u1ll3s",
    "c@ss3-c0uill3",
    "c@ss3-c0uill3s",
    "c@ss3-c0ull3",
    "c@ss3-c0ull3s",
    "c@ss3-cou1ll3",
    "c@ss3-cou1ll3s",
    "c@ss3-couill3",
    "c@ss3-couill3s",
    "c@ss3-coull3",
    "c@ss3-coull3s",
    "c@sse-b0nb0n",
    "c@sse-bonbon",
    "c@sse-c0u1lle",
    "c@sse-c0u1lles",
    "c@sse-c0uille",
    "c@sse-c0uilles",
    "c@sse-c0ulle",
    "c@sse-c0ulles",
    "c@sse-cou1lle",
    "c@sse-cou1lles",
    "c@sse-couille",
    "c@sse-couilles",
    "c@sse-coulle",
    "c@sse-coulles",
    "ca fait chier",
    "ca me fait chier",
    "ca suce gros temps",
    "ca553-b0nb0n",
    "ca553-bonbon",
    "ca553-c0u1ll3",
    "ca553-c0u1ll35",
    "ca553-c0uill3",
    "ca553-c0uill35",
    "ca553-c0ull3",
    "ca553-c0ull35",
    "ca553-cou1ll3",
    "ca553-cou1ll35",
    "ca553-couill3",
    "ca553-couill35",
    "ca553-coull3",
    "ca553-coull35",
    "ca55e-b0nb0n",
    "ca55e-bonbon",
    "ca55e-c0u1lle",
    "ca55e-c0u1lle5",
    "ca55e-c0uille",
    "ca55e-c0uille5",
    "ca55e-c0ulle",
    "ca55e-c0ulle5",
    "ca55e-cou1lle",
    "ca55e-cou1lle5",
    "ca55e-couille",
    "ca55e-couille5",
    "ca55e-coulle",
    "ca55e-coulle5",
    "cac0u",
    "cacou",
    "cafr3",
    "cafre",
    "cagasse",
    "cagoince",
    "cahba",
    "cailler",
    "cald0ch3",
    "cald0che",
    "caldoch3",
    "caldoche",
    "calice",
    "calisse",
    "calvaire",
    "calvâsse",
    "carrer dans l’oignon",
    "carte de france",
    "cass3-b0nb0n",
    "cass3-bonbon",
    "cass3-c0u1ll3",
    "cass3-c0u1ll3s",
    "cass3-c0uill3",
    "cass3-c0uill3s",
    "cass3-c0ull3",
    "cass3-c0ull3s",
    "cass3-cou1ll3",
    "cass3-cou1ll3s",
    "cass3-couill3",
    "cass3-couill3s",
    "cass3-coull3",
    "cass3-coull3s",
    "casse toi",
    "casse-b0nb0n",
    "casse-bonbon",
    "casse-burette",
    "casse-c0u1lle",
    "casse-c0u1lles",
    "casse-c0uille",
    "casse-c0uilles",
    "casse-c0ulle",
    "casse-c0ulles",
    "casse-cou1lle",
    "casse-cou1lles",
    "casse-couille",
    "casse-couilles",
    "casse-coulle",
    "casse-coulles",
    "casse-toi",
    "casse-toi pauvre con",
    "casse-toi, idiot",
    "casse-toi, idiote",
    "casser la gueule",
    "casser le pot",
    "casser les boules",
    "casser les burnes",
    "casser les couilles",
    "cave",
    "ce putain d’embouteillage",
    "ce putain d’ordinateur",
    "cela me soûle",
    "cerise",
    "cervelle d'oiseau",
    "cervelle de moineau",
    "ch'te harra l'chu",
    "ch13nn@553",
    "ch13nn@ss3",
    "ch13nna553",
    "ch13nnass3",
    "ch13r",
    "ch13ur",
    "ch13urs",
    "ch1enn@55e",
    "ch1enn@sse",
    "ch1enna55e",
    "ch1ennasse",
    "ch1er",
    "ch1eur",
    "ch1eurs",
    "ch1n3t0c",
    "ch1n3t0qu3",
    "ch1n3toc",
    "ch1n3toqu3",
    "ch1net0c",
    "ch1net0que",
    "ch1netoc",
    "ch1netoque",
    "ch1nt0k",
    "ch1ntok",
    "ch3nn@553",
    "ch3nn@ss3",
    "ch3nna553",
    "ch3nnass3",
    "ch3r",
    "ch@ch@r",
    "ch@g@553",
    "ch@g@55e",
    "ch@g@ss3",
    "ch@g@sse",
    "ch@uff@rd",
    "chachar",
    "chacun sa merde",
    "chaga553",
    "chaga55e",
    "chagass3",
    "chagasse",
    "chagatte",
    "chalice",
    "charmouta",
    "chat",
    "chat bite",
    "chat-bite",
    "chaude-pisse",
    "chauffard",
    "chenn@55e",
    "chenn@sse",
    "chenna55e",
    "chennasse",
    "cher",
    "cherche-merde",
    "chette",
    "chi3nn@553",
    "chi3nn@ss3",
    "chi3nna553",
    "chi3nnass3",
    "chi3r",
    "chi3ur",
    "chi3urs",
    "chiant comme la lune",
    "chiante",
    "chiasse",
    "chiasser",
    "chiatique",
    "chibre",
    "chien sale",
    "chienn@55e",
    "chienn@sse",
    "chienna55e",
    "chiennasse",
    "chienne",
    "chiennerie",
    "chiennes",
    "chier comme tout le monde",
    "chier dans les bottes",
    "chier dans son froc",
    "chier pour la marine",
    "chier une pendule",
    "chierie",
    "chieur",
    "chieurs",
    "chieuse",
    "chin3t0c",
    "chin3t0qu3",
    "chin3toc",
    "chin3toqu3",
    "chinet0c",
    "chinet0que",
    "chinetoc",
    "chint0k",
    "chintok",
    "chiottes",
    "chiseler",
    "chié",
    "chiée",
    "chl3uh",
    "chleuh",
    "chn0qu3",
    "chn0que",
    "chn3t0c",
    "chn3t0qu3",
    "chn3toc",
    "chn3toqu3",
    "chnet0c",
    "chnet0que",
    "chnetoc",
    "chnetoque",
    "chnoqu3",
    "chnoque",
    "chnt0k",
    "chntok",
    "choleque de merde",
    "choper",
    "choune",
    "chrisse qui pisse",
    "christ",
    "christer",
    "château de marde",
    "ciboire",
    "cibolle",
    "ciboulette de marde",
    "cibouã¨re",
    "cinclème",
    "claque merde",
    "claque-merde",
    "clille",
    "clito",
    "clochard",
    "coch3",
    "coche",
    "cochonneries",
    "coin",
    "coliss",
    "comme papa dans maman",
    "comme un chien fout sa merde",
    "con comme un balai",
    "con comme un gland",
    "con comme une bite",
    "con5",
    "con@553",
    "con@55e",
    "con@rd",
    "con@ss3",
    "con@sse",
    "cona553",
    "cona55e",
    "conard",
    "conass3",
    "conasse",
    "conch13r",
    "conch1er",
    "conch3r",
    "concher",
    "conchi3r",
    "conchier",
    "conn3",
    "conn@553",
    "conn@55e",
    "conn@rd",
    "conn@rd3",
    "conn@rde",
    "conn@ss3",
    "conn@sse",
    "conna553",
    "conna55e",
    "connard3",
    "connarde",
    "connass3",
    "conneau",
    "conneries",
    "cons",
    "contrecrisser",
    "convoitise",
    "copain de baise",
    "copine de baise",
    "coq",
    "coqs",
    "coquillard",
    "corné",
    "cou1lle",
    "cou1lles",
    "cou1llon",
    "cou1llonner",
    "couill3",
    "couill3s",
    "couille de loup",
    "couille molle",
    "couilles au poteau",
    "couillonn3r",
    "couillonne",
    "couillonner",
    "couillu",
    "coun1fl3",
    "coun1fle",
    "counfl3",
    "counfle",
    "counifl3",
    "counifle",
    "coup de pute",
    "courageux",
    "court@ud",
    "courtaud",
    "couter la peau des couilles",
    "couter la peau du cul",
    "coûter la peau des couilles",
    "coûter la peau du cul",
    "coûter une couille",
    "cr0tt3",
    "cr0tte",
    "cr0tté",
    "cr0u1ll3",
    "cr0u1ll@t",
    "cr0u1llat",
    "cr0u1lle",
    "cr0uill3",
    "cr0uill@t",
    "cr0uillat",
    "cr0uille",
    "cr0ull3",
    "cr0ull@t",
    "cr0ullat",
    "cr0ulle",
    "cr0ût0n",
    "cr1cr1",
    "cr3t1n",
    "cr3tin",
    "cr3tn",
    "cr3v@rd",
    "cr3vard",
    "cr3vur3",
    "cramouille",
    "cran",
    "craquer son slip",
    "craquer son string",
    "cravacher le pur-sang",
    "crcr",
    "cret1n",
    "cretn",
    "crev@rd",
    "crevard",
    "crevure",
    "cricri",
    "criffe",
    "crime",
    "criss",
    "criss de fif",
    "crisse",
    "crisse de cave",
    "crisse de câlice de tabarnak d'esti de sacrament",
    "crisse de tabernak",
    "crisse qu'y est bon",
    "crisse qu’y fait frette",
    "crissement",
    "crisser",
    "crock la merde",
    "crosse",
    "crosser",
    "crosseur",
    "crott3",
    "crotté",
    "crou1ll3",
    "crou1ll@t",
    "crou1llat",
    "crou1lle",
    "crouill3",
    "crouill@t",
    "crouillat",
    "crouille",
    "croull3",
    "croull@t",
    "croullat",
    "croulle",
    "croupe",
    "croûton",
    "cruchasse",
    "crucifix",
    "crève la gueule ouverte",
    "cré",
    "cré maudit",
    "cré tornon",
    "crét1n",
    "crétin",
    "crétn",
    "culasse",
    "culbuter",
    "culer",
    "culeter",
    "culeur",
    "culeurs",
    "culs",
    "culé",
    "culée",
    "câliboire",
    "câlice",
    "câlisse",
    "câlisse que j’en ai marre",
    "câlisser",
    "céoène",
    "c’est chiant",
    "c’est de la couille de loup",
    "c’est des conneries",
    "c’est le bordel ici",
    "c’est naze",
    "c’est quoi ce bordel",
    "c’est un ciboire de char",
    "c’est un vrai connard",
    "c’est vraiment de ta faute",
    "c’t’un cristié bon gateau",
    "d3b1l3",
    "d3bil3",
    "d3bl3",
    "d3gu3l@ss3",
    "d3gu3lass3",
    "d3m3rd3r",
    "damné",
    "dans ton cul",
    "de mes couilles",
    "de mes deux",
    "de mon vier",
    "deb1l3",
    "deb1le",
    "debil3",
    "debl3",
    "deble",
    "decaliss",
    "deguelasse",
    "demerder",
    "demi-molle",
    "des balles",
    "des couilles",
    "diarrhée",
    "digue",
    "dilater",
    "dinde",
    "djoc",
    "does",
    "doeser",
    "doigter",
    "dr0u1ll3",
    "dr0u1lle",
    "dr0uill3",
    "dr0uille",
    "dr0ull3",
    "dr0ulle",
    "drague",
    "drisser",
    "drou1ll3",
    "drou1lle",
    "drouill3",
    "drouille",
    "droull3",
    "droulle",
    "du schn0c",
    "du schnoc",
    "du5chn0ck",
    "du5chnock",
    "duc0n",
    "duc0nn0t",
    "duché",
    "ducon",
    "duconnot",
    "dug3n0ux",
    "dug3noux",
    "dugen0ux",
    "dugenoux",
    "dugl@nd",
    "dugland",
    "duschn0ck",
    "duschnock",
    "déb1l3",
    "déb1le",
    "débagouler",
    "débander",
    "débil3",
    "débile",
    "débl3",
    "déble",
    "déboiter",
    "débroussailler la tranchée",
    "décharger",
    "déconnade",
    "déconnage",
    "déconne",
    "déconner",
    "décrisser",
    "déculer",
    "décâlisser",
    "défoncer",
    "défonceur",
    "défourailler",
    "dégage",
    "dégage, j’essaie de travailler",
    "dégager",
    "déglinguer",
    "déguel@sse",
    "déguelasse",
    "dégueulasse",
    "dégueulassement",
    "dégénéré",
    "démerde yourself",
    "démerder",
    "démonter",
    "dépucelage",
    "dépuceler",
    "dérouler du câble",
    "désengorger",
    "e5p1ng01n",
    "e5p1ngo1n",
    "e5ping0in",
    "e5pingoin",
    "e5png0n",
    "e5pngon",
    "emballeur de fudge",
    "emm@nche",
    "emm@nché",
    "emmanche",
    "emmancher",
    "emmanché",
    "emmerdant",
    "emmerder",
    "emmerdeu5e",
    "emmerdeur",
    "emmerdeuse",
    "emmerdé",
    "emp@fe",
    "emp@fé",
    "emp@p@0ute",
    "emp@p@0uté",
    "emp@p@oute",
    "emp@p@outé",
    "empafe",
    "empafé",
    "empapa0ute",
    "empapa0uté",
    "empapaoutage",
    "empapaoute",
    "empapaouté",
    "en avoir deux",
    "en avoir plein le cul",
    "en avoir plein les couilles",
    "en avoir ras les burnes",
    "en chier",
    "enconnade",
    "enconner",
    "encuguler",
    "enculable",
    "enculade",
    "enculade de mouche",
    "enculagailler",
    "enculage",
    "enculage de mouche",
    "enculage de mouches",
    "enculailleur",
    "enculatoire",
    "enculement",
    "enculer les mouches",
    "enculer une mouche",
    "enculerie",
    "enculette",
    "enculeur",
    "enculeur de mouches",
    "enculeurs",
    "enculeuse",
    "enculã© de mes deux",
    "enculé de ta mère",
    "enculé de ta race",
    "enculé toi salaud",
    "enculée",
    "enf01re",
    "enf01ré",
    "enf0ire",
    "enf0iré",
    "enf0re",
    "enf0ré",
    "enfant de chienne",
    "enfant de putain",
    "enfant de pute",
    "enfer",
    "enfiler",
    "enfler",
    "enfo1re",
    "enfo1ré",
    "enfoirer",
    "enfoirée",
    "enfore",
    "enforé",
    "enfourailler",
    "enfoutrer",
    "englander",
    "engrosser",
    "engueuler",
    "entre couilles",
    "entuber",
    "env@5el1neur",
    "env@5elineur",
    "env@5elneur",
    "env@sel1neur",
    "env@selineur",
    "env@selneur",
    "enva5el1neur",
    "enva5elineur",
    "enva5elneur",
    "envasel1neur",
    "envaselineur",
    "envaselneur",
    "envoyer",
    "envoyer chier",
    "envulver",
    "ep@15",
    "ep@1s",
    "ep@5",
    "ep@i5",
    "ep@is",
    "ep@s",
    "epa15",
    "epa1s",
    "epa5",
    "epai5",
    "epais",
    "epas",
    "esp1ng01n",
    "esp1ngo1n",
    "espacer",
    "esping0in",
    "espingoin",
    "espng0n",
    "espngon",
    "esprit",
    "esque",
    "esti",
    "esti d'laid",
    "esti d'mal propre.",
    "esti d'épais à marde",
    "esti de calisse de tabarnak",
    "esti de cave",
    "esti de câlice de tabarnak",
    "esti de marde",
    "esti que t'es laid.",
    "estie",
    "et mon cul, c’est du poulet",
    "et ta connerie",
    "etr0n",
    "etron",
    "eucharistie",
    "exploser",
    "exploser le terrier",
    "f0tt3",
    "f0tte",
    "f0ut3ur",
    "f0uteur",
    "f0utr3",
    "f0utre",
    "f10tt3",
    "f10tte",
    "f1ott3",
    "f1otte",
    "f31gn@ss3",
    "f3ign@ss3",
    "f3ignass3",
    "face de cul",
    "face de pet",
    "face de t'chu",
    "faciale",
    "faire",
    "faire chier",
    "faire chier la bite",
    "faire crapahuter le flemmard",
    "faire enculer",
    "faire foutre",
    "faire minette",
    "faire sa pute",
    "faire sprinter l’unijambiste",
    "faire un caca nerveux",
    "fais chier",
    "fais chier la bite",
    "fais chier.",
    "fait moi jouir",
    "fall down fuck in the ass",
    "fan de putain",
    "fant de pute",
    "farme ta yeule",
    "fartmonger",
    "fartmuppet",
    "fdp",
    "fe1gnasse",
    "feign@sse",
    "feignasse",
    "fellation",
    "fente",
    "ferme ta putain de gueule, connard",
    "fermer sa gueule",
    "fermer son claque merde",
    "fermer son claque-merde",
    "fesse",
    "fi0tt3",
    "fi0tte",
    "fiche moi le paix",
    "fif",
    "fifi",
    "fille de pute",
    "fille à pédés",
    "film de boule",
    "film de boules",
    "film de cul",
    "fils de bâtard",
    "fils de chien",
    "fils de chienne",
    "fils de garce",
    "fils de putain",
    "fils de salope",
    "fils de ta race",
    "fils-de-puterie",
    "filsdeputerie",
    "fion",
    "fiott3",
    "fiotte",
    "flaming fartmonger",
    "flûte",
    "foirade",
    "foiré",
    "foirée",
    "folle",
    "forme woire ta geule",
    "fott3",
    "fotte",
    "foufoune",
    "foufounette",
    "fouille-merde",
    "foune",
    "fourbir",
    "foure toi les dans l'chu",
    "fourrer",
    "fous le camp",
    "fous le camps",
    "fous le camps et morte",
    "fout3ur",
    "foutage de gueule",
    "fouteur",
    "fouteur de merde",
    "foutoir",
    "foutr3",
    "foutre en l’air",
    "foutre la merde",
    "foutre la paix",
    "foutre le bordel",
    "foutre le camp",
    "foutre sur la gueule",
    "foutriquer",
    "fr1tz",
    "framble",
    "frambler",
    "fripe moi l'chu",
    "frippe mes balles",
    "fritz",
    "frtz",
    "fuck me boots",
    "fum13r",
    "fum1er",
    "fum3r",
    "fumer",
    "fumi3r",
    "fumier",
    "fétiche",
    "g0d0n",
    "g0g0l",
    "g0u1ll@nd",
    "g0u1lland",
    "g0u1n3",
    "g0u1ne",
    "g0uill@nd",
    "g0uilland",
    "g0uin3",
    "g0uine",
    "g0ull@nd",
    "g0ulland",
    "g0un3",
    "g0une",
    "g0urd3",
    "g0urde",
    "g0urg@nd1n3",
    "g0urg@nd1ne",
    "g0urg@ndin3",
    "g0urg@ndine",
    "g0urg@ndn3",
    "g0urg@ndne",
    "g0urgand1n3",
    "g0urgand1ne",
    "g0urgandin3",
    "g0urgandine",
    "g0urgandn3",
    "g0urgandne",
    "g0ï",
    "g@rc3",
    "g@rce",
    "g@up3",
    "g@upe",
    "garage à bite",
    "garage à bites",
    "garc3",
    "garce",
    "gaup3",
    "gaupe",
    "gdm",
    "gerbe",
    "gerber",
    "gl@nd",
    "gl@nd0u1ll0u",
    "gl@nd0uill0u",
    "gl@nd0ull0u",
    "gl@nd3u53",
    "gl@nd3ur",
    "gl@nd3us3",
    "gl@ndeu5e",
    "gl@ndeur",
    "gl@ndeuse",
    "gl@ndou1llou",
    "gl@ndouillou",
    "gl@ndoullou",
    "gl@ndu",
    "gland",
    "gland0u1ll0u",
    "gland0uill0u",
    "gland0ull0u",
    "gland3u53",
    "gland3ur",
    "gland3us3",
    "glandeu5e",
    "glandeur",
    "glandeuse",
    "glandou1llou",
    "glandouillou",
    "glandoullou",
    "glandu",
    "glaoui",
    "glisser",
    "gn0ul",
    "gn0ul3",
    "gn0ule",
    "gnasse",
    "gniouf",
    "gnoul",
    "gnoul3",
    "gnoule",
    "godemiché",
    "godes",
    "godon",
    "gogol",
    "goo guzzler",
    "goof",
    "gorby",
    "gosse",
    "gou1ll@nd",
    "gou1lland",
    "gou1n3",
    "gou1ne",
    "gougnote",
    "gougnoter",
    "gouill@nd",
    "gouilland",
    "gouin3",
    "goull@nd",
    "goulland",
    "goun3",
    "goune",
    "gourd3",
    "gourde",
    "gourdin",
    "gourg@nd1n3",
    "gourg@nd1ne",
    "gourg@ndin3",
    "gourg@ndine",
    "gourg@ndn3",
    "gourg@ndne",
    "gourgand1n3",
    "gourgand1ne",
    "gourgandin3",
    "gourgandine",
    "gourgandn3",
    "gourgandne",
    "gousse",
    "goï",
    "gr0gn@553",
    "gr0gn@55e",
    "gr0gn@ss3",
    "gr0gn@sse",
    "gr0gna553",
    "gr0gna55e",
    "gr0gnass3",
    "gr0gnasse",
    "graine",
    "grande folle",
    "grogn@553",
    "grogn@55e",
    "grogn@ss3",
    "grogn@sse",
    "grogna553",
    "grogna55e",
    "grognass3",
    "grognasse",
    "grogniasse",
    "gros",
    "gros colon",
    "gros cul",
    "gros ecoeurant",
    "gros tas",
    "gross cul",
    "grosse crisse de vache",
    "grosse dose",
    "grosse noune",
    "grouille",
    "gu1nd0ul3",
    "gu1nd0ule",
    "gu1ndoul3",
    "gu1ndoule",
    "gu3n1ch3",
    "gu3nch3",
    "gu3nich3",
    "guen1che",
    "guenche",
    "gueniche",
    "guenon",
    "gueule",
    "gueuler",
    "guind0ul3",
    "guind0ule",
    "guindoul3",
    "guindoule",
    "gund0ul3",
    "gund0ule",
    "gundoul3",
    "gundoule",
    "hirondelle",
    "hostie",
    "hébéphile",
    "hébéphiles",
    "hébéphilie",
    "idiote",
    "il est stupide",
    "il fait chaud ici, enculé",
    "il fait une putain de chaleur",
    "il me fait chier",
    "imb3cil3",
    "imbaisable",
    "imbecil3",
    "imbecile",
    "imbitabilité",
    "imbitable",
    "imbécil3",
    "imbécile",
    "inceste",
    "incestueux",
    "internet de marde",
    "j'ai baisã© ta mã¨re",
    "j'ai envie de chier",
    "j'en ai marre",
    "j'en ai plus rien à foutre",
    "j'en ai ral le bol",
    "j'en ai ral le cul",
    "j'en ai rien à cirer",
    "j'en ai rien à foutre",
    "j'en ai rien ã branler",
    "j'en ai rien ã foutre",
    "j'foure ta mere",
    "j'm'en calice",
    "j'm'en calice des politiciens",
    "j'va te harrer la face",
    "j3@n-f0utr3",
    "j3@n-foutr3",
    "j3an-f0utr3",
    "j3an-foutr3",
    "jante",
    "je chiee dans le chatte de ta mere",
    "je m'en bat les couilles",
    "je m'en fiche",
    "je m'en fou",
    "je m'en fous",
    "je m'en sacre",
    "je me fais chier",
    "je me fais chier ici",
    "je me fais chier.",
    "je me gode",
    "je m’emmerde",
    "je m’en bats les couilles",
    "je m’en crisse s’il fait froid, je vais quand même aller skier",
    "je m’en fiche",
    "je m’en fou",
    "je m’en fous",
    "je peux sentir ta chatte",
    "je peux violer tu.",
    "je pis dans ta bouche",
    "je suis tanné en cimoinak",
    "je t'emmerde",
    "je t'encule",
    "je te déteste",
    "je te nique ta race",
    "je te nique ta race sale fils de chien",
    "je vais niquer ta cerevelle.",
    "je vais te baiser.",
    "je veux faire l'amour avec toi",
    "je veux faire l’amour avec toi",
    "je veux t'enculer",
    "je veux violer t.",
    "je viole tu",
    "je@n-f0utre",
    "je@n-foutre",
    "jean-f0utre",
    "jean-foutre",
    "joual vert",
    "joualvert",
    "jouir",
    "journalope",
    "jériboire",
    "jésus de plâtre",
    "j’ai baisé ta mère",
    "j’ai envie de chier",
    "j’en ai eu de la bouffe en tabarnac",
    "j’en ai marre",
    "j’en ai plus rien à foutre",
    "j’en ai ral le bol",
    "j’en ai ral le cul",
    "j’en ai ras le bol",
    "j’en ai rien à cirer",
    "k1k00",
    "k1k0u",
    "k1koo",
    "k1kou",
    "keener",
    "kik00",
    "kik0u",
    "kikoo",
    "kikou",
    "kk00",
    "kk0u",
    "kkoo",
    "kkou",
    "kr@ut",
    "l'ambisexualité",
    "l0p3tt3",
    "l0pette",
    "l@ch3ux",
    "l@cheux",
    "l@v3tt3",
    "l@vette",
    "la chatte",
    "la conversation qu’on a eue m’a mis en beau calvaire",
    "la meme chose a toi",
    "la putain de ta mère",
    "la putain de ta race",
    "la vache",
    "lach3ux",
    "lache-moi la grappe",
    "lacheux",
    "laisse-moi tranquille",
    "laisser pisser le mérinos",
    "langue de pute",
    "latter",
    "lav3tt3",
    "lavette",
    "le ciel et si bleu en ostie",
    "le con",
    "le con de sa mère",
    "leche ma chat",
    "les lèvres",
    "les seins",
    "lesbienne",
    "libérer mandela",
    "limer",
    "lop3tt3",
    "lopette",
    "luxure",
    "lynchage",
    "lyncher",
    "là, je suis vraiment en tabarnac",
    "lâch3ux",
    "lâcheux",
    "lèche-cul",
    "lécher le cul",
    "l’avoir dans le cul",
    "m01n5-qu3-r13n",
    "m01n5-que-r1en",
    "m01n@1ll3",
    "m01n@1lle",
    "m01na1ll3",
    "m01na1lle",
    "m01ns-qu3-r13n",
    "m01ns-que-r1en",
    "m0in5-qu3-ri3n",
    "m0in5-que-rien",
    "m0in@ill3",
    "m0in@ille",
    "m0inaill3",
    "m0inaille",
    "m0ins-qu3-ri3n",
    "m0ins-que-rien",
    "m0n5-qu3-r3n",
    "m0n5-que-ren",
    "m0n@c@1ll3",
    "m0n@c@1lle",
    "m0n@c@ill3",
    "m0n@c@ille",
    "m0n@c@ll3",
    "m0n@c@lle",
    "m0n@ll3",
    "m0n@lle",
    "m0naca1ll3",
    "m0naca1lle",
    "m0nacaill3",
    "m0nacaille",
    "m0nacall3",
    "m0nacalle",
    "m0nall3",
    "m0nalle",
    "m0ns-qu3-r3n",
    "m0ns-que-ren",
    "m0r1c@ud",
    "m0r1caud",
    "m0rc@ud",
    "m0rcaud",
    "m0ric@ud",
    "m0ricaud",
    "m153r@bl3",
    "m153rabl3",
    "m15er@bl3",
    "m15er@ble",
    "m15erabl3",
    "m15erable",
    "m15ér@bl3",
    "m15ér@ble",
    "m15érabl3",
    "m15érable",
    "m1cht0",
    "m1chto",
    "m1n@bl3",
    "m1n@ble",
    "m1nabl3",
    "m1nable",
    "m1nu5",
    "m1nus",
    "m1s3r@bl3",
    "m1s3rabl3",
    "m1ser@bl3",
    "m1ser@ble",
    "m1serabl3",
    "m1serable",
    "m1sér@bl3",
    "m1sér@ble",
    "m1sérabl3",
    "m1sérable",
    "m3rd0u1ll@rd",
    "m3rd0u1llard",
    "m3rd0uill@rd",
    "m3rd0uillard",
    "m3rd0ull@rd",
    "m3rd0ullard",
    "m3rd3",
    "m3rd3ux",
    "m3rd@1ll0n",
    "m3rd@1ll3",
    "m3rd@1llon",
    "m3rd@ill0n",
    "m3rd@ill3",
    "m3rd@illon",
    "m3rd@ll0n",
    "m3rd@ll3",
    "m3rd@llon",
    "m3rda1ll0n",
    "m3rda1ll3",
    "m3rda1llon",
    "m3rdaill0n",
    "m3rdaill3",
    "m3rdaillon",
    "m3rdall0n",
    "m3rdall3",
    "m3rdallon",
    "m3rdou1ll@rd",
    "m3rdou1llard",
    "m3rdouill@rd",
    "m3rdouillard",
    "m3rdoull@rd",
    "m3rdoullard",
    "m53r@bl3",
    "m53rabl3",
    "m5er@ble",
    "m5erabl3",
    "m5erable",
    "m5ér@bl3",
    "m5ér@ble",
    "m5érabl3",
    "m5érable",
    "m@g0t",
    "m@got",
    "m@k0um3",
    "m@k0ume",
    "m@k0umé",
    "m@koum3",
    "m@koume",
    "m@koumé",
    "m@nch3",
    "m@nche",
    "m@ng3-m3rd3",
    "m@nge-merde",
    "m@rch@nd0t",
    "m@rch@ndot",
    "m@rg0u1ll15t3",
    "m@rg0u1ll15te",
    "m@rg0u1ll1st3",
    "m@rg0u1ll1ste",
    "m@rg0uilli5t3",
    "m@rg0uilli5te",
    "m@rg0uillist3",
    "m@rg0uilliste",
    "m@rg0ull5t3",
    "m@rg0ull5te",
    "m@rg0ullst3",
    "m@rg0ullste",
    "m@rgou1ll15t3",
    "m@rgou1ll15te",
    "m@rgou1ll1st3",
    "m@rgou1ll1ste",
    "m@rgouilli5t3",
    "m@rgouilli5te",
    "m@rgouillist3",
    "m@rgouilliste",
    "m@rgoull5t3",
    "m@rgoull5te",
    "m@rgoullst3",
    "m@rgoullste",
    "m@uv13tt3",
    "m@uv1ette",
    "m@uv3tt3",
    "m@uvette",
    "m@uvi3tt3",
    "m@uviette",
    "ma couille",
    "mag0t",
    "magot",
    "mak0um3",
    "mak0ume",
    "mak0umé",
    "makoum3",
    "makoume",
    "makoumé",
    "mal baisée",
    "malpt",
    "mamelon",
    "mance",
    "manch3",
    "manche",
    "manche à couilles",
    "mang3-m3rd3",
    "mange d'la marde",
    "mange de la marde",
    "mange de la merde",
    "mange donc un char de marde",
    "mange la marde",
    "mange la merde",
    "mange ma bite",
    "mange ma bitte",
    "mange merde et morte",
    "mange moi",
    "mange tes grands morts",
    "mange-merde",
    "manger de la marde",
    "manger ma merde",
    "manges la merde",
    "mangeux d'marde",
    "mangeux de couilles",
    "maquerellage",
    "marchand0t",
    "marchandot",
    "marde",
    "marg0u1ll15t3",
    "marg0u1ll15te",
    "marg0u1ll1st3",
    "marg0u1ll1ste",
    "marg0uilli5t3",
    "marg0uilli5te",
    "marg0uillist3",
    "marg0uilliste",
    "marg0ull5t3",
    "marg0ull5te",
    "marg0ullst3",
    "marg0ullste",
    "margou1ll15t3",
    "margou1ll15te",
    "margou1ll1st3",
    "margou1ll1ste",
    "margouilli5t3",
    "margouilli5te",
    "margouillist3",
    "margouilliste",
    "margoull5t3",
    "margoull5te",
    "margoullst3",
    "margoullste",
    "masochiste",
    "masturber",
    "matos",
    "maudit",
    "maudit bâtard",
    "maudit calvaire",
    "maudit chaudron",
    "maudite",
    "maudite merde",
    "maudite vache",
    "maususse",
    "mautadine",
    "mautadit",
    "mauv13tt3",
    "mauv1ette",
    "mauv3tt3",
    "mauvette",
    "mauvi3tt3",
    "mauviette",
    "mazouter le pingouin",
    "mb3cl3",
    "mbecl3",
    "mbecle",
    "mbécl3",
    "mbécle",
    "mcht0",
    "mchto",
    "me sucer la bite",
    "mercon",
    "merd0u1ll@rd",
    "merd0u1llard",
    "merd0uill@rd",
    "merd0uillard",
    "merd0ull@rd",
    "merd0ullard",
    "merd@1ll0n",
    "merd@1lle",
    "merd@1llon",
    "merd@ill0n",
    "merd@ille",
    "merd@illon",
    "merd@ll0n",
    "merd@lle",
    "merd@llon",
    "merda1ll0n",
    "merda1lle",
    "merda1llon",
    "merdaill0n",
    "merdaille",
    "merdaillon",
    "merdall0n",
    "merdalle",
    "merdallon",
    "merdasse",
    "merde embulante",
    "merder",
    "merderie",
    "merdeuse",
    "merdeux",
    "merdicité",
    "merdier",
    "merdique",
    "merdogène",
    "merdou1ll@rd",
    "merdou1llard",
    "merdouill@rd",
    "merdouillard",
    "merdoull@rd",
    "merdoullard",
    "mes couilles",
    "mes couilles en toi",
    "mes couilles le temps se brouille",
    "met la dans ta bouche",
    "metteux",
    "mettre",
    "mettre dans la sauce",
    "mettre dans l’os",
    "mettre la misère",
    "mettre la quenelle dans le shaker",
    "mettre le nez de quelqu’un dans sa merde",
    "mettre ses couilles sur la table",
    "mettre sur la gueule",
    "meuf",
    "meurs, pute",
    "mi53r@bl3",
    "mi53rabl3",
    "mi5er@bl3",
    "mi5er@ble",
    "mi5erabl3",
    "mi5erable",
    "mi5ér@bl3",
    "mi5ér@ble",
    "mi5érabl3",
    "mi5érable",
    "micht0",
    "michto",
    "mijole",
    "min@bl3",
    "min@ble",
    "minabl3",
    "minable",
    "mince",
    "minou",
    "minu5",
    "minus",
    "mis3r@bl3",
    "mis3rabl3",
    "miser@bl3",
    "miser@ble",
    "miserabl3",
    "miserable",
    "misér@bl3",
    "misér@ble",
    "misérabl3",
    "misérable",
    "mn@bl3",
    "mn@ble",
    "mnabl3",
    "mnable",
    "mnu5",
    "mnus",
    "mo1n5-qu3-r13n",
    "mo1n5-que-r1en",
    "mo1n@1ll3",
    "mo1n@1lle",
    "mo1na1ll3",
    "mo1na1lle",
    "mo1ns-qu3-r13n",
    "mo1ns-que-r1en",
    "moin5-qu3-ri3n",
    "moin5-que-rien",
    "moin@ill3",
    "moin@ille",
    "moinaill3",
    "moinaille",
    "moins-qu3-ri3n",
    "moins-que-rien",
    "mollard",
    "mon calisse de chavirer",
    "mon chum est un crisse d’idiot",
    "mon cul",
    "mon dieu",
    "mon fuckin de calisse de mangeu d'graine",
    "mon fucking de calisse de mangeu d'graine",
    "mon maudit innocent",
    "mon païen",
    "mon tabarnak",
    "mon vier",
    "mon vier, madame olivier",
    "mon5-qu3-r3n",
    "mon5-que-ren",
    "mon@c@1ll3",
    "mon@c@1lle",
    "mon@c@ill3",
    "mon@c@ille",
    "mon@c@ll3",
    "mon@c@lle",
    "mon@ll3",
    "mon@lle",
    "monaca1ll3",
    "monaca1lle",
    "monacaill3",
    "monacaille",
    "monacall3",
    "monacalle",
    "monall3",
    "monalle",
    "mons-qu3-r3n",
    "mons-que-ren",
    "mor1c@ud",
    "mor1caud",
    "morc@ud",
    "morcaud",
    "morceau de merde",
    "moric@ud",
    "moricaud",
    "morue",
    "motocultable",
    "motoculter",
    "mouche à merde",
    "mouille",
    "moule",
    "moule à merde",
    "moule-bite",
    "mouron",
    "ms3r@bl3",
    "ms3rabl3",
    "mser@bl3",
    "mser@ble",
    "mserabl3",
    "mserable",
    "msér@bl3",
    "msér@ble",
    "msérabl3",
    "msérable",
    "mère enculée",
    "mésange",
    "n1@153ux",
    "n1@15eux",
    "n1@1s3ux",
    "n1@1seux",
    "n1@c",
    "n1@k0u3",
    "n1@k0ue",
    "n1@k0ué",
    "n1@kou3",
    "n1@koue",
    "n1@koué",
    "n1a153ux",
    "n1a15eux",
    "n1a1s3ux",
    "n1a1seux",
    "n1ac",
    "n1ak0u3",
    "n1ak0ue",
    "n1ak0ué",
    "n1akou3",
    "n1akoue",
    "n1akoué",
    "n1qu3",
    "n1qu3r",
    "n1que",
    "n1quer",
    "n3gr0",
    "n3gro",
    "n@53ux",
    "n@5eux",
    "n@c",
    "n@k0u3",
    "n@k0ue",
    "n@k0ué",
    "n@kou3",
    "n@koue",
    "n@koué",
    "n@s3",
    "n@s3ux",
    "n@se",
    "n@seux",
    "n@z3",
    "n@ze",
    "na53ux",
    "na5eux",
    "nac",
    "nak0u3",
    "nak0ue",
    "nak0ué",
    "nakou3",
    "nakoue",
    "nakoué",
    "nana",
    "nas3",
    "nas3ux",
    "nase",
    "naseux",
    "naz3",
    "naze",
    "ne plus se sentir pisser",
    "ne rien branler",
    "ne rien foutre",
    "negr0",
    "ni@c",
    "ni@i53ux",
    "ni@i5eux",
    "ni@is3ux",
    "ni@iseux",
    "ni@k0u3",
    "ni@k0ue",
    "ni@k0ué",
    "ni@kou3",
    "ni@koue",
    "ni@koué",
    "niac",
    "niai53ux",
    "niai5eux",
    "niais3ux",
    "niaiseuse",
    "niaiseux",
    "niak0u3",
    "niak0ue",
    "niak0ué",
    "niakou3",
    "niakoue",
    "niakoué",
    "niqu3",
    "niqu3r",
    "nique la police",
    "nique sa mère",
    "nique ta mã¨re",
    "nique ta mère",
    "nique ta mère espèce de gros bâtard de merde",
    "nique ta mère la chauve",
    "nique ta race",
    "niquer sa mère",
    "nom de dieu",
    "nom de dieu de merde",
    "noune",
    "nqu3",
    "nqu3r",
    "nque",
    "nquer",
    "ntm",
    "nul à chier",
    "nulach",
    "nulach’",
    "nymphe",
    "nymphomanie",
    "nègre",
    "nègres",
    "négr0",
    "négro",
    "néonazi",
    "n’en avoir rien à foutre",
    "oh hisse, enculé",
    "oh la vache",
    "oh putain de merde",
    "oh, merde",
    "on s’encule",
    "ordure",
    "orgasme",
    "orgasmes",
    "orgie",
    "ostensoir",
    "ostensoir à pédale",
    "osti",
    "osti d'kalisse de pourris",
    "osti de calisse de tabarnak",
    "osti de tapette",
    "osti fils de putte",
    "ostie",
    "ostie d'maillet",
    "ostie d'tarla",
    "ostie de",
    "ostie de cave",
    "ostie que je suis tanné",
    "oui ou merde",
    "ouvrir sa grande gueule",
    "p0rc@5",
    "p0rc@553",
    "p0rc@55e",
    "p0rc@s",
    "p0rc@ss3",
    "p0rc@sse",
    "p0rca5",
    "p0rca553",
    "p0rca55e",
    "p0rcas",
    "p0rcass3",
    "p0rcasse",
    "p0uc@v",
    "p0ucav",
    "p0uf",
    "p0uf1@553",
    "p0uf1@55e",
    "p0uf1@ss3",
    "p0uf1@sse",
    "p0uf1a553",
    "p0uf1a55e",
    "p0uf1ass3",
    "p0uf1asse",
    "p0uf@553",
    "p0uf@55e",
    "p0uf@ss3",
    "p0uf@sse",
    "p0ufa553",
    "p0ufa55e",
    "p0ufass3",
    "p0ufasse",
    "p0uff1@553",
    "p0uff1@55e",
    "p0uff1@ss3",
    "p0uff1@sse",
    "p0uff1a553",
    "p0uff1a55e",
    "p0uff1ass3",
    "p0uff1asse",
    "p0uff@553",
    "p0uff@55e",
    "p0uff@ss3",
    "p0uff@sse",
    "p0uffa553",
    "p0uffa55e",
    "p0uffass3",
    "p0uffasse",
    "p0uffi@553",
    "p0uffi@55e",
    "p0uffi@ss3",
    "p0uffi@sse",
    "p0uffia553",
    "p0uffia55e",
    "p0uffiass3",
    "p0uffiasse",
    "p0ufi@553",
    "p0ufi@55e",
    "p0ufi@ss3",
    "p0ufi@sse",
    "p0ufia553",
    "p0ufia55e",
    "p0ufiass3",
    "p0ufiasse",
    "p0und3",
    "p0unde",
    "p0undé",
    "p0urr1tur3",
    "p0urr1ture",
    "p0urritur3",
    "p0urriture",
    "p0urrtur3",
    "p0urrture",
    "p1550u",
    "p155ou",
    "p1gn0uf",
    "p1gnouf",
    "p1mbêch3",
    "p1mbêche",
    "p1ss0u",
    "p1ss3ux",
    "p1sseux",
    "p1ssou",
    "p3cqu3",
    "p3d0qu3",
    "p3d3",
    "p3d@l3",
    "p3dal3",
    "p3doqu3",
    "p3qu3n@ud",
    "p3qu3naud",
    "p3t",
    "p3t3ux",
    "p3t@553",
    "p3t@ss3",
    "p3ta553",
    "p3tass3",
    "p550u",
    "p55ou",
    "p@k05",
    "p@k0s",
    "p@ko5",
    "p@kos",
    "p@n0ufl3",
    "p@n0ufle",
    "p@noufl3",
    "p@noufle",
    "p@t@r1n",
    "p@t@rin",
    "p@t@rn",
    "pachole",
    "pak05",
    "pak0s",
    "pako5",
    "pakos",
    "palucher",
    "pan0ufl3",
    "pan0ufle",
    "panier",
    "panoufl3",
    "panoufle",
    "pansexuel",
    "papier-cul",
    "parachuter un sénégalais",
    "pare-choc",
    "pare-chocs",
    "parle à mon cul, ma tête est malade",
    "partir en couille",
    "pas fort",
    "patar1n",
    "patarin",
    "patarn",
    "patente à gosse",
    "pauvre con",
    "pays-bas",
    "peau de zob",
    "pecque",
    "ped0qu3",
    "ped0que",
    "ped@l3",
    "ped@le",
    "pedal3",
    "pedoqu3",
    "pedoque",
    "peler",
    "pelle à merde",
    "penchant",
    "penser avec sa bite",
    "penser avec sa queue",
    "pequ3n@ud",
    "pequ3naud",
    "pequen@ud",
    "pequenaud",
    "pervers",
    "pet",
    "pet sauce",
    "pet@55e",
    "pet@ss3",
    "pet@sse",
    "peta553",
    "petass3",
    "peteux",
    "petit tabernac",
    "petite bite",
    "petite pute",
    "pgn0uf",
    "pgnouf",
    "pi550u",
    "pi55ou",
    "pign0uf",
    "pignouf",
    "pimbêch3",
    "pimbêche",
    "piment",
    "pine",
    "piner",
    "pinocumettable",
    "pinocumettre",
    "pipe",
    "piquer",
    "piqûres",
    "piss0u",
    "piss3ux",
    "pisse-au-lit",
    "pisser dans",
    "pisser de la copie",
    "pisser sa côtelette",
    "pisser à la raie",
    "pisserclitoris",
    "pisseur",
    "pisseux",
    "pissou",
    "pl0uc",
    "pl3utr3",
    "plan cul",
    "planter le javelot dans la moquette",
    "pleutre",
    "plotte",
    "plotte à cash",
    "plouc",
    "plume",
    "poche",
    "pogne-cul",
    "poil",
    "pomme à l’huile",
    "pommeau",
    "pompe à merde",
    "pomper",
    "porc@5",
    "porc@553",
    "porc@55e",
    "porc@s",
    "porc@ss3",
    "porc@sse",
    "porca5",
    "porca553",
    "porca55e",
    "porcas",
    "porcass3",
    "porcasse",
    "pornographie",
    "porter le pet",
    "pouc@v",
    "poucav",
    "pouf1@553",
    "pouf1@55e",
    "pouf1@ss3",
    "pouf1@sse",
    "pouf1a553",
    "pouf1a55e",
    "pouf1ass3",
    "pouf1asse",
    "pouf@553",
    "pouf@55e",
    "pouf@ss3",
    "pouf@sse",
    "poufa553",
    "poufa55e",
    "poufass3",
    "poufasse",
    "pouff1@553",
    "pouff1@55e",
    "pouff1@ss3",
    "pouff1@sse",
    "pouff1a553",
    "pouff1a55e",
    "pouff1ass3",
    "pouff1asse",
    "pouff@553",
    "pouff@55e",
    "pouff@ss3",
    "pouff@sse",
    "pouffa553",
    "pouffa55e",
    "pouffass3",
    "pouffasse",
    "pouffe",
    "pouffi@553",
    "pouffi@55e",
    "pouffi@ss3",
    "pouffi@sse",
    "pouffia553",
    "pouffia55e",
    "pouffiass3",
    "pouffiasse",
    "poufi@553",
    "poufi@55e",
    "poufi@ss3",
    "poufi@sse",
    "poufia553",
    "poufia55e",
    "poufiass3",
    "poufiasse",
    "pougner",
    "pound3",
    "pounde",
    "poundé",
    "poupée",
    "pour les couilles du pape",
    "pourr1tur3",
    "pourr1ture",
    "pourrir",
    "pourritur3",
    "pourriture",
    "pourrtur3",
    "pourrture",
    "pousse-crotte",
    "pousser le repas de la veille",
    "pousser une gueulante",
    "poutrer",
    "prostituée",
    "pss0u",
    "pssou",
    "pun@153",
    "pun@15e",
    "pun@1s3",
    "pun@1se",
    "pun@53",
    "pun@5e",
    "pun@i53",
    "pun@i5e",
    "pun@is3",
    "pun@ise",
    "pun@s3",
    "pun@se",
    "puna153",
    "puna15e",
    "puna1s3",
    "puna1se",
    "puna53",
    "puna5e",
    "punai53",
    "punai5e",
    "punais3",
    "punaise",
    "punas3",
    "punase",
    "purée",
    "put1n",
    "put3",
    "put@1n",
    "put@in",
    "put@n",
    "puta1n",
    "putain con",
    "putain de",
    "putain de bordel de merde",
    "putain de merde",
    "putain de moine",
    "putain de sa mère",
    "putain de sa race",
    "putain de ta race",
    "putain de temps",
    "putain t'es moche",
    "putain t’es moche",
    "putain, pute",
    "putain, tu m’as fait peur",
    "putan",
    "pute a cinq cennes",
    "pute borgne",
    "pute de luxe",
    "pute or putin",
    "putin",
    "putn",
    "péd0qu3",
    "péd0que",
    "péd@l3",
    "péd@le",
    "pédal3",
    "pédale",
    "pédale de marde",
    "pédophile",
    "pédophilie",
    "pédoqu3",
    "pédoque",
    "pédé",
    "pédé comme un grec",
    "pélot",
    "pénis",
    "pénétration",
    "pénétrer",
    "pépom",
    "péqu3n@ud",
    "péqu3naud",
    "péquen@ud",
    "péquenaud",
    "pét@553",
    "pét@55e",
    "pét@ss3",
    "pét@sse",
    "péta553",
    "péta55e",
    "pétass3",
    "pétasse",
    "péter",
    "péter dans la soie",
    "péter la cenne",
    "péter le cul",
    "péter les couilles",
    "péter à la gueule",
    "péteux",
    "qu'esser qu'tu calice lã",
    "qu3ut@rd",
    "qu3utard",
    "quel bordel",
    "quel salaud",
    "queue",
    "queut@rd",
    "queutard",
    "quéquette",
    "qu’est-ce que tu branles",
    "qu’il aille se faire foutre",
    "qu’ils aillent se faire foutre",
    "qu’on l’encule",
    "r05b1f",
    "r05bf",
    "r05bif",
    "r0b35p13rr0t",
    "r0b35p3rr0t",
    "r0b35pi3rr0t",
    "r0b3sp13rr0t",
    "r0b3sp3rr0t",
    "r0b3spi3rr0t",
    "r0be5p1err0t",
    "r0be5perr0t",
    "r0be5pierr0t",
    "r0besp1err0t",
    "r0besperr0t",
    "r0bespierr0t",
    "r0sb1f",
    "r0sbf",
    "r0sbif",
    "r0ulur3",
    "r0ulure",
    "r1p0p33",
    "r1p0pe3",
    "r1p0pee",
    "r1p0pé3",
    "r1p0pée",
    "r1pop33",
    "r1pope3",
    "r1popee",
    "r1popé3",
    "r1popée",
    "r@clur3",
    "r@clure",
    "r@t0n",
    "r@ton",
    "raccrocher à la gueule",
    "raclur3",
    "radasse",
    "rage",
    "ramoner",
    "ramoner le trou de balle",
    "rapace",
    "ras la touffe",
    "ras le cul",
    "ras-la-moule",
    "ras-le-bonbon",
    "ras-les-fesses",
    "rat0n",
    "ratisser le bunker",
    "refucker",
    "remuer la merde",
    "retourne aux asperges",
    "retourne enculer",
    "rien à branler",
    "rien à enculer",
    "rien à foutre",
    "riflard",
    "rip0p33",
    "rip0pe3",
    "rip0pee",
    "rip0pé3",
    "rip0pée",
    "ripop33",
    "ripope3",
    "ripopee",
    "ripopé3",
    "ripopée",
    "ro5b1f",
    "ro5bf",
    "ro5bif",
    "rob35p13rrot",
    "rob35p3rrot",
    "rob35pi3rrot",
    "rob3sp13rrot",
    "rob3sp3rrot",
    "rob3spi3rrot",
    "robe5p1errot",
    "robe5perrot",
    "robe5pierrot",
    "robesp1errot",
    "robesperrot",
    "robespierrot",
    "rondelle",
    "rosb1f",
    "rosbf",
    "rosbif",
    "roubignole",
    "roulur3",
    "roulure",
    "roupette",
    "rp0p33",
    "rp0pe3",
    "rp0pee",
    "rp0pé3",
    "rp0pée",
    "rpop33",
    "rpope3",
    "rpopee",
    "rpopé3",
    "rpopée",
    "râpé",
    "récurer la marmite",
    "réempaffer",
    "réenculer",
    "s0tt1s3ux",
    "s0tt1seux",
    "s0ttis3ux",
    "s0ttiseux",
    "s0tts3ux",
    "s0ttseux",
    "s0us-m3rd3",
    "s0us-merde",
    "s3nt-l@-p1ss3",
    "s3nt-l@-piss3",
    "s3nt-l@-pss3",
    "s3nt-la-p1ss3",
    "s3nt-la-piss3",
    "s3nt-la-pss3",
    "s@g0u1n",
    "s@g0uin",
    "s@g0un",
    "s@gou1n",
    "s@gouin",
    "s@goun",
    "s@l0p",
    "s@l0p3",
    "s@l0p3r13",
    "s@l0p3ri3",
    "s@l0p@rd",
    "s@l0pe",
    "s@l3",
    "s@l@ud",
    "s@le",
    "s@lop",
    "s@lop3",
    "s@lop3ri3",
    "s@lop@rd",
    "s@lope",
    "s@loperie",
    "s@tr0u1ll3",
    "s@tr0u1lle",
    "s@tr0uill3",
    "s@tr0uille",
    "s@tr0ull3",
    "s@tr0ulle",
    "s@trou1ll3",
    "s@trou1lle",
    "s@trouill3",
    "s@trouille",
    "s@troull3",
    "s@troulle",
    "sa mère",
    "sa mère la pute",
    "sa race",
    "sac a foutre",
    "sac de billes",
    "sac merde",
    "sac vin",
    "sac à foutre",
    "sac à merde",
    "sac ã merde",
    "sac ã vin",
    "saccade",
    "sacrament",
    "sacrament que ce gars-là est épais",
    "sacre bleu",
    "sacrebleu",
    "sacré",
    "sacréfisse",
    "sadique",
    "sadisme",
    "sag0u1n",
    "sag0uin",
    "sag0un",
    "sagou1n",
    "sagouin",
    "sagoun",
    "saint",
    "saint bénisse",
    "saint christ",
    "saint ciboire",
    "saint ciboire aux deux étages",
    "saint esprit",
    "saint gériboire",
    "saint hostie",
    "saint pkp",
    "saint sacrament",
    "saint sacrifice",
    "saint sacripant",
    "saint sicrisse",
    "saint sicroche",
    "saint tabarnac",
    "saint-chrême",
    "saint-ciboire",
    "saint-crême",
    "saint-sacrament",
    "saint-simonaque",
    "sainte viarge",
    "saintosti",
    "sal0p",
    "sal0p3",
    "sal0pard",
    "sal0pe",
    "sal0perie",
    "sal3",
    "salament",
    "salaud, tu m’as bien eu",
    "sale",
    "salle des fêtes",
    "salop3",
    "salop3ri3",
    "salopard",
    "saloper1e",
    "saloperie",
    "saloppe",
    "sanglant",
    "sans-couilles",
    "saprement",
    "sarce",
    "satr0u1ll3",
    "satr0u1lle",
    "satr0uill3",
    "satr0uille",
    "satr0ull3",
    "satr0ulle",
    "satrou1ll3",
    "satrou1lle",
    "satrouill3",
    "satrouille",
    "satroull3",
    "satroulle",
    "saute au paf",
    "saute-au-paf",
    "sauter",
    "schb3b",
    "schbeb",
    "schl3u",
    "schleu",
    "schn0c",
    "schn0ck",
    "schn0qu3",
    "schn0que",
    "schnek",
    "schnoc",
    "schnock",
    "schnoqu3",
    "schnoque",
    "scivey",
    "se battre les couilles de",
    "se branler",
    "se branler comme de l’an quarante de",
    "se branler les couilles",
    "se casser la gueule",
    "se casser le cul",
    "se casser le tronc",
    "se casser les couilles",
    "se cirer le manche",
    "se cogner",
    "se contrecrisser",
    "se contrefoutre",
    "se câlisser",
    "se doigter",
    "se désenclaver la péninsule",
    "se faire",
    "se faire enculer",
    "se faire la bite",
    "se faire pousser au cul",
    "se faire quelquun",
    "se faire reluire",
    "se foutre comme de l’an quarante de",
    "se foutre dans la merde",
    "se foutre de",
    "se foutre de la gueule de",
    "se geler le croupion",
    "se geler le fion",
    "se geler les couilles",
    "se les cailler",
    "se magner le cul",
    "se manger les couilles",
    "se masturber",
    "se ronger le cul à la vinaigrette",
    "se sortir les doigts du cul",
    "se taire",
    "se taper",
    "se taper une queue",
    "se vider les couilles",
    "seins",
    "sent-l@-p1sse",
    "sent-l@-pisse",
    "sent-l@-psse",
    "sent-la-p1sse",
    "sent-la-pisse",
    "sent-la-psse",
    "sexe",
    "shampoing",
    "sieve",
    "silo de marde",
    "simonac",
    "simonaque",
    "sodome",
    "sodomie",
    "sodomiser",
    "sodomisé",
    "son hostié char",
    "sott1s3ux",
    "sott1seux",
    "sottis3ux",
    "sottiseux",
    "sotts3ux",
    "sottseux",
    "souchien",
    "souchienne",
    "sous-m3rd3",
    "sous-merde",
    "sperme",
    "sphincter",
    "squatch",
    "st3@r1qu3",
    "st3@riqu3",
    "st3@rqu3",
    "st3ar1qu3",
    "st3ariqu3",
    "st3arqu3",
    "ste@r1qu3",
    "ste@r1que",
    "ste@riqu3",
    "ste@rique",
    "ste@rqu3",
    "ste@rque",
    "stear1qu3",
    "stear1que",
    "steariqu3",
    "stearique",
    "stearqu3",
    "stearque",
    "stephen harper",
    "stupide",
    "sté@r1qu3",
    "sté@r1que",
    "sté@riqu3",
    "sté@rique",
    "sté@rqu3",
    "sté@rque",
    "stéar1qu3",
    "stéar1que",
    "stéariqu3",
    "stéarique",
    "stéarqu3",
    "stéarque",
    "suce",
    "suce ma bite",
    "suce ma bites",
    "suce ma blette",
    "suce ma marde",
    "suce ma quéquette",
    "suce-boules",
    "suce-médailles",
    "suceu d'poche",
    "suceuse",
    "s’archifoutre",
    "s’astiquer le poireau",
    "s’en badigeonner les testicules avec le pinceau de l’indifférence",
    "s’en battre",
    "s’en battre lec",
    "s’en beurrer la raie",
    "s’en branler",
    "s’en cogner",
    "s’en câlisser",
    "s’en foutre",
    "s’en taper",
    "t'as pas de couilles",
    "t'es rien qu'un petit connard",
    "t'es un salaud",
    "t0c@rd",
    "t0card",
    "t3b3",
    "t3be",
    "t3bé",
    "t3t3ux",
    "t3ub3",
    "t3ube",
    "t3ubé",
    "t@f0l3",
    "t@f0le",
    "t@f10l3",
    "t@f10le",
    "t@f1ol3",
    "t@f1ole",
    "t@fi0l3",
    "t@fi0le",
    "t@fiol3",
    "t@fiole",
    "t@fol3",
    "t@fole",
    "t@nt0u53r13",
    "t@nt0u53r3",
    "t@nt0u53ri3",
    "t@nt0u5er1e",
    "t@nt0u5ere",
    "t@nt0u5erie",
    "t@nt0us3r13",
    "t@nt0us3r3",
    "t@nt0us3ri3",
    "t@nt0user1e",
    "t@nt0usere",
    "t@nt0userie",
    "t@nt0uz3",
    "t@nt0uze",
    "t@ntou53r13",
    "t@ntou53r3",
    "t@ntou53ri3",
    "t@ntou5er1e",
    "t@ntou5ere",
    "t@ntou5erie",
    "t@ntous3r13",
    "t@ntous3r3",
    "t@ntous3ri3",
    "t@ntouser1e",
    "t@ntousere",
    "t@ntouserie",
    "t@ntouz3",
    "t@ntouze",
    "t@p3tt3",
    "t@pette",
    "t@rl0uz3",
    "t@rl0uze",
    "t@rlouz3",
    "t@rlouze",
    "ta ben pas d'amis.",
    "ta bouche",
    "ta gueule quand je parle",
    "ta mere",
    "ta mere est francaise",
    "ta mere la pute",
    "ta mere suce des bites en enfer",
    "ta mère",
    "ta mère elle suce des ours",
    "ta mère est une pute",
    "ta mère la pute",
    "tabarnac",
    "tabarnak",
    "tabarnak aux deux étages",
    "tabarnak percé",
    "tabernac",
    "tabernacle",
    "taboune",
    "taf0l3",
    "taf0le",
    "taf10l3",
    "taf10le",
    "taf1ol3",
    "taf1ole",
    "tafi0l3",
    "tafi0le",
    "tafiol3",
    "tafiole",
    "tafol3",
    "tafole",
    "tais-toi",
    "take off eh",
    "tanche",
    "tanné",
    "tant0u53r13",
    "tant0u53r3",
    "tant0u53ri3",
    "tant0u5er1e",
    "tant0u5ere",
    "tant0u5erie",
    "tant0us3r13",
    "tant0us3r3",
    "tant0us3ri3",
    "tant0user1e",
    "tant0usere",
    "tant0userie",
    "tant0uz3",
    "tant0uze",
    "tantou53r13",
    "tantou53r3",
    "tantou53ri3",
    "tantou5er1e",
    "tantou5ere",
    "tantou5erie",
    "tantous3r13",
    "tantous3r3",
    "tantous3ri3",
    "tantouser1e",
    "tantousere",
    "tantouserie",
    "tantouz3",
    "tantouze",
    "tap3tt3",
    "taper",
    "tapettitude",
    "tapiole",
    "tapis muncher",
    "tarl0uz3",
    "tarl0uze",
    "tarlouse va",
    "tarlouz3",
    "tarlouze",
    "tarte",
    "tartissure",
    "tas de marde",
    "taspé",
    "tassepé",
    "tata",
    "tayeul",
    "tebe",
    "tebé",
    "techa",
    "tenir votre ane",
    "tepu",
    "testiculaire",
    "testicule",
    "tet3ux",
    "teteux",
    "teub",
    "teube",
    "teubé",
    "teuch",
    "teucha",
    "teuf",
    "tg",
    "tire-au-cul",
    "tirelire",
    "tirer son coup",
    "tirer un coup",
    "toc@rd",
    "tocard",
    "tool",
    "torrieu",
    "torrieux",
    "torvice",
    "toton",
    "touche à ton cul t’auras des verrues",
    "touffe",
    "tout de la gueule",
    "toé",
    "toé, le p’tit câline de morvaillon",
    "tr0uduc",
    "tr@1n33",
    "tr@1nee",
    "tr@in33",
    "tr@inee",
    "tr@n33",
    "tr@nee",
    "tr@în33",
    "tr@îne3",
    "tr@înee",
    "tr@îné3",
    "tr@înée",
    "tra1n33",
    "tra1nee",
    "train33",
    "trainee",
    "tran33",
    "tranee",
    "trappe",
    "traîn33",
    "traîne3",
    "traînee",
    "traîné3",
    "traînée",
    "tremper",
    "tremper son biscuit",
    "treuf",
    "tringler",
    "trique",
    "troncher",
    "trou de balle",
    "trou de cul",
    "trou de t'chu",
    "trou du cul du monde",
    "trouducune",
    "trouer le cul",
    "troufignoler",
    "troufignolerie",
    "troufignoliser",
    "troufignon",
    "tru1@553",
    "tru1@55e",
    "tru1@ss3",
    "tru1@sse",
    "tru1a553",
    "tru1a55e",
    "tru1ass3",
    "tru1asse",
    "tru@553",
    "tru@55e",
    "tru@ss3",
    "tru@sse",
    "trua553",
    "trua55e",
    "truass3",
    "truasse",
    "trui@553",
    "trui@55e",
    "trui@ss3",
    "trui@sse",
    "truia553",
    "truia55e",
    "truiass3",
    "truiasse",
    "truie",
    "très stupide",
    "tu as merdé",
    "tu commence m’enmerder",
    "tu es con",
    "tu es très stupide",
    "tu es un putain",
    "tu et un ane",
    "tu fais chier",
    "tu fais chier.",
    "tu fais dur",
    "tu m'emmerdes",
    "tu m`emmerdes",
    "tu mangeras le tas",
    "tu me fais chier",
    "tu me fatigues",
    "tu me gonfles",
    "tu me niaises-tu",
    "turluchon",
    "turlute",
    "turlutte",
    "tuyau",
    "tâter",
    "téléphoner aux congolais",
    "tét3ux",
    "téteux",
    "tête de gland",
    "tête de nœud",
    "tête moi le dard",
    "tête moi le noeud",
    "t’as intérêt ne pas m’énervé",
    "t’as pas de couilles",
    "t’es débile",
    "t’es rien qu’un petit connard",
    "t’es un criss de cave, toi",
    "t’es un salaud",
    "t’es vraiment emmerdant, toi",
    "une salope",
    "urinaire",
    "urètre",
    "utérus",
    "v13d@53",
    "v13d@s3",
    "v13da53",
    "v13das3",
    "v13r",
    "v1d3-c0u1ll35",
    "v1d3-c0u1ll3s",
    "v1d3-cou1ll35",
    "v1d3-cou1ll3s",
    "v1de-c0u1lle5",
    "v1de-c0u1lles",
    "v1de-cou1lle5",
    "v1de-cou1lles",
    "v1ed@53",
    "v1ed@5e",
    "v1ed@s3",
    "v1ed@se",
    "v1eda53",
    "v1eda5e",
    "v1edas3",
    "v1edase",
    "v1er",
    "v1éd@53",
    "v1éd@5e",
    "v1éd@s3",
    "v1éd@se",
    "v1éda53",
    "v1éda5e",
    "v1édas3",
    "v1édase",
    "v3d@53",
    "v3d@s3",
    "v3da53",
    "v3das3",
    "v3r",
    "v@ur13n",
    "v@ur1en",
    "v@ur3n",
    "v@uren",
    "v@uri3n",
    "v@urien",
    "va chier",
    "va libérer mandela",
    "va niquer ta mã¨re",
    "va niquer ta mère",
    "va su le djabe",
    "va t'empaler encule",
    "va te branler",
    "va te crosser",
    "va te faire",
    "va te faire baiser",
    "va te faire empapaouter",
    "va te faire enculer",
    "va te faire enculer chez les grecs",
    "va te faire enculer par un ourse",
    "va te faire mettre",
    "va te faire une soupe d’esques",
    "va te faire voir",
    "va te pendre",
    "va te pendre avec ma bite",
    "va te tripoter",
    "vache",
    "vache sale",
    "vagin",
    "vais libérer mandela",
    "valseuse",
    "varlope",
    "vas chier",
    "vas faire foutre a la vache",
    "vas te crosser avec une poignée de clous",
    "vas te crosser avec une poignée de clous rouillés",
    "vas te crosser avec une poignée de poignée de braquettes",
    "vas te faire",
    "vas te faire chier",
    "vas te faire cuire un eouf fils de pute",
    "vas te faire enculi",
    "vas te faire foutre",
    "vaur13n",
    "vaur1en",
    "vaur3n",
    "vauren",
    "vauri3n",
    "vaurien",
    "vd3-c0ull35",
    "vd3-c0ull3s",
    "vd3-coull35",
    "vd3-coull3s",
    "vde-c0ulle5",
    "vde-c0ulles",
    "vde-coulle5",
    "vde-coulles",
    "ved@5e",
    "ved@s3",
    "ved@se",
    "veda53",
    "veda5e",
    "vedas3",
    "vedase",
    "vendre du piment",
    "ver",
    "verasse",
    "verrat",
    "veuve",
    "vi3d@53",
    "vi3d@s3",
    "vi3da53",
    "vi3das3",
    "vi3r",
    "viande à chien",
    "viarge",
    "vid3-c0uill35",
    "vid3-c0uill3s",
    "vid3-couill35",
    "vid3-couill3s",
    "vide-c0uille5",
    "vide-c0uilles",
    "vide-couille5",
    "vide-couilles",
    "vied@53",
    "vied@5e",
    "vied@s3",
    "vied@se",
    "vieda53",
    "vieda5e",
    "viedas3",
    "viedase",
    "vieille",
    "viens m'enculer",
    "vier",
    "vier d’âne",
    "viol",
    "violeur",
    "violé",
    "viéd@53",
    "viéd@5e",
    "viéd@s3",
    "viéd@se",
    "viéda53",
    "viéda5e",
    "viédas3",
    "viédase",
    "vous sentez comme le boeuf et le fromage",
    "vous vissez",
    "vous êtes stupide",
    "vtff",
    "véd@53",
    "véd@5e",
    "véd@s3",
    "véd@se",
    "véda53",
    "véda5e",
    "védas3",
    "védase",
    "wasteyute",
    "x évalué",
    "x3r0p1n3ur",
    "x3r0pin3ur",
    "x3r0pn3ur",
    "x3rop1n3ur",
    "x3ropin3ur",
    "x3ropn3ur",
    "xer0p1n3ur",
    "xer0p1neur",
    "xer0pin3ur",
    "xer0pineur",
    "xer0pn3ur",
    "xer0pneur",
    "xerop1n3ur",
    "xerop1neur",
    "xeropin3ur",
    "xeropineur",
    "xeropn3ur",
    "xeropneur",
    "xér0p1n3ur",
    "xér0p1neur",
    "xér0pin3ur",
    "xér0pineur",
    "xér0pn3ur",
    "xér0pneur",
    "xérop1n3ur",
    "xérop1neur",
    "xéropin3ur",
    "xéropineur",
    "xéropn3ur",
    "xéropneur",
    "y avoir une couille dans le potage",
    "y avoir une couille dans le pâté",
    "y0ud",
    "y0up1n",
    "y0up1n15@t10n",
    "y0up1n15at10n",
    "y0up1n1s@t10n",
    "y0up1n1sat10n",
    "y0up1n3",
    "y0up1ne",
    "y0upin",
    "y0upin3",
    "y0upine",
    "y0upini5@ti0n",
    "y0upini5ati0n",
    "y0upinis@ti0n",
    "y0upinisati0n",
    "y0upn",
    "y0upn3",
    "y0upn5@t0n",
    "y0upn5at0n",
    "y0upne",
    "y0upns@t0n",
    "y0upnsat0n",
    "y0utr3",
    "y0utre",
    "y3ul3",
    "yer fuckin' a right",
    "yeule",
    "you hoser",
    "you sheep fucker",
    "youd",
    "youp",
    "youp1n",
    "youp1n15@t1on",
    "youp1n15at1on",
    "youp1n1s@t1on",
    "youp1n1sat1on",
    "youp1n3",
    "youp1ne",
    "youpin3",
    "youpine",
    "youpini5@tion",
    "youpini5ation",
    "youpinis@tion",
    "youpinisation",
    "youpn",
    "youpn3",
    "youpn5@ton",
    "youpn5aton",
    "youpne",
    "youpns@ton",
    "youpnsaton",
    "youtr3",
    "zboob",
    "zboube",
    "zgu3gu3",
    "zguegu3",
    "zguegue",
    "zguègu3",
    "zguègue",
    "zigounette",
    "zizi",
    "zoophilie",
    "zut",
    "zut alors",
    "à chier",
    "à couilles rabattues",
    "à la con",
    "à la mords-moi",
    "à la mords-moi-le-nœud",
    "à la roule-moi les couilles dans la laitue",
    "à un poil de cul",
    "ça casse les couilles",
    "ça craint",
    "ça fait chier",
    "ça fait shier",
    "ça m'emmerde",
    "ça me casse les couilles",
    "ça me fait chier",
    "ça me saoûle",
    "ça pue",
    "ça schlingue",
    "ça, c’est une ostie de belle fille",
    "éburné",
    "écouillé",
    "égoïsme",
    "éjaculant",
    "éjaculation",
    "éjaculations",
    "éjacule",
    "éjaculer",
    "éjaculé",
    "ép@15",
    "ép@1s",
    "ép@5",
    "ép@i5",
    "ép@is",
    "ép@s",
    "épa15",
    "épa1s",
    "épa5",
    "épai5",
    "épais",
    "épas",
    "érection",
    "ériger",
    "étoile",
    "étole",
    "étr0n",
    "étrangler le borgne",
    "étron",
    "être chié",
    "être couillu",
    "être la fête",
    "être mou de la bite",
] as const;

export default words;
