import { mkdirSync, writeFileSync } from "node:fs";

import { join } from "@visulima/path";
import type { WorkspaceConfiguration } from "@visulima/task-runner";
import { afterEach, beforeEach, describe, expect, it } from "vitest";

import type { VisProjectConfiguration } from "../../src/config/workspace";
import {
    buildCodeownersLines,
    DEFAULT_BLOCK_MARKER,
    mergeIntoExisting,
    renderCodeowners,
    renderCodeownersBlock,
} from "../../src/util/codeowners";
import {
    collectMaintainerLines,
    collectNestedCodeownersLines,
    extractGitHubHandle,
    parseCodeownersFile,
} from "../../src/util/codeowners-sources";
import { cleanupTemporaryDirectory, createTemporaryDirectory } from "../test-helpers";

describe(buildCodeownersLines, () => {
    it("should prefix paths with each project's root and sort by path (file-source)", () => {
        expect.assertions(5);

        const workspace: WorkspaceConfiguration = {
            projects: {
                "pkg-a": {
                    owners: [{ owners: ["@team-a"], path: "src/**" }],
                    root: "packages/pkg-a",
                } as VisProjectConfiguration,
                "pkg-b": {
                    owners: [{ owners: ["@team-b"], path: "src/**" }],
                    root: "packages/pkg-b",
                } as VisProjectConfiguration,
            },
        };

        const lines = buildCodeownersLines(workspace, { orderBy: "file-source" });

        expect(lines).toHaveLength(2);
        expect(lines[0]!.path).toBe("/packages/pkg-a/src/**");
        expect(lines[0]!.owners).toStrictEqual(["@team-a"]);
        expect(lines[1]!.path).toBe("/packages/pkg-b/src/**");
        expect(lines[1]!.owners).toStrictEqual(["@team-b"]);
    });

    it("should sort by project-id then path when orderBy is 'project-id'", () => {
        expect.assertions(4);

        const workspace: WorkspaceConfiguration = {
            projects: {
                "a-project": {
                    owners: [
                        { owners: ["@a-team"], path: "tests/**" },
                        { owners: ["@a-team"], path: "src/**" },
                    ],
                    root: "packages/a-project",
                } as VisProjectConfiguration,
                "z-project": {
                    owners: [{ owners: ["@z-team"], path: "lib/**" }],
                    root: "packages/z-project",
                } as VisProjectConfiguration,
            },
        };

        const lines = buildCodeownersLines(workspace, { orderBy: "project-id" });

        expect(lines).toHaveLength(3);
        expect(lines[0]!.projectId).toBe("a-project");
        expect(lines[0]!.path).toBe("/packages/a-project/src/**");
        expect(lines[2]!.projectId).toBe("z-project");
    });

    it("should include global paths from config", () => {
        expect.assertions(3);

        const workspace: WorkspaceConfiguration = {
            projects: {
                app: {
                    owners: [{ owners: ["@app-team"], path: "src/**" }],
                    root: "apps/app",
                } as VisProjectConfiguration,
            },
        };

        const lines = buildCodeownersLines(workspace, {
            globalPaths: { "/.github/**": ["@infra"], "/docs/**": ["@docs-team"] },
        });

        expect(lines).toHaveLength(3);
        expect(lines[0]!.path).toBe("/.github/**");
        expect(lines[0]!.owners).toStrictEqual(["@infra"]);
    });

    it("should return empty lines when projects have no owners", () => {
        expect.assertions(1);

        const workspace: WorkspaceConfiguration = {
            projects: {
                empty: {
                    root: "packages/empty",
                },
            },
        };

        const lines = buildCodeownersLines(workspace, undefined);

        expect(lines).toHaveLength(0);
    });
});

describe(renderCodeowners, () => {
    it("should render header, entries with owners, channel comments, and a trailing newline", () => {
        expect.assertions(6);

        const lines = [
            { owners: ["@team-a", "@team-b"], path: "/packages/foo/src/**" },
            { channel: "#alerts", owners: ["@ops"], path: "/infra/**" },
        ];

        const output = renderCodeowners(lines);
        const outputLines = output.split("\n");

        expect(outputLines[0]).toBe("# CODEOWNERS — generated by `vis sync codeowners`. Do not edit by hand.");
        expect(outputLines[1]).toBe("# Update each project's project.json `owners` field and re-run the command.");
        expect(outputLines[2]).toBe("");

        expect(outputLines[3]).toBe("/packages/foo/src/** @team-a @team-b");
        expect(outputLines[4]).toBe("/infra/** @ops    # notify: #alerts");

        expect(outputLines[outputLines.length - 1]).toBe("");
    });

    it("should produce only header and trailing newline for empty lines array", () => {
        expect.assertions(2);

        const output = renderCodeowners([]);
        const outputLines = output.split("\n");

        expect(outputLines).toHaveLength(4);
        expect(outputLines[outputLines.length - 1]).toBe("");
    });

    it("should replace the second header line with regenerationCommand when provided", () => {
        expect.assertions(2);

        const output = renderCodeowners(
            [{ owners: ["@team"], path: "/foo/" }],
            { regenerationCommand: "pnpm owners" },
        );

        const outputLines = output.split("\n");

        expect(outputLines[1]).toBe("# Re-run with: pnpm owners");
        expect(outputLines[3]).toBe("/foo/ @team");
    });
});

describe(buildCodeownersLines, () => {
    it("should drop extra-source lines whose path is already claimed by project.json", () => {
        expect.assertions(2);

        const workspace: WorkspaceConfiguration = {
            projects: {
                explicit: {
                    owners: [{ owners: ["@canonical"], path: "" }],
                    root: "packages/explicit",
                } as VisProjectConfiguration,
            },
        };

        const lines = buildCodeownersLines(workspace, { orderBy: "file-source" }, [
            { owners: ["@ghost"], path: "/packages/explicit/", source: "nested" },
        ]);

        expect(lines).toHaveLength(1);
        expect(lines[0]!.owners).toStrictEqual(["@canonical"]);
    });

    it("should accept extra-source lines on paths not covered by project.json", () => {
        expect.assertions(2);

        const lines = buildCodeownersLines({ projects: {} }, undefined, [
            { owners: ["@nested-team"], path: "/services/api/", source: "nested" },
        ]);

        expect(lines).toHaveLength(1);
        expect(lines[0]!.owners).toStrictEqual(["@nested-team"]);
    });
});

describe(parseCodeownersFile, () => {
    it("should strip comments and blank lines and split path + owners", () => {
        expect.assertions(3);

        const out = parseCodeownersFile(
            ["# header comment", "", "src/** @core   # inline-comment", "docs/ @docs-team @backup", "no-owners-here", "  "].join("\n"),
        );

        expect(out).toHaveLength(2);
        expect(out[0]).toStrictEqual({ owners: ["@core"], path: "src/**" });
        expect(out[1]).toStrictEqual({ owners: ["@docs-team", "@backup"], path: "docs/" });
    });
});

describe(extractGitHubHandle, () => {
    it("should extract handles from github profile urls", () => {
        expect.assertions(4);

        expect(extractGitHubHandle("https://github.com/janedoe")).toBe("@janedoe");
        // eslint-disable-next-line sonarjs/no-clear-text-protocols -- exercising the parser's http:// fallback branch.
        expect(extractGitHubHandle("http://www.github.com/Org_Name")).toBe("@Org_Name");
        expect(extractGitHubHandle("https://github.com/team/sub")).toBe("@team");
        expect(extractGitHubHandle("https://github.com/janedoe?tab=repos")).toBe("@janedoe");
    });

    it("should return undefined for non-github urls or empty input", () => {
        expect.assertions(3);

        expect(extractGitHubHandle(undefined)).toBeUndefined();
        expect(extractGitHubHandle("https://example.com/jane")).toBeUndefined();
        expect(extractGitHubHandle("")).toBeUndefined();
    });
});

describe(renderCodeownersBlock, () => {
    it("should bracket entries with begin/end markers and omit the file header", () => {
        expect.assertions(4);

        const block = renderCodeownersBlock([{ owners: ["@x"], path: "/a/" }]);
        const lines = block.split("\n");

        expect(lines[0]).toBe(DEFAULT_BLOCK_MARKER.begin);
        expect(lines[lines.length - 1]).toBe(DEFAULT_BLOCK_MARKER.end);
        expect(lines).toContain("/a/ @x");
        expect(lines.some((line) => line.startsWith("# CODEOWNERS"))).toBe(false);
    });
});

describe(mergeIntoExisting, () => {
    it("should replace content between existing markers", () => {
        expect.assertions(2);

        const existing = [
            "# top-of-file note",
            "/manual/path @manual-team",
            "",
            DEFAULT_BLOCK_MARKER.begin,
            "stale @ghost",
            DEFAULT_BLOCK_MARKER.end,
            "/trailing/ @tail",
            "",
        ].join("\n");

        const block = renderCodeownersBlock([{ owners: ["@fresh"], path: "/new/" }]);
        const merged = mergeIntoExisting(existing, block);

        expect(merged).toContain("/manual/path @manual-team");
        expect(merged).toContain("/new/ @fresh");
    });

    it("should append the block with a blank line when markers are absent", () => {
        expect.assertions(2);

        const existing = "# hand-maintained header\n/manual/ @manual\n";
        const block = renderCodeownersBlock([{ owners: ["@auto"], path: "/auto/" }]);
        const merged = mergeIntoExisting(existing, block);

        expect(merged).toContain("/manual/ @manual");
        expect(merged.indexOf(DEFAULT_BLOCK_MARKER.begin)).toBeGreaterThan(merged.indexOf("/manual/ @manual"));
    });
});

describe(collectNestedCodeownersLines, () => {
    let workspaceRoot: string;

    beforeEach(() => {
        workspaceRoot = createTemporaryDirectory("vis-nested-co-");
    });

    afterEach(() => {
        cleanupTemporaryDirectory(workspaceRoot);
    });

    it("should rewrite leading-slash paths relative to the nested file's directory", async () => {
        expect.assertions(2);

        const dir = join(workspaceRoot, "services", "api");

        mkdirSync(dir, { recursive: true });
        writeFileSync(join(dir, "CODEOWNERS"), "/src/** @api-team\n");

        const lines = await collectNestedCodeownersLines(workspaceRoot, undefined);

        expect(lines).toHaveLength(1);
        expect(lines[0]!.path).toBe("/services/api/src/**");
    });

    it("should anchor non-rooted paths under the nested file's directory", async () => {
        expect.assertions(2);

        const dir = join(workspaceRoot, "services", "api");

        mkdirSync(dir, { recursive: true });
        writeFileSync(join(dir, "CODEOWNERS"), "docs/** @docs-team\n");

        const lines = await collectNestedCodeownersLines(workspaceRoot, undefined);

        expect(lines).toHaveLength(1);
        expect(lines[0]!.path).toBe("/services/api/docs/**");
    });

    it("should exclude the output file from the walk so re-runs do not recurse", async () => {
        expect.assertions(1);

        writeFileSync(join(workspaceRoot, "CODEOWNERS"), "/auto-generated @ghost\n");

        const lines = await collectNestedCodeownersLines(workspaceRoot, undefined, "CODEOWNERS");

        expect(lines).toHaveLength(0);
    });

    it("should ignore node_modules and .git directories by default", async () => {
        expect.assertions(1);

        const nodeModules = join(workspaceRoot, "node_modules", "pkg");
        const git = join(workspaceRoot, ".git");

        mkdirSync(nodeModules, { recursive: true });
        mkdirSync(git, { recursive: true });
        writeFileSync(join(nodeModules, "CODEOWNERS"), "/src @from-deps\n");
        writeFileSync(join(git, "CODEOWNERS"), "/x @from-git\n");

        const lines = await collectNestedCodeownersLines(workspaceRoot, undefined);

        expect(lines).toHaveLength(0);
    });

    it("should respect custom includes globs", async () => {
        expect.assertions(2);

        const dir = join(workspaceRoot, "team-a");

        mkdirSync(dir, { recursive: true });
        writeFileSync(join(dir, "OWNERS"), "/src @team-a\n");

        const lines = await collectNestedCodeownersLines(workspaceRoot, ["**/OWNERS"]);

        expect(lines).toHaveLength(1);
        expect(lines[0]!.owners).toStrictEqual(["@team-a"]);
    });
});

describe(collectMaintainerLines, () => {
    let workspaceRoot: string;

    beforeEach(() => {
        workspaceRoot = createTemporaryDirectory("vis-maintainer-");
    });

    afterEach(() => {
        cleanupTemporaryDirectory(workspaceRoot);
    });

    it("should emit one line per project with a resolvable github maintainer", () => {
        expect.assertions(3);

        const dir = join(workspaceRoot, "packages", "api");

        mkdirSync(dir, { recursive: true });
        writeFileSync(
            join(dir, "package.json"),
            JSON.stringify({
                maintainers: [{ name: "Jane", url: "https://github.com/janedoe" }],
                name: "@my/api",
            }),
        );

        const workspace = { projects: { api: { root: "packages/api" } as VisProjectConfiguration } };
        const lines = collectMaintainerLines(workspace, workspaceRoot);

        expect(lines).toHaveLength(1);
        expect(lines[0]!.path).toBe("/packages/api/");
        expect(lines[0]!.owners).toStrictEqual(["@janedoe"]);
    });

    it("should skip projects that already declare project.json owners", () => {
        expect.assertions(1);

        const dir = join(workspaceRoot, "packages", "api");

        mkdirSync(dir, { recursive: true });
        writeFileSync(
            join(dir, "package.json"),
            JSON.stringify({
                maintainers: [{ url: "https://github.com/jane" }],
                name: "@my/api",
            }),
        );

        const workspace = {
            projects: {
                api: {
                    owners: [{ owners: ["@canonical"], path: "src/**" }],
                    root: "packages/api",
                } as VisProjectConfiguration,
            },
        };

        const lines = collectMaintainerLines(workspace, workspaceRoot);

        expect(lines).toHaveLength(0);
    });

    it("should skip maintainers whose url is not a github profile", () => {
        expect.assertions(1);

        const dir = join(workspaceRoot, "packages", "api");

        mkdirSync(dir, { recursive: true });
        writeFileSync(
            join(dir, "package.json"),
            JSON.stringify({
                maintainers: [{ url: "https://example.com/jane" }],
                name: "@my/api",
            }),
        );

        const workspace = { projects: { api: { root: "packages/api" } as VisProjectConfiguration } };
        const lines = collectMaintainerLines(workspace, workspaceRoot);

        expect(lines).toHaveLength(0);
    });

    it("should dedupe handles across maintainers on the same project", () => {
        expect.assertions(2);

        const dir = join(workspaceRoot, "packages", "api");

        mkdirSync(dir, { recursive: true });
        writeFileSync(
            join(dir, "package.json"),
            JSON.stringify({
                maintainers: [
                    { url: "https://github.com/janedoe" },
                    { url: "https://github.com/janedoe" },
                    { url: "https://github.com/other" },
                ],
                name: "@my/api",
            }),
        );

        const workspace = { projects: { api: { root: "packages/api" } as VisProjectConfiguration } };
        const lines = collectMaintainerLines(workspace, workspaceRoot);

        expect(lines).toHaveLength(1);
        expect(lines[0]!.owners).toStrictEqual(["@janedoe", "@other"]);
    });

    it("should silently skip projects with no package.json on disk", () => {
        expect.assertions(1);

        const workspace = { projects: { ghost: { root: "packages/ghost" } as VisProjectConfiguration } };
        const lines = collectMaintainerLines(workspace, workspaceRoot);

        expect(lines).toHaveLength(0);
    });
});
