import ColorizeImpl from "./colorize.server";
import type { ColorizeType } from "./types";

const colorize: ColorizeType = new ColorizeImpl() as ColorizeType;

export default colorize as ColorizeType;

export const {
    ansi256,
    bg,
    bgAnsi256,
    bgBlack,
    bgBlackBright,
    bgBlue,
    bgBlueBright,
    bgCyan,
    bgCyanBright,
    bgGray,
    bgGreen,
    bgGreenBright,
    bgGrey,
    bgHex,
    bgMagenta,
    bgMagentaBright,
    bgRed,
    bgRedBright,
    bgRgb,
    bgWhite,
    bgWhiteBright,
    bgYellow,
    bgYellowBright,
    black,
    blackBright,
    blue,
    blueBright,
    bold,
    cyan,
    cyanBright,
    dim,
    fg,
    gray,
    green,
    greenBright,
    grey,
    hex,
    hidden,
    inverse,
    italic,
    magenta,
    magentaBright,
    overline,
    red,
    redBright,
    reset,
    rgb,
    strike,
    strikethrough,
    strip,
    underline,
    visible,
    white,
    whiteBright,
    yellow,
    yellowBright,
} = colorize;

export { default as Colorize } from "./colorize.server";
export type { AnsiColors, AnsiStyles, ColorizeType } from "./types";
