import { createConfig } from "@anolilab/eslint-config";

/** @type {import("@anolilab/eslint-config").PromiseFlatConfigComposer} */
export default createConfig(
    {
        ignores: [
            "dist",
            "node_modules",
            "coverage",
            "__fixtures__",
            "__docs__",
            "examples",
            "vitest.config.ts",
            "packem.config.ts",
            ".secretlintrc.cjs",
            ".secretlintrc.js",
            "prettier.config.js",
            "package.json",
            "README.md",
        ],
        typescript: {
            tsconfigPath: "./tsconfig.eslint.json",
        },
    },
    {
        files: ["bench/**/*"],
        rules: {
            "func-style": "off",
            "import/extensions": "off",
            "import/no-unresolved": "off",
            "jsdoc/require-param-description": "off",
            "jsdoc/require-param-type": "off",
            "markdown/fenced-code-language": "off",
        },
    },
    {
        files: ["**/*.test.ts"],
        rules: {
            "@typescript-eslint/no-explicit-any": "off",
            "@typescript-eslint/no-throw-literal": "off",
            "@typescript-eslint/no-unsafe-assignment": "off",
            "@typescript-eslint/no-unsafe-call": "off",
            "@typescript-eslint/no-unsafe-member-access": "off",
            "@typescript-eslint/no-unsafe-return": "off",
            "@typescript-eslint/only-throw-error": "off",
            "@typescript-eslint/require-await": "off",
            "@typescript-eslint/restrict-template-expressions": "off",
            "@typescript-eslint/unbound-method": "off",
            "compat/compat": "off",
            "e18e/prefer-static-regex": "off",
            "no-secrets/no-secrets": "off",
            "security/detect-object-injection": "off",
            "security/detect-unsafe-regex": "off",
            "sonarjs/no-clear-text-protocols": "off",
            "sonarjs/no-commented-code": "off",
            "sonarjs/no-identical-functions": "off",
            "sonarjs/no-nested-functions": "off",
            "unicorn/no-null": "off",
            "unused-imports/no-unused-vars": "off",
        },
    },
    {
        files: ["./__tests__/unit/index.test.ts"],
        rules: {
            "@stylistic/no-tabs": "off",
            "sonarjs/no-tab": "off",
        },
    },
    {
        files: ["./src/**/*.ts"],
        rules: {
            "@stylistic/no-extra-parens": "off",
            "@typescript-eslint/no-confusing-void-expression": "off",
            "@typescript-eslint/no-explicit-any": "off",
            "@typescript-eslint/no-redundant-type-constituents": "off",
            "@typescript-eslint/no-unnecessary-type-parameters": "off",
            "@typescript-eslint/no-unsafe-return": "off",
            "@typescript-eslint/prefer-promise-reject-errors": "off",
            "@typescript-eslint/require-await": "off",
            "@typescript-eslint/restrict-template-expressions": "off",
            "compat/compat": "off",
            "import/no-namespace": "off",
            "jsdoc/match-description": "off",
            "no-confusing-arrow": "off",
            "no-for-of-array/no-for-of-array": "off",
            "no-loops/no-loops": "off",
            "no-useless-assignment": "off",
            "security/detect-object-injection": "off",
            "sonarjs/function-return-type": "off",
            "sonarjs/no-dead-store": "off",
            "unicorn/no-null": "off",
        },
    },
);
