import { createConfig } from "@anolilab/eslint-config";

/** @type {import("@anolilab/eslint-config").PromiseFlatConfigComposer} */
export default createConfig(
    {
        ignores: [
            "dist",
            "node_modules",
            "coverage",
            "__fixtures__",
            "__docs__",
            "__bench__",
            "vitest.config.ts",
            "packem.config.ts",
            ".secretlintrc.cjs",
            "prettier.config.js",
            "package.json",
            "README.md",
        ],
        typescript: {
            tsconfigPath: "./tsconfig.eslint.json",
        },
    },
    {
        files: ["**/*.test.ts"],
        rules: {
            "@stylistic/quotes": "off",
            "@typescript-eslint/no-explicit-any": "off",
            "@typescript-eslint/no-misused-spread": "off",
            "@typescript-eslint/no-unsafe-assignment": "off",
            "@typescript-eslint/no-unsafe-call": "off",
            "@typescript-eslint/no-unsafe-member-access": "off",
            "@typescript-eslint/no-unsafe-return": "off",
            "@typescript-eslint/require-await": "off",
            "@typescript-eslint/restrict-template-expressions": "off",
            "no-for-of-array/no-for-of-array": "off",
            "no-secrets/no-secrets": "off",
            "sonarjs/deprecation": "off",
            "sonarjs/no-nested-functions": "off",
            "unicorn/no-null": "off",
        },
    },
    {
        files: ["./__tests__/**/*.types.test.ts"],
        rules: {
            "sonarjs/assertions-in-tests": "off",
            "vitest/expect-expect": "off",
            "vitest/prefer-expect-assertions": "off",
        },
    },
    {
        files: ["./src/**/*.ts"],
        rules: {
            "@typescript-eslint/no-misused-spread": "off",
            "@typescript-eslint/no-necessary-condition": "off",
            "@typescript-eslint/no-unnecessary-condition": "off",
            "@typescript-eslint/no-unnecessary-type-assertion": "off",
            "@typescript-eslint/no-unnecessary-type-conversion": "off",
            "@typescript-eslint/no-unnecessary-type-parameters": "off",
            "@typescript-eslint/no-unsafe-argument": "off",
            "@typescript-eslint/no-unsafe-call": "off",
            "@typescript-eslint/no-unsafe-member-access": "off",
            "@typescript-eslint/no-unsafe-return": "off",
            "@typescript-eslint/prefer-nullish-coalescing": "off",
            "@typescript-eslint/restrict-plus-operands": "off",
            "@typescript-eslint/restrict-template-expressions": "off",
            "@typescript-eslint/unbound-method": "off",
            "jsdoc/match-description": "off",
            "jsdoc/no-undefined-types": "off",
            "no-for-of-array/no-for-of-array": "off",
            "no-param-reassign": "off",
            "no-secrets/no-secrets": "off",
            "sonarjs/function-return-type": "off",
            "sonarjs/prefer-regexp-exec": "off",
            "unicorn/prefer-default-parameters": "off",
        },
    },
);
