import type { WorkspaceConfiguration } from "@visulima/task-runner";

import type { CodeownersConfig, OwnersEntry, VisProjectConfiguration } from "../config/workspace";

export type { CodeownersConfig } from "../config/workspace";

/**
 * A single resolved CODEOWNERS line, pre-sorted by path. Kept as an
 * object so callers can post-process (e.g. append sub-sections).
 */
export interface CodeownersLine {
    /** Optional notification channel (added as a trailing comment). */
    channel?: string;
    /** Owner handles, space-separated by the writer. */
    owners: string[];
    /** Effective path glob (workspace-root-relative). */
    path: string;
    /** Source project name — used for `order-by=project-id` sorting. */
    projectId?: string;

    /**
     * Source tag — `project-json` lines win on path conflict over
     * `nested` and `maintainers` lines. Internal; not surfaced to
     * callers of the renderer.
     */
    source?: "maintainers" | "nested" | "project-json";
}

/**
 * Normalises an {@link OwnersEntry} path to be workspace-root-relative.
 * Owners entries live in project.json, so they are stated relative to
 * each project root. We prepend the project root to keep git-blame
 * matching simple.
 */
const toWorkspacePath = (projectRoot: string, entryPath: string): string => {
    const trimmed = entryPath.replace(/^\.?\//, "");

    if (trimmed === "" || trimmed === ".") {
        return `/${projectRoot}/`;
    }

    if (projectRoot === "" || projectRoot === ".") {
        return `/${trimmed}`;
    }

    return `/${projectRoot}/${trimmed}`;
};

/**
 * Computes CODEOWNERS lines from the workspace's projects and a
 * workspace-level `codeowners` block, optionally merged with
 * pre-resolved lines from other sources (nested CODEOWNERS files,
 * package.json maintainers).
 *
 * On path conflict, the `project-json` source wins. Extra-source
 * lines for paths already covered by project.json are dropped — this
 * keeps a forgotten nested CODEOWNERS file from shipping ghost owners.
 */
export const buildCodeownersLines = (
    workspace: WorkspaceConfiguration,
    config: CodeownersConfig | undefined,
    extraLines: ReadonlyArray<CodeownersLine> = [],
): CodeownersLine[] => {
    const lines: CodeownersLine[] = [];
    const claimedPaths = new Set<string>();

    for (const [globalPath, owners] of Object.entries(config?.globalPaths ?? {})) {
        lines.push({ owners, path: globalPath, source: "project-json" });
        claimedPaths.add(globalPath);
    }

    for (const [name, project] of Object.entries(workspace.projects) as [string, VisProjectConfiguration][]) {
        const ownersList: OwnersEntry[] = project.owners ?? [];

        for (const entry of ownersList) {
            const path = toWorkspacePath(project.root ?? name, entry.path);

            lines.push({
                channel: entry.channel,
                owners: entry.owners,
                path,
                projectId: name,
                source: "project-json",
            });
            claimedPaths.add(path);
        }
    }

    for (const extra of extraLines) {
        if (claimedPaths.has(extra.path)) {
            continue;
        }

        lines.push(extra);
        claimedPaths.add(extra.path);
    }

    const orderBy = config?.orderBy ?? "file-source";

    if (orderBy === "project-id") {
        lines.sort((a, b) => (a.projectId ?? "").localeCompare(b.projectId ?? "") || a.path.localeCompare(b.path));
    } else {
        lines.sort((a, b) => a.path.localeCompare(b.path));
    }

    return lines;
};

const DEFAULT_HEADER_INSTRUCTION = "Update each project's project.json `owners` field and re-run the command.";

const buildHeader = (regenerationCommand: string | undefined): string[] => {
    const second = regenerationCommand ? `# Re-run with: ${regenerationCommand}` : `# ${DEFAULT_HEADER_INSTRUCTION}`;

    return ["# CODEOWNERS — generated by `vis sync codeowners`. Do not edit by hand.", second, ""];
};

const renderEntries = (lines: ReadonlyArray<CodeownersLine>): string[] => {
    const out: string[] = [];

    for (const line of lines) {
        const owners = line.owners.join(" ");
        const channel = line.channel ? `    # notify: ${line.channel}` : "";

        out.push(`${line.path} ${owners}${channel}`);
    }

    return out;
};

export interface RenderOptions {
    /** Overrides the "Update each project's project.json…" header line. */
    regenerationCommand?: string;
}

/**
 * Serialises {@link CodeownersLine}s to a valid CODEOWNERS file string.
 * @param lines Resolved CODEOWNERS lines.
 * @param options Optional renderer overrides (e.g. `regenerationCommand`).
 * @returns The full CODEOWNERS file content with header and trailing newline.
 */
export const renderCodeowners = (lines: ReadonlyArray<CodeownersLine>, options: RenderOptions = {}): string =>
    [...buildHeader(options.regenerationCommand), ...renderEntries(lines), ""].join("\n");

/** Default markers used by `mergeIntoExisting`. */
export const DEFAULT_BLOCK_MARKER = {
    begin: "# BEGIN vis-codeowners",
    end: "# END vis-codeowners",
} as const;

/**
 * Renders just the marker-bracketed block (no top-level header). Used
 * by `preserveBlock` mode to embed a generated section inside a
 * hand-maintained CODEOWNERS file.
 */
export const renderCodeownersBlock = (
    lines: ReadonlyArray<CodeownersLine>,
    marker: { begin: string; end: string } = DEFAULT_BLOCK_MARKER,
    options: RenderOptions = {},
): string => {
    const headerNote = options.regenerationCommand
        ? `# Generated by vis sync codeowners — re-run with: ${options.regenerationCommand}`
        : "# Generated by `vis sync codeowners` — do not edit by hand.";

    return [marker.begin, headerNote, ...renderEntries(lines), marker.end].join("\n");
};

/**
 * Splices a block into an existing CODEOWNERS file body. If markers
 * are present, the content between them (inclusive) is replaced.
 * Otherwise the block is appended after a blank line. The trailing
 * newline is preserved.
 */
export const mergeIntoExisting = (existing: string, block: string, marker: { begin: string; end: string } = DEFAULT_BLOCK_MARKER): string => {
    const beginIndex = existing.indexOf(marker.begin);
    const endIndex = existing.indexOf(marker.end);

    if (beginIndex !== -1 && endIndex !== -1 && endIndex > beginIndex) {
        const before = existing.slice(0, beginIndex);
        const afterStart = endIndex + marker.end.length;
        const after = existing.slice(afterStart);

        return `${before}${block}${after}`;
    }

    const trimmed = existing.replace(/\s+$/u, "");
    const prefix = trimmed.length === 0 ? "" : `${trimmed}\n\n`;

    return `${prefix}${block}\n`;
};
