import type { WorkspaceConfiguration } from "@visulima/task-runner";

import type { CodeownersConfig, OwnersEntry, VisProjectConfiguration } from "../config/workspace";

export type { CodeownersConfig } from "../config/workspace";

/**
 * A single resolved CODEOWNERS line, pre-sorted by path. Kept as an
 * object so callers can post-process (e.g. append sub-sections).
 */
export interface CodeownersLine {
    /** Optional notification channel (added as a trailing comment). */
    channel?: string;
    /** Owner handles, space-separated by the writer. */
    owners: string[];
    /** Effective path glob (workspace-root-relative). */
    path: string;
    /** Source project name — used for `order-by=project-id` sorting. */
    projectId?: string;
}

/**
 * Normalises an {@link OwnersEntry} path to be workspace-root-relative.
 * Owners entries live in project.json, so they are stated relative to
 * each project root. We prepend the project root to keep git-blame
 * matching simple.
 */
const toWorkspacePath = (projectRoot: string, entryPath: string): string => {
    const trimmed = entryPath.replace(/^\.?\//, "");

    if (trimmed === "" || trimmed === ".") {
        return `/${projectRoot}/`;
    }

    if (projectRoot === "" || projectRoot === ".") {
        return `/${trimmed}`;
    }

    return `/${projectRoot}/${trimmed}`;
};

/**
 * Computes CODEOWNERS lines from the workspace's projects and a
 * workspace-level `codeowners` block. Returns lines in the requested
 * order (default: `file-source`).
 */
export const buildCodeownersLines = (workspace: WorkspaceConfiguration, config: CodeownersConfig | undefined): CodeownersLine[] => {
    const lines: CodeownersLine[] = [];

    for (const [globalPath, owners] of Object.entries(config?.globalPaths ?? {})) {
        lines.push({ owners, path: globalPath });
    }

    for (const [name, project] of Object.entries(workspace.projects) as [string, VisProjectConfiguration][]) {
        const ownersList: OwnersEntry[] = project.owners ?? [];

        for (const entry of ownersList) {
            lines.push({
                channel: entry.channel,
                owners: entry.owners,
                path: toWorkspacePath(project.root ?? name, entry.path),
                projectId: name,
            });
        }
    }

    const orderBy = config?.orderBy ?? "file-source";

    if (orderBy === "project-id") {
        lines.sort((a, b) => (a.projectId ?? "").localeCompare(b.projectId ?? "") || a.path.localeCompare(b.path));
    } else {
        lines.sort((a, b) => a.path.localeCompare(b.path));
    }

    return lines;
};

const HEADER_LINES = [
    "# CODEOWNERS — generated by `vis sync codeowners`. Do not edit by hand.",
    "# Update each project's project.json `owners` field and re-run the command.",
    "",
];

/**
 * Serialises {@link CodeownersLine}s to a valid CODEOWNERS file string.
 * @param lines Resolved CODEOWNERS lines.
 * @param _provider Reserved for future provider-specific formatting (e.g. Bitbucket syntax).
 * @returns The full CODEOWNERS file content with header and trailing newline.
 */
export const renderCodeowners = (lines: CodeownersLine[], _provider: CodeownersConfig["provider"] = "github"): string => {
    const out: string[] = [...HEADER_LINES];

    for (const line of lines) {
        const owners = line.owners.join(" ");
        const channel = line.channel ? `    # notify: ${line.channel}` : "";

        out.push(`${line.path} ${owners}${channel}`);
    }

    out.push("");

    return out.join("\n");
};
