/**
 * Multi-stage Dockerfile generator for `vis docker init`.
 *
 * Emits a Dockerfile wired to the `vis docker scaffold` / `vis docker
 * prune` flow: a `deps` stage that installs from the scaffolded workspace
 * (so the install layer caches on manifest changes only), a `build` stage
 * that compiles the focus project and prunes unfocused projects, and a
 * slim `runtime` stage. The output is a starting point — the runtime
 * CMD is a placeholder the user is expected to tailor.
 */

import type { LockfilePackageManager } from "../preflight/lockfile";

export interface GenerateDockerfileOptions {
    /** Focus project name (for the build filter); omitted → generic build. */
    focus?: string;
    /** Package manager driving install/build commands. */
    manager: LockfilePackageManager;
    /** Node.js major version tag, e.g. "22". */
    nodeVersion: string;
}

interface ManagerCommands {
    /** Lines for the shared base stage (corepack, env). */
    base: string[];
    /** Build command for the focus project. */
    build: (focus: string | undefined) => string;
    /** Frozen install command. */
    install: string;
}

const MANAGER_COMMANDS: Record<LockfilePackageManager, ManagerCommands> = {
    aube: {
        base: ["RUN corepack enable"],
        build: (focus) => (focus ? `RUN aube run --filter ${focus} build` : "RUN aube run build"),
        install: "RUN aube install --frozen-lockfile",
    },
    bun: {
        base: ["RUN npm install -g bun"],
        build: (focus) => (focus ? `RUN bun run --filter ${focus} build` : "RUN bun run build"),
        install: "RUN --mount=type=cache,target=/root/.bun/install/cache bun install --frozen-lockfile",
    },
    npm: {
        base: [],
        build: (focus) => (focus ? `RUN npm run build --workspace ${focus}` : "RUN npm run build"),
        install: "RUN --mount=type=cache,target=/root/.npm npm ci",
    },
    pnpm: {
        base: ["ENV PNPM_HOME=/pnpm", "ENV PATH=$PNPM_HOME:$PATH", "RUN corepack enable"],
        build: (focus) => (focus ? `RUN pnpm --filter ${focus} build` : "RUN pnpm build"),
        install: "RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile",
    },
    yarn: {
        base: ["RUN corepack enable"],
        build: (focus) => (focus ? `RUN yarn workspace ${focus} build` : "RUN yarn build"),
        install: "RUN --mount=type=cache,target=/usr/local/share/.cache/yarn yarn install --immutable",
    },
};

/**
 * Generates a multi-stage Dockerfile as a string.
 * @param options Generator inputs.
 */
export const generateDockerfile = (options: GenerateDockerfileOptions): string => {
    const { focus, manager, nodeVersion } = options;
    const commands = MANAGER_COMMANDS[manager] ?? MANAGER_COMMANDS.npm;

    const focusComment = focus ? ` --focus=${focus}` : "";

    const lines: string[] = [
        "# syntax=docker/dockerfile:1",
        "",
        `# Generated by 'vis docker init'. Before building, scaffold the context:`,
        `#   vis docker scaffold${focusComment} --include-sources`,
        "# then build with BuildKit enabled (DOCKER_BUILDKIT=1).",
        "",
        `FROM node:${nodeVersion}-slim AS base`,
        "WORKDIR /app",
        ...commands.base,
        "",
        "# --- install dependencies from the scaffolded manifests only ---",
        "FROM base AS deps",
        "COPY .vis/docker/workspace/ ./",
        commands.install,
        "",
        "# --- build the focus project, then drop unfocused workspace projects ---",
        "FROM deps AS build",
        "COPY .vis/docker/sources/ ./",
        commands.build(focus),
        "RUN npx vis docker prune --context=.vis/docker",
        "",
        "# --- minimal runtime image ---",
        `FROM node:${nodeVersion}-slim AS runtime`,
        "WORKDIR /app",
        "ENV NODE_ENV=production",
        "COPY --from=build /app ./",
        "USER node",
        "# TODO: point this at your app's entrypoint",
        `CMD ["node", "index.js"]`,
        "",
    ];

    return lines.join("\n");
};
