/**
 * Write Guard generators.
 *
 * `vis sync codeowners --write-guard` emits CI for projects flagged
 * `restricted: true` in their project.json. Two artefacts are produced
 * so the guard works on both forges, with deliberately different
 * enforcement strength:
 *
 *  - GitHub: `.github/workflows/write-guard.yml` — a **hard gate**.
 *    Uses the existing `geritol/write-guard` action, which reads the
 *    repo CODEOWNERS and fails the PR check when a restricted path
 *    changed without code-owner approval.
 *  - GitLab: `.gitlab/write-guard.gitlab-ci.yml` — a **soft guard**.
 *    CI cannot portably gate a merge on code-owner *approval*, so the
 *    job only verifies CODEOWNERS freshness and loudly states (in a
 *    file header comment and its own log output) that real
 *    enforcement requires GitLab's native protected-branch "Require
 *    approval from Code Owners" setting.
 *
 * Both are scoped to restricted project roots so unrelated changes
 * are never blocked.
 */

/** A project that opted into Write Guard via `restricted: true`. */
export interface RestrictedProject {
    /** Project name (used only for stable ordering). */
    name: string;
    /** Workspace-root-relative project directory. */
    root: string;
}

const GENERATED_NOTE = "Generated by `vis sync codeowners --write-guard`. Do not edit by hand.";

/**
 * Normalises a project root to a forge path glob. Roots are stored
 * workspace-relative and may be `.`; everything maps to a `&lt;root>/**`
 * recursive glob with no leading slash.
 */
const toPathGlob = (root: string): string => {
    const trimmed = root.replace(/^\.?\/+/u, "").replace(/\/+$/u, "");

    return trimmed === "" || trimmed === "." ? "**" : `${trimmed}/**`;
};

/**
 * Sorts restricted projects by name and resolves their path globs,
 * deduplicating identical globs (two projects can share a root).
 */
const resolveGlobs = (projects: ReadonlyArray<RestrictedProject>): string[] => {
    const seen = new Set<string>();
    const globs: string[] = [];

    for (const project of [...projects].sort((a, b) => a.name.localeCompare(b.name))) {
        const glob = toPathGlob(project.root);

        if (seen.has(glob)) {
            continue;
        }

        seen.add(glob);
        globs.push(glob);
    }

    return globs;
};

/**
 * Renders the GitHub Actions Write Guard workflow. Triggers only on
 * pull requests that touch a restricted path and delegates the actual
 * ownership check to `geritol/write-guard`, which reads the repo's
 * CODEOWNERS (kept fresh by `vis sync codeowners`).
 */
export const renderGithubWriteGuard = (projects: ReadonlyArray<RestrictedProject>): string => {
    const globs = resolveGlobs(projects);
    const pathLines = globs.map((glob) => `      - "${glob}"`).join("\n");
    const guardLines = globs.map((glob) => `            ${glob}`).join("\n");

    return `# ${GENERATED_NOTE}
name: Write Guard

on:
  pull_request:
    paths:
${pathLines}

permissions:
  contents: read
  pull-requests: read

jobs:
  write-guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: geritol/write-guard@v1
        with:
          codeowners: CODEOWNERS
          paths: |
${guardLines}
`;
};

/**
 * Renders an includable GitLab CI job.
 *
 * Unlike the GitHub side (a hard gate via `geritol/write-guard`), this
 * is a deliberate **soft guard**: GitLab CI cannot portably gate a
 * merge on code-owner *approval* from a job (it needs an API-scoped
 * token and a pipeline that re-runs on approval). So the job only
 * verifies the repo CODEOWNERS is in sync and loudly states that real
 * enforcement requires GitLab's native protected-branch "Require
 * approval from Code Owners" setting. The generated file says this
 * prominently in a header comment **and** in the job's own log output
 * so it can't be silently mistaken for a blocking check.
 *
 * `include` this file from `.gitlab-ci.yml` and enable the native
 * setting for full enforcement.
 */
export const renderGitlabWriteGuard = (projects: ReadonlyArray<RestrictedProject>): string => {
    const globs = resolveGlobs(projects);
    // `toPathGlob` already appends `/**`. GitHub treats `**` as
    // recursive on its own, but GitLab `rules:changes` globs need an
    // explicit trailing `/*` segment after `**` to match files at any
    // depth, so the GitLab glob is `<root>/**/*` not just `<root>/**`.
    const changeLines = globs.map((glob) => `        - "${glob}/*"`).join("\n");

    return `# ${GENERATED_NOTE}
#
# SOFT GUARD ONLY — this job does NOT block a merge by itself.
# It verifies the generated CODEOWNERS is in sync and flags that a
# restricted path changed. GitLab CI cannot portably gate a merge on
# code-owner *approval* from a job, so REAL ENFORCEMENT REQUIRES the
# native GitLab setting:
#   Settings -> Repository -> Protected branches ->
#   "Require approval from Code Owners"  (GitLab Premium / Ultimate)
#   https://docs.gitlab.com/ee/user/project/codeowners/
# Without that setting enabled, this job is advisory only.
write-guard:
  stage: test
  image: node:22-alpine
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
${changeLines}
  script:
    - corepack enable
    - pnpm install --frozen-lockfile
    - pnpm vis sync codeowners --check
    - >-
      echo "SOFT GUARD: a restricted path changed. This job does NOT enforce
      code-owner approval. Enable 'Require approval from Code Owners' on the
      protected branch (GitLab Premium/Ultimate) for a real merge gate:
      https://docs.gitlab.com/ee/user/project/codeowners/"
`;
};

export interface WriteGuardArtifact {
    /** Rendered file content. */
    content: string;
    /** Workspace-root-relative output path. */
    path: string;
}

/**
 * Produces both Write Guard artefacts for the given restricted
 * projects. Returns an empty list when nothing is restricted so the
 * caller can no-op cleanly.
 */
export const buildWriteGuardArtifacts = (projects: ReadonlyArray<RestrictedProject>): WriteGuardArtifact[] => {
    if (projects.length === 0) {
        return [];
    }

    return [
        { content: renderGithubWriteGuard(projects), path: ".github/workflows/write-guard.yml" },
        { content: renderGitlabWriteGuard(projects), path: ".gitlab/write-guard.gitlab-ci.yml" },
    ];
};
