/**
 * Write Guard generators.
 *
 * `vis sync codeowners --write-guard` emits CI that fails a pull /
 * merge request when a project flagged `restricted: true` in its
 * project.json is touched without going through its CODEOWNERS. Two
 * artefacts are produced so the guard works on both forges:
 *
 *  - GitHub: `.github/workflows/write-guard.yml` (uses the existing
 *    `geritol/write-guard` action, which reads the repo CODEOWNERS).
 *  - GitLab: `.gitlab/write-guard.gitlab-ci.yml`, an includable job
 *    that gates merge requests touching restricted paths.
 *
 * Both are scoped to restricted project roots so unrelated changes
 * are never blocked.
 */

/** A project that opted into Write Guard via `restricted: true`. */
export interface RestrictedProject {
    /** Project name (used only for stable ordering). */
    name: string;
    /** Workspace-root-relative project directory. */
    root: string;
}

const GENERATED_NOTE = "Generated by `vis sync codeowners --write-guard`. Do not edit by hand.";

/**
 * Normalises a project root to a forge path glob. Roots are stored
 * workspace-relative and may be `.`; everything maps to a `&lt;root>/**`
 * recursive glob with no leading slash.
 */
const toPathGlob = (root: string): string => {
    const trimmed = root.replace(/^\.?\/+/u, "").replace(/\/+$/u, "");

    return trimmed === "" || trimmed === "." ? "**" : `${trimmed}/**`;
};

/**
 * Sorts restricted projects by name and resolves their path globs,
 * deduplicating identical globs (two projects can share a root).
 */
const resolveGlobs = (projects: ReadonlyArray<RestrictedProject>): string[] => {
    const seen = new Set<string>();
    const globs: string[] = [];

    for (const project of [...projects].sort((a, b) => a.name.localeCompare(b.name))) {
        const glob = toPathGlob(project.root);

        if (seen.has(glob)) {
            continue;
        }

        seen.add(glob);
        globs.push(glob);
    }

    return globs;
};

/**
 * Renders the GitHub Actions Write Guard workflow. Triggers only on
 * pull requests that touch a restricted path and delegates the actual
 * ownership check to `geritol/write-guard`, which reads the repo's
 * CODEOWNERS (kept fresh by `vis sync codeowners`).
 */
export const renderGithubWriteGuard = (projects: ReadonlyArray<RestrictedProject>): string => {
    const globs = resolveGlobs(projects);
    const pathLines = globs.map((glob) => `      - "${glob}"`).join("\n");
    const guardLines = globs.map((glob) => `            ${glob}`).join("\n");

    return `# ${GENERATED_NOTE}
name: Write Guard

on:
  pull_request:
    paths:
${pathLines}

permissions:
  contents: read
  pull-requests: read

jobs:
  write-guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: geritol/write-guard@v1
        with:
          codeowners: CODEOWNERS
          paths: |
${guardLines}
`;
};

/**
 * Renders an includable GitLab CI job. GitLab has no `geritol`
 * equivalent, so the job enforces what CI portably can: on merge
 * requests touching a restricted path it verifies the repo CODEOWNERS
 * is in sync (owners cannot be silently dropped) and prints the
 * native CODEOWNERS approval requirement so reviewers don't bypass it.
 *
 * `include` this file from `.gitlab-ci.yml` and pair it with a
 * protected-branch CODEOWNERS approval rule for full enforcement.
 */
export const renderGitlabWriteGuard = (projects: ReadonlyArray<RestrictedProject>): string => {
    const globs = resolveGlobs(projects);
    // `toPathGlob` already appends `/**`. GitHub treats `**` as
    // recursive on its own, but GitLab `rules:changes` globs need an
    // explicit trailing `/*` segment after `**` to match files at any
    // depth, so the GitLab glob is `<root>/**/*` not just `<root>/**`.
    const changeLines = globs.map((glob) => `        - "${glob}/*"`).join("\n");

    return `# ${GENERATED_NOTE}
write-guard:
  stage: test
  image: node:22-alpine
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
${changeLines}
  script:
    - corepack enable
    - pnpm install --frozen-lockfile
    - pnpm vis sync codeowners --check
    - >-
      echo "Restricted paths changed. A CODEOWNERS approval is required to merge."
`;
};

export interface WriteGuardArtifact {
    /** Rendered file content. */
    content: string;
    /** Workspace-root-relative output path. */
    path: string;
}

/**
 * Produces both Write Guard artefacts for the given restricted
 * projects. Returns an empty list when nothing is restricted so the
 * caller can no-op cleanly.
 */
export const buildWriteGuardArtifacts = (projects: ReadonlyArray<RestrictedProject>): WriteGuardArtifact[] => {
    if (projects.length === 0) {
        return [];
    }

    return [
        { content: renderGithubWriteGuard(projects), path: ".github/workflows/write-guard.yml" },
        { content: renderGitlabWriteGuard(projects), path: ".gitlab/write-guard.gitlab-ci.yml" },
    ];
};
