// This file is auto-generated by the generate-charmap.js script.
// Do not edit this file manually.

import type { Charmap } from "../types";
import UNICODE_BLOCK_0000_00FF from "./block-0000-00ff";
import UNICODE_BLOCK_0100_01FF from "./block-0100-01ff";
import UNICODE_BLOCK_0200_02FF from "./block-0200-02ff";
import UNICODE_BLOCK_0300_03FF from "./block-0300-03ff";
import UNICODE_BLOCK_0400_04FF from "./block-0400-04ff";
import UNICODE_BLOCK_0500_05FF from "./block-0500-05ff";
import UNICODE_BLOCK_0600_06FF from "./block-0600-06ff";
import UNICODE_BLOCK_0700_07FF from "./block-0700-07ff";
import UNICODE_BLOCK_0800_08FF from "./block-0800-08ff";
import UNICODE_BLOCK_0900_09FF from "./block-0900-09ff";
import UNICODE_BLOCK_0A00_0AFF from "./block-0a00-0aff";
import UNICODE_BLOCK_0B00_0BFF from "./block-0b00-0bff";
import UNICODE_BLOCK_0C00_0CFF from "./block-0c00-0cff";
import UNICODE_BLOCK_0D00_0DFF from "./block-0d00-0dff";
import UNICODE_BLOCK_0E00_0EFF from "./block-0e00-0eff";
import UNICODE_BLOCK_0F00_0FFF from "./block-0f00-0fff";
import UNICODE_BLOCK_1000_10FF from "./block-1000-10ff";
import UNICODE_BLOCK_1100_11FF from "./block-1100-11ff";
import UNICODE_BLOCK_1200_12FF from "./block-1200-12ff";
import UNICODE_BLOCK_1300_13FF from "./block-1300-13ff";
import UNICODE_BLOCK_1400_14FF from "./block-1400-14ff";
import UNICODE_BLOCK_1500_15FF from "./block-1500-15ff";
import UNICODE_BLOCK_1600_16FF from "./block-1600-16ff";
import UNICODE_BLOCK_1700_17FF from "./block-1700-17ff";
import UNICODE_BLOCK_1800_18FF from "./block-1800-18ff";
import UNICODE_BLOCK_1900_19FF from "./block-1900-19ff";
import UNICODE_BLOCK_1A00_1AFF from "./block-1a00-1aff";
import UNICODE_BLOCK_1B00_1BFF from "./block-1b00-1bff";
import UNICODE_BLOCK_1C00_1CFF from "./block-1c00-1cff";
import UNICODE_BLOCK_1D00_1DFF from "./block-1d00-1dff";
import UNICODE_BLOCK_1E00_1EFF from "./block-1e00-1eff";
import UNICODE_BLOCK_1F00_1FFF from "./block-1f00-1fff";
import UNICODE_BLOCK_2000_20FF from "./block-2000-20ff";
import UNICODE_BLOCK_2100_21FF from "./block-2100-21ff";
import UNICODE_BLOCK_2200_22FF from "./block-2200-22ff";
import UNICODE_BLOCK_2300_23FF from "./block-2300-23ff";
import UNICODE_BLOCK_2400_24FF from "./block-2400-24ff";
import UNICODE_BLOCK_2500_25FF from "./block-2500-25ff";
import UNICODE_BLOCK_2600_26FF from "./block-2600-26ff";
import UNICODE_BLOCK_2700_27FF from "./block-2700-27ff";
import UNICODE_BLOCK_2800_28FF from "./block-2800-28ff";
import UNICODE_BLOCK_2900_29FF from "./block-2900-29ff";
import UNICODE_BLOCK_2A00_2AFF from "./block-2a00-2aff";
import UNICODE_BLOCK_2B00_2BFF from "./block-2b00-2bff";
import UNICODE_BLOCK_2C00_2CFF from "./block-2c00-2cff";
import UNICODE_BLOCK_2D00_2DFF from "./block-2d00-2dff";
import UNICODE_BLOCK_2E00_2EFF from "./block-2e00-2eff";
import UNICODE_BLOCK_2F00_2FFF from "./block-2f00-2fff";
import UNICODE_BLOCK_3000_30FF from "./block-3000-30ff";
import UNICODE_BLOCK_3100_31FF from "./block-3100-31ff";
import UNICODE_BLOCK_3200_32FF from "./block-3200-32ff";
import UNICODE_BLOCK_3300_33FF from "./block-3300-33ff";
import UNICODE_BLOCK_3400_34FF from "./block-3400-34ff";
import UNICODE_BLOCK_3500_35FF from "./block-3500-35ff";
import UNICODE_BLOCK_3600_36FF from "./block-3600-36ff";
import UNICODE_BLOCK_3700_37FF from "./block-3700-37ff";
import UNICODE_BLOCK_3800_38FF from "./block-3800-38ff";
import UNICODE_BLOCK_3900_39FF from "./block-3900-39ff";
import UNICODE_BLOCK_3A00_3AFF from "./block-3a00-3aff";
import UNICODE_BLOCK_3B00_3BFF from "./block-3b00-3bff";
import UNICODE_BLOCK_3C00_3CFF from "./block-3c00-3cff";
import UNICODE_BLOCK_3D00_3DFF from "./block-3d00-3dff";
import UNICODE_BLOCK_3E00_3EFF from "./block-3e00-3eff";
import UNICODE_BLOCK_3F00_3FFF from "./block-3f00-3fff";
import UNICODE_BLOCK_4000_40FF from "./block-4000-40ff";
import UNICODE_BLOCK_4100_41FF from "./block-4100-41ff";
import UNICODE_BLOCK_4200_42FF from "./block-4200-42ff";
import UNICODE_BLOCK_4300_43FF from "./block-4300-43ff";
import UNICODE_BLOCK_4400_44FF from "./block-4400-44ff";
import UNICODE_BLOCK_4500_45FF from "./block-4500-45ff";
import UNICODE_BLOCK_4600_46FF from "./block-4600-46ff";
import UNICODE_BLOCK_4700_47FF from "./block-4700-47ff";
import UNICODE_BLOCK_4800_48FF from "./block-4800-48ff";
import UNICODE_BLOCK_4900_49FF from "./block-4900-49ff";
import UNICODE_BLOCK_4A00_4AFF from "./block-4a00-4aff";
import UNICODE_BLOCK_4B00_4BFF from "./block-4b00-4bff";
import UNICODE_BLOCK_4C00_4CFF from "./block-4c00-4cff";
import UNICODE_BLOCK_4D00_4DFF from "./block-4d00-4dff";
import UNICODE_BLOCK_4E00_4EFF from "./block-4e00-4eff";
import UNICODE_BLOCK_4F00_4FFF from "./block-4f00-4fff";
import UNICODE_BLOCK_5000_50FF from "./block-5000-50ff";
import UNICODE_BLOCK_5100_51FF from "./block-5100-51ff";
import UNICODE_BLOCK_5200_52FF from "./block-5200-52ff";
import UNICODE_BLOCK_5300_53FF from "./block-5300-53ff";
import UNICODE_BLOCK_5400_54FF from "./block-5400-54ff";
import UNICODE_BLOCK_5500_55FF from "./block-5500-55ff";
import UNICODE_BLOCK_5600_56FF from "./block-5600-56ff";
import UNICODE_BLOCK_5700_57FF from "./block-5700-57ff";
import UNICODE_BLOCK_5800_58FF from "./block-5800-58ff";
import UNICODE_BLOCK_5900_59FF from "./block-5900-59ff";
import UNICODE_BLOCK_5A00_5AFF from "./block-5a00-5aff";
import UNICODE_BLOCK_5B00_5BFF from "./block-5b00-5bff";
import UNICODE_BLOCK_5C00_5CFF from "./block-5c00-5cff";
import UNICODE_BLOCK_5D00_5DFF from "./block-5d00-5dff";
import UNICODE_BLOCK_5E00_5EFF from "./block-5e00-5eff";
import UNICODE_BLOCK_5F00_5FFF from "./block-5f00-5fff";
import UNICODE_BLOCK_6000_60FF from "./block-6000-60ff";
import UNICODE_BLOCK_6100_61FF from "./block-6100-61ff";
import UNICODE_BLOCK_6200_62FF from "./block-6200-62ff";
import UNICODE_BLOCK_6300_63FF from "./block-6300-63ff";
import UNICODE_BLOCK_6400_64FF from "./block-6400-64ff";
import UNICODE_BLOCK_6500_65FF from "./block-6500-65ff";
import UNICODE_BLOCK_6600_66FF from "./block-6600-66ff";
import UNICODE_BLOCK_6700_67FF from "./block-6700-67ff";
import UNICODE_BLOCK_6800_68FF from "./block-6800-68ff";
import UNICODE_BLOCK_6900_69FF from "./block-6900-69ff";
import UNICODE_BLOCK_6A00_6AFF from "./block-6a00-6aff";
import UNICODE_BLOCK_6B00_6BFF from "./block-6b00-6bff";
import UNICODE_BLOCK_6C00_6CFF from "./block-6c00-6cff";
import UNICODE_BLOCK_6D00_6DFF from "./block-6d00-6dff";
import UNICODE_BLOCK_6E00_6EFF from "./block-6e00-6eff";
import UNICODE_BLOCK_6F00_6FFF from "./block-6f00-6fff";
import UNICODE_BLOCK_7000_70FF from "./block-7000-70ff";
import UNICODE_BLOCK_7100_71FF from "./block-7100-71ff";
import UNICODE_BLOCK_7200_72FF from "./block-7200-72ff";
import UNICODE_BLOCK_7300_73FF from "./block-7300-73ff";
import UNICODE_BLOCK_7400_74FF from "./block-7400-74ff";
import UNICODE_BLOCK_7500_75FF from "./block-7500-75ff";
import UNICODE_BLOCK_7600_76FF from "./block-7600-76ff";
import UNICODE_BLOCK_7700_77FF from "./block-7700-77ff";
import UNICODE_BLOCK_7800_78FF from "./block-7800-78ff";
import UNICODE_BLOCK_7900_79FF from "./block-7900-79ff";
import UNICODE_BLOCK_7A00_7AFF from "./block-7a00-7aff";
import UNICODE_BLOCK_7B00_7BFF from "./block-7b00-7bff";
import UNICODE_BLOCK_7C00_7CFF from "./block-7c00-7cff";
import UNICODE_BLOCK_7D00_7DFF from "./block-7d00-7dff";
import UNICODE_BLOCK_7E00_7EFF from "./block-7e00-7eff";
import UNICODE_BLOCK_7F00_7FFF from "./block-7f00-7fff";
import UNICODE_BLOCK_8000_80FF from "./block-8000-80ff";
import UNICODE_BLOCK_8100_81FF from "./block-8100-81ff";
import UNICODE_BLOCK_8200_82FF from "./block-8200-82ff";
import UNICODE_BLOCK_8300_83FF from "./block-8300-83ff";
import UNICODE_BLOCK_8400_84FF from "./block-8400-84ff";
import UNICODE_BLOCK_8500_85FF from "./block-8500-85ff";
import UNICODE_BLOCK_8600_86FF from "./block-8600-86ff";
import UNICODE_BLOCK_8700_87FF from "./block-8700-87ff";
import UNICODE_BLOCK_8800_88FF from "./block-8800-88ff";
import UNICODE_BLOCK_8900_89FF from "./block-8900-89ff";
import UNICODE_BLOCK_8A00_8AFF from "./block-8a00-8aff";
import UNICODE_BLOCK_8B00_8BFF from "./block-8b00-8bff";
import UNICODE_BLOCK_8C00_8CFF from "./block-8c00-8cff";
import UNICODE_BLOCK_8D00_8DFF from "./block-8d00-8dff";
import UNICODE_BLOCK_8E00_8EFF from "./block-8e00-8eff";
import UNICODE_BLOCK_8F00_8FFF from "./block-8f00-8fff";
import UNICODE_BLOCK_9000_90FF from "./block-9000-90ff";
import UNICODE_BLOCK_9100_91FF from "./block-9100-91ff";
import UNICODE_BLOCK_9200_92FF from "./block-9200-92ff";
import UNICODE_BLOCK_9300_93FF from "./block-9300-93ff";
import UNICODE_BLOCK_9400_94FF from "./block-9400-94ff";
import UNICODE_BLOCK_9500_95FF from "./block-9500-95ff";
import UNICODE_BLOCK_9600_96FF from "./block-9600-96ff";
import UNICODE_BLOCK_9700_97FF from "./block-9700-97ff";
import UNICODE_BLOCK_9800_98FF from "./block-9800-98ff";
import UNICODE_BLOCK_9900_99FF from "./block-9900-99ff";
import UNICODE_BLOCK_9A00_9AFF from "./block-9a00-9aff";
import UNICODE_BLOCK_9B00_9BFF from "./block-9b00-9bff";
import UNICODE_BLOCK_9C00_9CFF from "./block-9c00-9cff";
import UNICODE_BLOCK_9D00_9DFF from "./block-9d00-9dff";
import UNICODE_BLOCK_9E00_9EFF from "./block-9e00-9eff";
import UNICODE_BLOCK_9F00_9FFF from "./block-9f00-9fff";
import UNICODE_BLOCK_A000_A0FF from "./block-a000-a0ff";
import UNICODE_BLOCK_A100_A1FF from "./block-a100-a1ff";
import UNICODE_BLOCK_A200_A2FF from "./block-a200-a2ff";
import UNICODE_BLOCK_A300_A3FF from "./block-a300-a3ff";
import UNICODE_BLOCK_A400_A4FF from "./block-a400-a4ff";
import UNICODE_BLOCK_A500_A5FF from "./block-a500-a5ff";
import UNICODE_BLOCK_A600_A6FF from "./block-a600-a6ff";
import UNICODE_BLOCK_A700_A7FF from "./block-a700-a7ff";
import UNICODE_BLOCK_A800_A8FF from "./block-a800-a8ff";
import UNICODE_BLOCK_A900_A9FF from "./block-a900-a9ff";
import UNICODE_BLOCK_AA00_AAFF from "./block-aa00-aaff";
import UNICODE_BLOCK_AB00_ABFF from "./block-ab00-abff";
import UNICODE_BLOCK_AC00_ACFF from "./block-ac00-acff";
import UNICODE_BLOCK_AD00_ADFF from "./block-ad00-adff";
import UNICODE_BLOCK_AE00_AEFF from "./block-ae00-aeff";
import UNICODE_BLOCK_AF00_AFFF from "./block-af00-afff";

let unicodeBlocks: undefined | (string | undefined)[][] = [
    UNICODE_BLOCK_0000_00FF,
    UNICODE_BLOCK_0100_01FF,
    UNICODE_BLOCK_0200_02FF,
    UNICODE_BLOCK_0300_03FF,
    UNICODE_BLOCK_0400_04FF,
    UNICODE_BLOCK_0500_05FF,
    UNICODE_BLOCK_0600_06FF,
    UNICODE_BLOCK_0700_07FF,
    UNICODE_BLOCK_0800_08FF,
    UNICODE_BLOCK_0900_09FF,
    UNICODE_BLOCK_0A00_0AFF,
    UNICODE_BLOCK_0B00_0BFF,
    UNICODE_BLOCK_0C00_0CFF,
    UNICODE_BLOCK_0D00_0DFF,
    UNICODE_BLOCK_0E00_0EFF,
    UNICODE_BLOCK_0F00_0FFF,
    UNICODE_BLOCK_1000_10FF,
    UNICODE_BLOCK_1100_11FF,
    UNICODE_BLOCK_1200_12FF,
    UNICODE_BLOCK_1300_13FF,
    UNICODE_BLOCK_1400_14FF,
    UNICODE_BLOCK_1500_15FF,
    UNICODE_BLOCK_1600_16FF,
    UNICODE_BLOCK_1700_17FF,
    UNICODE_BLOCK_1800_18FF,
    UNICODE_BLOCK_1900_19FF,
    UNICODE_BLOCK_1A00_1AFF,
    UNICODE_BLOCK_1B00_1BFF,
    UNICODE_BLOCK_1C00_1CFF,
    UNICODE_BLOCK_1D00_1DFF,
    UNICODE_BLOCK_1E00_1EFF,
    UNICODE_BLOCK_1F00_1FFF,
    UNICODE_BLOCK_2000_20FF,
    UNICODE_BLOCK_2100_21FF,
    UNICODE_BLOCK_2200_22FF,
    UNICODE_BLOCK_2300_23FF,
    UNICODE_BLOCK_2400_24FF,
    UNICODE_BLOCK_2500_25FF,
    UNICODE_BLOCK_2600_26FF,
    UNICODE_BLOCK_2700_27FF,
    UNICODE_BLOCK_2800_28FF,
    UNICODE_BLOCK_2900_29FF,
    UNICODE_BLOCK_2A00_2AFF,
    UNICODE_BLOCK_2B00_2BFF,
    UNICODE_BLOCK_2C00_2CFF,
    UNICODE_BLOCK_2D00_2DFF,
    UNICODE_BLOCK_2E00_2EFF,
    UNICODE_BLOCK_2F00_2FFF,
    UNICODE_BLOCK_3000_30FF,
    UNICODE_BLOCK_3100_31FF,
    UNICODE_BLOCK_3200_32FF,
    UNICODE_BLOCK_3300_33FF,
    UNICODE_BLOCK_3400_34FF,
    UNICODE_BLOCK_3500_35FF,
    UNICODE_BLOCK_3600_36FF,
    UNICODE_BLOCK_3700_37FF,
    UNICODE_BLOCK_3800_38FF,
    UNICODE_BLOCK_3900_39FF,
    UNICODE_BLOCK_3A00_3AFF,
    UNICODE_BLOCK_3B00_3BFF,
    UNICODE_BLOCK_3C00_3CFF,
    UNICODE_BLOCK_3D00_3DFF,
    UNICODE_BLOCK_3E00_3EFF,
    UNICODE_BLOCK_3F00_3FFF,
    UNICODE_BLOCK_4000_40FF,
    UNICODE_BLOCK_4100_41FF,
    UNICODE_BLOCK_4200_42FF,
    UNICODE_BLOCK_4300_43FF,
    UNICODE_BLOCK_4400_44FF,
    UNICODE_BLOCK_4500_45FF,
    UNICODE_BLOCK_4600_46FF,
    UNICODE_BLOCK_4700_47FF,
    UNICODE_BLOCK_4800_48FF,
    UNICODE_BLOCK_4900_49FF,
    UNICODE_BLOCK_4A00_4AFF,
    UNICODE_BLOCK_4B00_4BFF,
    UNICODE_BLOCK_4C00_4CFF,
    UNICODE_BLOCK_4D00_4DFF,
    UNICODE_BLOCK_4E00_4EFF,
    UNICODE_BLOCK_4F00_4FFF,
    UNICODE_BLOCK_5000_50FF,
    UNICODE_BLOCK_5100_51FF,
    UNICODE_BLOCK_5200_52FF,
    UNICODE_BLOCK_5300_53FF,
    UNICODE_BLOCK_5400_54FF,
    UNICODE_BLOCK_5500_55FF,
    UNICODE_BLOCK_5600_56FF,
    UNICODE_BLOCK_5700_57FF,
    UNICODE_BLOCK_5800_58FF,
    UNICODE_BLOCK_5900_59FF,
    UNICODE_BLOCK_5A00_5AFF,
    UNICODE_BLOCK_5B00_5BFF,
    UNICODE_BLOCK_5C00_5CFF,
    UNICODE_BLOCK_5D00_5DFF,
    UNICODE_BLOCK_5E00_5EFF,
    UNICODE_BLOCK_5F00_5FFF,
    UNICODE_BLOCK_6000_60FF,
    UNICODE_BLOCK_6100_61FF,
    UNICODE_BLOCK_6200_62FF,
    UNICODE_BLOCK_6300_63FF,
    UNICODE_BLOCK_6400_64FF,
    UNICODE_BLOCK_6500_65FF,
    UNICODE_BLOCK_6600_66FF,
    UNICODE_BLOCK_6700_67FF,
    UNICODE_BLOCK_6800_68FF,
    UNICODE_BLOCK_6900_69FF,
    UNICODE_BLOCK_6A00_6AFF,
    UNICODE_BLOCK_6B00_6BFF,
    UNICODE_BLOCK_6C00_6CFF,
    UNICODE_BLOCK_6D00_6DFF,
    UNICODE_BLOCK_6E00_6EFF,
    UNICODE_BLOCK_6F00_6FFF,
    UNICODE_BLOCK_7000_70FF,
    UNICODE_BLOCK_7100_71FF,
    UNICODE_BLOCK_7200_72FF,
    UNICODE_BLOCK_7300_73FF,
    UNICODE_BLOCK_7400_74FF,
    UNICODE_BLOCK_7500_75FF,
    UNICODE_BLOCK_7600_76FF,
    UNICODE_BLOCK_7700_77FF,
    UNICODE_BLOCK_7800_78FF,
    UNICODE_BLOCK_7900_79FF,
    UNICODE_BLOCK_7A00_7AFF,
    UNICODE_BLOCK_7B00_7BFF,
    UNICODE_BLOCK_7C00_7CFF,
    UNICODE_BLOCK_7D00_7DFF,
    UNICODE_BLOCK_7E00_7EFF,
    UNICODE_BLOCK_7F00_7FFF,
    UNICODE_BLOCK_8000_80FF,
    UNICODE_BLOCK_8100_81FF,
    UNICODE_BLOCK_8200_82FF,
    UNICODE_BLOCK_8300_83FF,
    UNICODE_BLOCK_8400_84FF,
    UNICODE_BLOCK_8500_85FF,
    UNICODE_BLOCK_8600_86FF,
    UNICODE_BLOCK_8700_87FF,
    UNICODE_BLOCK_8800_88FF,
    UNICODE_BLOCK_8900_89FF,
    UNICODE_BLOCK_8A00_8AFF,
    UNICODE_BLOCK_8B00_8BFF,
    UNICODE_BLOCK_8C00_8CFF,
    UNICODE_BLOCK_8D00_8DFF,
    UNICODE_BLOCK_8E00_8EFF,
    UNICODE_BLOCK_8F00_8FFF,
    UNICODE_BLOCK_9000_90FF,
    UNICODE_BLOCK_9100_91FF,
    UNICODE_BLOCK_9200_92FF,
    UNICODE_BLOCK_9300_93FF,
    UNICODE_BLOCK_9400_94FF,
    UNICODE_BLOCK_9500_95FF,
    UNICODE_BLOCK_9600_96FF,
    UNICODE_BLOCK_9700_97FF,
    UNICODE_BLOCK_9800_98FF,
    UNICODE_BLOCK_9900_99FF,
    UNICODE_BLOCK_9A00_9AFF,
    UNICODE_BLOCK_9B00_9BFF,
    UNICODE_BLOCK_9C00_9CFF,
    UNICODE_BLOCK_9D00_9DFF,
    UNICODE_BLOCK_9E00_9EFF,
    UNICODE_BLOCK_9F00_9FFF,
    UNICODE_BLOCK_A000_A0FF,
    UNICODE_BLOCK_A100_A1FF,
    UNICODE_BLOCK_A200_A2FF,
    UNICODE_BLOCK_A300_A3FF,
    UNICODE_BLOCK_A400_A4FF,
    UNICODE_BLOCK_A500_A5FF,
    UNICODE_BLOCK_A600_A6FF,
    UNICODE_BLOCK_A700_A7FF,
    UNICODE_BLOCK_A800_A8FF,
    UNICODE_BLOCK_A900_A9FF,
    UNICODE_BLOCK_AA00_AAFF,
    UNICODE_BLOCK_AB00_ABFF,
    UNICODE_BLOCK_AC00_ACFF,
    UNICODE_BLOCK_AD00_ADFF,
    UNICODE_BLOCK_AE00_AEFF,
    UNICODE_BLOCK_AF00_AFFF,
];

const generatedCharmap: Record<string, string> = {};

unicodeBlocks.forEach((block, blockIndex) => {
    if (block) {
        // Assuming each block constant represents 256 code points (0x100)
        const baseCode = blockIndex * 0x100;

        block.forEach((replacement, charIndex) => {
            if (typeof replacement === "string") { // Only map if a replacement string exists
                const charCode = baseCode + charIndex;

                try {
                    const originalChar = String.fromCharCode(charCode);

                    if (originalChar && !generatedCharmap[originalChar]) {
                        generatedCharmap[originalChar] = replacement;
                    }
                } catch (e) {
                    // Ignore errors for invalid char codes
                }
            }
        });
    }
});

export default Object.freeze(generatedCharmap) as Charmap;

// reset memory
unicodeBlocks = undefined;
