import { readdirSync, statSync } from "node:fs";
import { cwd } from "node:process";

import { isAccessibleSync, readFileSync } from "@visulima/fs";
import { join } from "@visulima/path";

import { HOOKS } from "./constants";

interface HookBlock {
    command: string;
    id: string;
    name?: string;
}

interface StageEntry {
    blocks: HookBlock[];
    rawLineCount: number;
    stage: string;
}

interface ListResult {
    hooksDirectory: string;
    stages: StageEntry[];
}

const HOOK_HEADER_RE = /^# ([^:\s]\S*)(?::\s+(.+))?$/;

/**
 * Parse a `.vis-hooks/{stage}` script into `# id: name` headers emitted by the
 * migrator. Scripts authored by hand (no headers) surface as a single
 * "(custom)" block.
 */
const parseStageScript = (content: string): HookBlock[] => {
    const blocks: HookBlock[] = [];
    const lines = content.split("\n");
    let current: HookBlock | undefined;

    for (const line of lines) {
        if (line.startsWith("#!") || line.startsWith("# Generated by") || line.startsWith("# NOTE:") || line === "set -e" || line === "") {
            continue;
        }

        const headerMatch = HOOK_HEADER_RE.exec(line);

        if (headerMatch) {
            if (current) {
                blocks.push(current);
            }

            current = { command: "", id: headerMatch[1] ?? "", ...(headerMatch[2] ? { name: headerMatch[2] } : {}) };
            continue;
        }

        if (current) {
            current.command = current.command.length > 0 ? `${current.command}\n${line}` : line;
        } else {
            current = { command: line, id: "(custom)" };
        }
    }

    if (current) {
        blocks.push(current);
    }

    return blocks;
};

const listHooks = (root: string, hooksDirectory: string): ListResult => {
    const directory = join(root, hooksDirectory);
    const stages: StageEntry[] = [];
    const stageSet = new Set<string>(HOOKS);

    if (isAccessibleSync(directory)) {
        for (const entry of readdirSync(directory)) {
            if (entry.startsWith(".") || entry === "_") {
                continue;
            }

            if (!stageSet.has(entry)) {
                continue;
            }

            const stagePath = join(directory, entry);

            if (!statSync(stagePath).isFile()) {
                continue;
            }

            const content: string = readFileSync(stagePath);
            const blocks = parseStageScript(content);

            stages.push({ blocks, rawLineCount: content.split("\n").length, stage: entry });
        }
    }

    stages.sort((a, b) => a.stage.localeCompare(b.stage));

    return { hooksDirectory, stages };
};

const formatListResult = (result: ListResult): string[] => {
    const lines: string[] = [];

    if (result.stages.length === 0) {
        lines.push(`No hooks installed in ${result.hooksDirectory}/.`);

        return lines;
    }

    lines.push(`Hooks in ${result.hooksDirectory}/:`);

    for (const entry of result.stages) {
        lines.push("", `${entry.stage} (${entry.rawLineCount} lines)`);

        if (entry.blocks.length === 0) {
            lines.push("  (empty)");
        } else {
            for (const block of entry.blocks) {
                const title = block.name ? `${block.id} — ${block.name}` : block.id;

                lines.push(`  - ${title}`);

                const firstCommandLine = block.command.split("\n").find((line) => line.trim() !== "");

                if (firstCommandLine) {
                    const display = firstCommandLine.length > 120 ? `${firstCommandLine.slice(0, 117)}...` : firstCommandLine;

                    lines.push(`      ${display}`);
                }
            }
        }
    }

    return lines;
};

const runList = (hooksDirectory: string, logger: { info: (message: string) => void }): void => {
    const result = listHooks(cwd(), hooksDirectory);

    for (const line of formatListResult(result)) {
        logger.info(line);
    }
};

export type { HookBlock, ListResult, StageEntry };
export { formatListResult, listHooks, parseStageScript, runList };
export { DEFAULT_HOOKS_DIRECTORY as LIST_DEFAULT_DIRECTORY } from "./constants";
