import { spawnSync } from "node:child_process";
import { unlinkSync, writeFileSync } from "node:fs";

import { ensureDirSync, isAccessibleSync, readFileSync } from "@visulima/fs";
import { readTomlSync } from "@visulima/fs/toml";
import { join } from "@visulima/path";
import { parse as parseYaml } from "yaml";

import type { InstallResult } from "./constants";
import { PREK_CONFIG_FILES, PREK_STAGE_ALIASES, PREK_STAGES_WITH_GIT_ARGS, PREK_SUPPORTED_STAGES, PREK_TRANSLATABLE_LANGUAGES } from "./constants";
import { installHooks } from "./install";

interface PrekHookEntry {
    additional_dependencies?: string[];
    alias?: string;
    always_run?: boolean;
    args?: string[];
    description?: string;
    entry?: string;
    exclude?: string;
    exclude_types?: string[];
    files?: string;
    id?: string;
    language?: string;
    language_version?: string;
    name?: string;
    pass_filenames?: boolean;
    stages?: string[];
    types?: string[];
    types_or?: string[];
}

interface PrekRepoEntry {
    hooks?: PrekHookEntry[];
    repo?: string;
    rev?: string;
}

interface PrekConfig {
    default_language_version?: Record<string, string>;
    default_stages?: string[];
    exclude?: string;
    fail_fast?: boolean;
    files?: string;
    repos?: PrekRepoEntry[];
}

interface SkippedHook {
    hookId: string;
    reason: string;
    repo: string;
}

interface ConversionResult {
    droppedFilters: string[];
    manualSteps: string[];
    scripts: Map<string, string>;
    skippedHooks: SkippedHook[];
}

interface MigrateLogger {
    info: (message: string) => void;
    warn: (message: string) => void;
}

const AUTO_GENERATED_HEADER = "# Generated by `vis hook migrate` from prek";

/**
 * Single-quote a string for safe use in a POSIX shell.
 */
const shellQuote = (value: string): string => `'${value.replaceAll("'", String.raw`'\''`)}'`;

/**
 * Locate a prek config file under `root`. Returns the first match.
 */
const detectPrekConfig = (root: string): string | undefined => {
    for (const file of PREK_CONFIG_FILES) {
        if (isAccessibleSync(join(root, file))) {
            return file;
        }
    }

    return undefined;
};

/**
 * Normalize a stage name, translating legacy pre-commit.com aliases.
 */
const mapPrekStage = (stage: string): string => PREK_STAGE_ALIASES[stage] ?? stage;

/**
 * Build the shell command line for a single hook entry.
 * Entry is emitted verbatim (pre-commit tokenizes via shlex, shell will tokenize too for most real-world entries).
 * Args are single-quoted individually. "$@" is forwarded for stages where git passes an argument.
 */
const buildHookCommand = (entry: PrekHookEntry, stage: string): string => {
    const parts: string[] = [];

    if (entry.language === "fail") {
        const message = entry.entry ?? entry.name ?? entry.id ?? "hook failed";

        parts.push(`echo ${shellQuote(message)}; exit 1`);

        return parts.join(" ");
    }

    if (entry.entry) {
        parts.push(entry.entry);
    }

    if (Array.isArray(entry.args)) {
        for (const arg of entry.args) {
            parts.push(shellQuote(arg));
        }
    }

    const passFilenames = entry.pass_filenames ?? true;

    if (passFilenames && PREK_STAGES_WITH_GIT_ARGS.has(stage)) {
        parts.push('"$@"');
    }

    return parts.join(" ");
};

/**
 * True if the hook declares any file filter we cannot preserve.
 */
const hasFileFilter = (entry: PrekHookEntry): boolean =>
    Boolean(entry.files || entry.exclude || (entry.types && entry.types.length > 0) || (entry.types_or && entry.types_or.length > 0) || (entry.exclude_types && entry.exclude_types.length > 0));

/**
 * Determine the target stages for a hook, falling back to config defaults then `[pre-commit]`.
 */
const resolveStages = (entry: PrekHookEntry, defaultStages: string[] | undefined): string[] => {
    const raw = entry.stages && entry.stages.length > 0 ? entry.stages : (defaultStages ?? ["pre-commit"]);

    return raw.map((stage) => mapPrekStage(stage));
};

/**
 * Convert a parsed prek config into a per-stage map of shell script bodies.
 * Hooks we cannot translate (remote repos, language-specific toolchains) are
 * reported back in `skippedHooks` for the caller to surface.
 */
const convertPrekConfig = (config: PrekConfig): ConversionResult => {
    const stageBlocks = new Map<string, string[]>();
    const skippedHooks: SkippedHook[] = [];
    const droppedFilters: string[] = [];
    const manualSteps: string[] = [];

    if (config.files || config.exclude) {
        droppedFilters.push("top-level files/exclude filter dropped (vis hook scripts do not filter files)");
    }

    for (const repo of config.repos ?? []) {
        const repoName = repo.repo ?? "<unknown>";
        const isLocal = repoName === "local";

        for (const hook of repo.hooks ?? []) {
            const hookId = hook.id ?? "<unknown>";

            if (!isLocal) {
                skippedHooks.push({
                    hookId,
                    reason: `remote repo "${repoName}"@${repo.rev ?? "?"} — requires the prek binary to run`,
                    repo: repoName,
                });
                continue;
            }

            const language = hook.language ?? "system";

            if (!PREK_TRANSLATABLE_LANGUAGES.has(language)) {
                skippedHooks.push({
                    hookId,
                    reason: `language "${language}" needs an isolated toolchain — run this hook via prek or reimplement as a system command`,
                    repo: repoName,
                });
                continue;
            }

            if (language !== "fail" && !hook.entry) {
                skippedHooks.push({
                    hookId,
                    reason: "missing `entry`",
                    repo: repoName,
                });
                continue;
            }

            if (Array.isArray(hook.additional_dependencies) && hook.additional_dependencies.length > 0) {
                manualSteps.push(`Install ${hook.additional_dependencies.join(", ")} for hook "${hookId}" (prek managed this via additional_dependencies)`);
            }

            if (hasFileFilter(hook)) {
                droppedFilters.push(`hook "${hookId}" had file filters (types/files/exclude) — they were dropped, the command will run unconditionally`);
            }

            const stages = resolveStages(hook, config.default_stages);

            for (const stage of stages) {
                if (stage === "manual") {
                    continue;
                }

                if (!PREK_SUPPORTED_STAGES.has(stage)) {
                    skippedHooks.push({
                        hookId,
                        reason: `unsupported stage "${stage}"`,
                        repo: repoName,
                    });
                    continue;
                }

                const command = buildHookCommand(hook, stage);
                const header = `# ${hookId}${hook.name ? `: ${hook.name}` : ""}`;
                const block = `${header}\n${command}`;

                const existing = stageBlocks.get(stage);

                if (existing) {
                    existing.push(block);
                } else {
                    stageBlocks.set(stage, [block]);
                }
            }
        }
    }

    const scripts = new Map<string, string>();
    const preamble = [AUTO_GENERATED_HEADER];

    if (droppedFilters.length > 0) {
        preamble.push("# NOTE: prek file filters (types/files/exclude) are not replicated — commands run unconditionally.");
    }

    for (const [stage, blocks] of stageBlocks) {
        const bodyLines = ["#!/usr/bin/env sh", ...preamble];

        if (config.fail_fast) {
            bodyLines.push("set -e");
        }

        bodyLines.push("", blocks.join("\n\n"), "");

        scripts.set(stage, bodyLines.join("\n"));
    }

    return {
        droppedFilters,
        manualSteps,
        scripts,
        skippedHooks,
    };
};

/**
 * Parse a prek YAML config. Returns undefined if the content is empty or malformed.
 */
const parsePrekConfig = (content: string): PrekConfig | undefined => {
    const parsed = parseYaml(content) as unknown;

    if (parsed && typeof parsed === "object") {
        return parsed as PrekConfig;
    }

    return undefined;
};

/**
 * Load a prek config file from disk, dispatching to the YAML or TOML parser
 * based on the extension. TOML parsing is delegated to `@visulima/fs/toml`
 * (which wraps smol-toml), so we hit the same implementation the rest of the
 * codebase uses for TOML.
 */
const loadPrekConfig = (configPath: string): PrekConfig | undefined => {
    if (configPath.endsWith(".toml")) {
        const parsed = readTomlSync(configPath) as unknown;

        if (parsed && typeof parsed === "object") {
            return parsed as PrekConfig;
        }

        return undefined;
    }

    const content: string = readFileSync(configPath);

    return parsePrekConfig(content);
};

/**
 * Try to detach prek from git. Best-effort: if `prek` is on PATH we run
 * `prek uninstall` so it removes its own shims; otherwise we only reset
 * core.hooksPath if it currently points to a prek-managed directory.
 * We never touch the prek binary itself (it's a system install).
 */
const detachPrek = (root: string, logger: MigrateLogger): void => {
    const prekCheck = spawnSync("prek", ["--version"], { cwd: root, encoding: "utf8" });

    if (prekCheck.status === 0) {
        const uninstall = spawnSync("prek", ["uninstall"], { cwd: root, encoding: "utf8" });

        if (uninstall.status === 0) {
            logger.info("Detached prek via `prek uninstall`.");
        } else {
            logger.info("`prek uninstall` did not exit cleanly — continuing. You may need to run it manually.");
        }
    } else {
        logger.info("prek binary not found on PATH — skipping `prek uninstall`. Run it manually if prek is installed elsewhere.");
    }
};

/**
 * Migrates a prek / pre-commit framework configuration to vis hooks.
 */
const migrateFromPrek = (root: string, hooksDirectory: string, logger: MigrateLogger): InstallResult => {
    const configFile = detectPrekConfig(root);

    if (!configFile) {
        return { isError: true, message: "No prek configuration found (.pre-commit-config.yaml, .pre-commit-config.yml, or prek.toml)" };
    }

    logger.info(`Found prek config at ${configFile}`);

    const configPath = join(root, configFile);
    const rawContent: string = readFileSync(configPath);
    const config = loadPrekConfig(configPath);

    if (!config) {
        return { isError: true, message: `Could not parse ${configFile}` };
    }

    const { droppedFilters, manualSteps, scripts, skippedHooks } = convertPrekConfig(config);

    if (scripts.size === 0 && skippedHooks.length === 0) {
        return { isError: true, message: `${configFile} has no hooks to migrate` };
    }

    // If core.hooksPath points to a prek-managed dir, unset it so installHooks can take over.
    const existingPath = spawnSync("git", ["config", "--local", "core.hooksPath"], { cwd: root, encoding: "utf8" });

    if (existingPath.status === 0) {
        const current = existingPath.stdout?.toString().trim();

        if (current && (current.includes(".prek") || current.includes("prek-hooks"))) {
            spawnSync("git", ["config", "--local", "--unset", "core.hooksPath"], { cwd: root });
        }
    }

    const installResult = installHooks(hooksDirectory);

    if (installResult.isError) {
        return installResult;
    }

    if (installResult.message) {
        logger.info(installResult.message);
    }

    const targetDirectory = join(root, hooksDirectory);

    ensureDirSync(targetDirectory);

    let migratedCount = 0;

    for (const [stage, body] of scripts) {
        writeFileSync(join(targetDirectory, stage), body, { mode: 0o755 });
        migratedCount += 1;
        logger.info(`  Wrote ${hooksDirectory}/${stage}`);
    }

    detachPrek(root, logger);

    // Back up and remove the prek config so it doesn't confuse future runs.
    const backupPath = `${configPath}.bak`;

    if (!isAccessibleSync(backupPath)) {
        writeFileSync(backupPath, rawContent, "utf8");
    }

    unlinkSync(configPath);
    logger.info(`Removed ${configFile} (backup at ${configFile}.bak)`);

    // Surface everything we couldn't translate so the user can act on it.
    if (skippedHooks.length > 0) {
        logger.warn(`Skipped ${skippedHooks.length} hook${skippedHooks.length === 1 ? "" : "s"} that cannot run without prek:`);

        for (const skipped of skippedHooks) {
            logger.warn(`  - ${skipped.repo}::${skipped.hookId} — ${skipped.reason}`);
        }
    }

    if (droppedFilters.length > 0) {
        logger.warn("File filters were dropped during migration:");

        for (const note of droppedFilters) {
            logger.warn(`  - ${note}`);
        }
    }

    if (manualSteps.length > 0) {
        logger.warn("Manual follow-up required:");

        for (const step of manualSteps) {
            logger.warn(`  - ${step}`);
        }
    }

    return {
        isError: false,
        message: `Migration complete: ${migratedCount} stage script${migratedCount === 1 ? "" : "s"} written to ${hooksDirectory}/`,
    };
};

export type { ConversionResult, PrekConfig, PrekHookEntry, PrekRepoEntry, SkippedHook };
export { buildHookCommand, convertPrekConfig, detectPrekConfig, loadPrekConfig, mapPrekStage, migrateFromPrek, parsePrekConfig, resolveStages };
