import { spawnSync } from "node:child_process";
import { unlinkSync, writeFileSync } from "node:fs";

import { ensureDirSync, isAccessibleSync, readFileSync } from "@visulima/fs";
import { readTomlSync } from "@visulima/fs/toml";
import { join } from "@visulima/path";
import { parse as parseYaml } from "yaml";

import { resolveIndentForFile } from "../../util/editorconfig";
import { isKnownTag } from "../../util/identify";
import { BUILTIN_HOOK_IDS } from "./builtins";
import type { HookConfig, HookEntry } from "./config";
import { HOOK_CONFIG_FILENAME, HOOK_CONFIG_VERSION, writeHookConfig } from "./config";
import type { InstallResult } from "./constants";
import { PREK_CONFIG_FILES, PREK_STAGE_ALIASES, PREK_STAGES_WITH_GIT_ARGS, PREK_SUPPORTED_STAGES, PREK_TRANSLATABLE_LANGUAGES } from "./constants";
import { installHooks } from "./install";

interface PrekHookEntry {
    additional_dependencies?: string[];
    alias?: string;
    always_run?: boolean;
    args?: string[];
    description?: string;
    entry?: string;
    exclude?: string;
    exclude_types?: string[];
    files?: string;
    id?: string;
    language?: string;
    language_version?: string;
    name?: string;
    pass_filenames?: boolean;
    stages?: string[];
    types?: string[];
    types_or?: string[];
    verbose?: boolean;
}

interface PrekRepoEntry {
    hooks?: PrekHookEntry[];
    repo?: string;
    rev?: string;
}

interface PrekConfig {
    default_language_version?: Record<string, string>;
    default_stages?: string[];
    exclude?: string;
    fail_fast?: boolean;
    files?: string;
    repos?: PrekRepoEntry[];
}

interface SkippedHook {
    hookId: string;
    reason: string;
    repo: string;
}

interface AdditionalDep {
    hookId: string;
    name: string;
    raw: string;
    version: string;
}

interface ConversionResult {
    additionalDeps: AdditionalDep[];
    config: HookConfig;
    droppedFilters: string[];
    manualSteps: string[];
    skippedHooks: SkippedHook[];
}

interface MigrateLogger {
    info: (message: string) => void;
    warn: (message: string) => void;
}

// Curated mapping of remote pre-commit-framework hooks → vis-bundled builtins.
// Key is `<owner>/<repo>#<hook-id>` after normalising the repo URL.
const REMOTE_HOOK_BUILTIN_MAP: ReadonlyMap<string, string> = new Map([
    ["pre-commit/pre-commit-hooks#check-json", "check-json"],
    ["pre-commit/pre-commit-hooks#check-merge-conflict", "check-merge-conflict"],
    ["pre-commit/pre-commit-hooks#end-of-file-fixer", "end-of-file-fixer"],
    ["pre-commit/pre-commit-hooks#mixed-line-ending", "mixed-line-ending"],
    ["pre-commit/pre-commit-hooks#trailing-whitespace", "trailing-whitespace"],
]);

// Pip-style version pin (`package==1.0.0`) — not representable in package.json.
const PIP_PIN_RE = /[<>=!~]=/;

// GitHub repo URL matcher; normalises https/git/ssh forms to `<owner>/<repo>`.
const GITHUB_REPO_RE = /github\.com[/:]([^/\s]+\/[^/\s.]+)/i;

const AUTO_GENERATED_HEADER = "# Generated by `vis hook migrate` from prek";

/**
 * Body for the thin per-stage shell script. The script's only job is
 * to invoke vis with the stage name and forward whatever git passes in
 * `$@`. All filter logic / hook orchestration lives in
 * `&lt;hooksDirectory>/config.json` and the in-process dispatcher.
 *
 * `node_modules/.bin` is already on PATH thanks to the wrapper at
 * `install.ts:hookScript`, so a bare `vis` is sufficient.
 * @param stage Git hook stage name (e.g. `pre-commit`).
 * @returns POSIX-sh script source for the stage entry point.
 */
const stageScriptBody = (stage: string): string => `#!/usr/bin/env sh
${AUTO_GENERATED_HEADER}
exec vis hook run ${stage} "$@"
`;

/**
 * Locate a prek config file under `root`. Returns the first match.
 */
const detectPrekConfig = (root: string): string | undefined => {
    for (const file of PREK_CONFIG_FILES) {
        if (isAccessibleSync(join(root, file))) {
            return file;
        }
    }

    return undefined;
};

/**
 * Normalize a stage name, translating legacy pre-commit.com aliases.
 */
const mapPrekStage = (stage: string): string => PREK_STAGE_ALIASES[stage] ?? stage;

/**
 * Reduce a repo URL (https/git/ssh) to an `owner/repo` slug for builtin lookup.
 */
const normalizeRepoKey = (url: string): string => {
    const match = GITHUB_REPO_RE.exec(url);

    return match?.[1] ?? url;
};

/**
 * Parse a prek additional_dependencies entry into a (name, version) pair. Pip
 * specifiers (e.g. `black==24.1.0`) return undefined so the caller can warn.
 */
const parseAdditionalDep = (spec: string): { name: string; version: string } | undefined => {
    if (PIP_PIN_RE.test(spec)) {
        return undefined;
    }

    // Scoped package: name starts with `@`, version follows the second `@`.
    if (spec.startsWith("@")) {
        const at = spec.indexOf("@", 1);

        if (at === -1) {
            return { name: spec, version: "latest" };
        }

        const version = spec.slice(at + 1).trim();

        return { name: spec.slice(0, at), version: version || "latest" };
    }

    const at = spec.indexOf("@");

    if (at === -1) {
        return { name: spec, version: "latest" };
    }

    const version = spec.slice(at + 1).trim();

    return { name: spec.slice(0, at), version: version || "latest" };
};

/**
 * Names in `types` / `types_or` / `exclude_types` that aren't in the
 * combined tag universe (prek-identify's ~311-tag set plus the
 * vis-specific overlay). Surfaced as a warning so users know their
 * migrated filter won't match the files they expect.
 */
const unknownTypes = (entry: PrekHookEntry): string[] => {
    const unknown: string[] = [];

    for (const list of [entry.types, entry.types_or, entry.exclude_types]) {
        for (const type of list ?? []) {
            if (!isKnownTag(type)) {
                unknown.push(type);
            }
        }
    }

    return unknown;
};

/**
 * Determine the target stages for a hook, falling back to config defaults then `[pre-commit]`.
 */
const resolveStages = (entry: PrekHookEntry, defaultStages: string[] | undefined): string[] => {
    const raw = entry.stages && entry.stages.length > 0 ? entry.stages : (defaultStages ?? ["pre-commit"]);

    return raw.map((stage) => mapPrekStage(stage));
};

/**
 * Convert a parsed prek hook into a vis `HookEntry`. The dispatcher
 * interprets exactly one of `builtin`, `entry`, `fail` per entry; the
 * config schema enforces that invariant at load time as a backstop.
 *
 * For git-arg stages (commit-msg, prepare-commit-msg, post-*) the entry
 * is marked `alwaysRun` so the dispatcher doesn't skip it when there
 * are no filterable files — those stages run against argv from git.
 */
const buildHookEntry = (raw: PrekHookEntry, stage: string, builtin?: string): HookEntry => {
    const hookId = raw.id ?? "<unknown>";
    const usesGitArgs = PREK_STAGES_WITH_GIT_ARGS.has(stage);
    const entry: HookEntry = { id: hookId };

    if (raw.name) {
        entry.name = raw.name;
    }

    if (raw.language === "fail") {
        entry.fail = raw.entry ?? raw.name ?? hookId;

        return entry;
    }

    if (builtin) {
        entry.builtin = builtin;
    } else if (raw.entry) {
        entry.entry = raw.entry;
    }

    if (Array.isArray(raw.args) && raw.args.length > 0) {
        entry.args = [...raw.args];
    }

    // Filters only apply to the discovered file set, which git-arg
    // stages don't have — keep the config noise-free by omitting them.
    if (!usesGitArgs) {
        if (raw.files) {
            entry.files = raw.files;
        }

        if (raw.exclude) {
            entry.exclude = raw.exclude;
        }

        if (raw.types && raw.types.length > 0) {
            entry.types = [...raw.types];
        }

        if (raw.types_or && raw.types_or.length > 0) {
            entry.typesOr = [...raw.types_or];
        }

        if (raw.exclude_types && raw.exclude_types.length > 0) {
            entry.excludeTypes = [...raw.exclude_types];
        }
    }

    if (raw.pass_filenames === false || usesGitArgs) {
        entry.passFilenames = false;
    }

    if (raw.always_run || usesGitArgs) {
        entry.alwaysRun = true;
    }

    if (raw.verbose) {
        entry.verbose = true;
    }

    return entry;
};

/**
 * Collect a parsed `additional_dependencies` entry into the migration report,
 * pushing pip-style pins to manualSteps instead of devDependencies.
 */
const collectAdditionalDeps = (entry: PrekHookEntry, hookId: string, additionalDeps: AdditionalDep[], manualSteps: string[]): void => {
    if (!Array.isArray(entry.additional_dependencies)) {
        return;
    }

    for (const spec of entry.additional_dependencies) {
        const parsed = parseAdditionalDep(spec);

        if (!parsed) {
            manualSteps.push(`"${hookId}": additional_dependency "${spec}" uses a pip-style pin and cannot be added to package.json — install manually.`);
            continue;
        }

        additionalDeps.push({ hookId, name: parsed.name, raw: spec, version: parsed.version });
    }
};

/**
 * Convert a parsed prek config into a vis `HookConfig`. Hooks we
 * cannot translate (remote repos with no bundled equivalent,
 * language-specific toolchains) are reported back in `skippedHooks`
 * for the caller to surface to the user.
 */
const convertPrekConfig = (config: PrekConfig): ConversionResult => {
    const stages: Record<string, HookEntry[]> = {};
    const skippedHooks: SkippedHook[] = [];
    const droppedFilters: string[] = [];
    const manualSteps: string[] = [];
    const additionalDeps: AdditionalDep[] = [];

    if (config.files || config.exclude) {
        droppedFilters.push("top-level files/exclude filter dropped — apply it per hook if needed");
    }

    for (const repo of config.repos ?? []) {
        const repoName = repo.repo ?? "<unknown>";
        const isLocal = repoName === "local";
        const repoKey = isLocal ? undefined : normalizeRepoKey(repoName);

        for (const hook of repo.hooks ?? []) {
            const hookId = hook.id ?? "<unknown>";
            let builtin: string | undefined;

            if (isLocal) {
                const language = hook.language ?? "system";

                if (!PREK_TRANSLATABLE_LANGUAGES.has(language)) {
                    skippedHooks.push({
                        hookId,
                        reason: `language "${language}" needs an isolated toolchain — run via prek or reimplement as a system command`,
                        repo: repoName,
                    });
                    continue;
                }

                if (language !== "fail" && !hook.entry) {
                    skippedHooks.push({ hookId, reason: "missing `entry`", repo: repoName });
                    continue;
                }
            } else {
                if (repoKey) {
                    builtin = REMOTE_HOOK_BUILTIN_MAP.get(`${repoKey}#${hookId}`);
                }

                if (!builtin) {
                    skippedHooks.push({
                        hookId,
                        reason: `remote repo "${repoName}"@${repo.rev ?? "?"} has no bundled equivalent — run via prek or replace with a system command`,
                        repo: repoName,
                    });
                    continue;
                }
            }

            collectAdditionalDeps(hook, hookId, additionalDeps, manualSteps);

            const unknownTypeNames = unknownTypes(hook);

            if (unknownTypeNames.length > 0) {
                droppedFilters.push(`hook "${hookId}": unsupported types ${unknownTypeNames.join(", ")} — those entries are ignored by the dispatcher`);
            }

            const hookStages = resolveStages(hook, config.default_stages);

            for (const stage of hookStages) {
                if (stage === "manual") {
                    continue;
                }

                if (!PREK_SUPPORTED_STAGES.has(stage)) {
                    skippedHooks.push({ hookId, reason: `unsupported stage "${stage}"`, repo: repoName });
                    continue;
                }

                const entry = buildHookEntry(hook, stage, builtin);
                const existing = stages[stage];

                if (existing) {
                    existing.push(entry);
                } else {
                    stages[stage] = [entry];
                }
            }
        }
    }

    const hookConfig: HookConfig = {
        stages,
        version: HOOK_CONFIG_VERSION,
    };

    if (config.fail_fast) {
        hookConfig.failFast = true;
    }

    return {
        additionalDeps,
        config: hookConfig,
        droppedFilters,
        manualSteps,
        skippedHooks,
    };
};

/**
 * Parse a prek YAML config. Returns undefined if the content is empty or malformed.
 */
const parsePrekConfig = (content: string): PrekConfig | undefined => {
    const parsed = parseYaml(content) as unknown;

    if (parsed && typeof parsed === "object") {
        return parsed;
    }

    return undefined;
};

/**
 * Load a prek config file from disk, dispatching to the YAML or TOML parser
 * based on the extension. TOML parsing is delegated to `@visulima/fs/toml`
 * (which wraps smol-toml), so we hit the same implementation the rest of the
 * codebase uses for TOML.
 */
const loadPrekConfig = (configPath: string): PrekConfig | undefined => {
    if (configPath.endsWith(".toml")) {
        const parsed = readTomlSync(configPath) as unknown;

        if (parsed && typeof parsed === "object") {
            return parsed;
        }

        return undefined;
    }

    const content: string = readFileSync(configPath);

    return parsePrekConfig(content);
};

/**
 * Merge collected additional_dependencies into the project's package.json
 * devDependencies. Doesn't run install — just updates the manifest and asks
 * the caller to run their package manager.
 */
const mergeAdditionalDependencies = (root: string, deps: ReadonlyArray<AdditionalDep>, useEditorconfig?: boolean): { added: string[]; skipped: string[] } => {
    const packageJsonPath = join(root, "package.json");
    const added: string[] = [];
    const skipped: string[] = [];

    if (!isAccessibleSync(packageJsonPath) || deps.length === 0) {
        return { added, skipped };
    }

    const content: string = readFileSync(packageJsonPath);
    const pkg = JSON.parse(content) as Record<string, unknown>;
    const devDeps: Record<string, string> = (pkg["devDependencies"] as Record<string, string> | undefined) ?? {};
    const runtimeDeps = (pkg["dependencies"] as Record<string, string> | undefined) ?? {};

    for (const dep of deps) {
        // Don't clobber an existing pin in either dependency bucket.
        if (dep.name in devDeps || dep.name in runtimeDeps) {
            skipped.push(dep.name);
            continue;
        }

        devDeps[dep.name] = dep.version;
        added.push(dep.name);
    }

    if (added.length === 0) {
        return { added, skipped };
    }

    pkg["devDependencies"] = devDeps;

    const indent = resolveIndentForFile(packageJsonPath, content, { defaultIndent: "    ", useEditorconfig });

    writeFileSync(packageJsonPath, `${JSON.stringify(pkg, undefined, indent)}\n`, "utf8");

    return { added, skipped };
};

/**
 * Marker doc next to `config.json` for users who land in `.vis-hooks/`
 * looking for what the file does. Re-runs of `vis hook migrate` are
 * idempotent so it's safe to overwrite.
 */
const writeConfigReadme = (root: string, hooksDirectory: string): void => {
    const directory = join(root, hooksDirectory);

    ensureDirSync(directory);
    writeFileSync(
        join(directory, "README.md"),
        [
            "# Vis hook config",
            "",
            "`config.json` is the single source of truth for what each stage",
            "script runs. Auto-generated by `vis hook migrate`. Edit by hand",
            "or re-run the migrator after updating your prek config.",
            "",
            `Bundled builtins: ${BUILTIN_HOOK_IDS.join(", ")}`,
            "",
        ].join("\n"),
        "utf8",
    );
};

/**
 * Try to detach prek from git. Best-effort: if `prek` is on PATH we run
 * `prek uninstall` so it removes its own shims; otherwise we only reset
 * core.hooksPath if it currently points to a prek-managed directory.
 * We never touch the prek binary itself (it's a system install).
 */
const detachPrek = (root: string, logger: MigrateLogger): void => {
    const prekCheck = spawnSync("prek", ["--version"], { cwd: root, encoding: "utf8" });

    if (prekCheck.status === 0) {
        const uninstall = spawnSync("prek", ["uninstall"], { cwd: root, encoding: "utf8" });

        if (uninstall.status === 0) {
            logger.info("Detached prek via `prek uninstall`.");
        } else {
            logger.info("`prek uninstall` did not exit cleanly — continuing. You may need to run it manually.");
        }
    } else {
        logger.info("prek binary not found on PATH — skipping `prek uninstall`. Run it manually if prek is installed elsewhere.");
    }
};

interface MigrateOptions {
    dryRun?: boolean;
    useEditorconfig?: boolean;
}

/**
 * Migrates a prek / pre-commit framework configuration to vis hooks.
 */
const migrateFromPrek = (root: string, hooksDirectory: string, logger: MigrateLogger, options: MigrateOptions = {}): InstallResult => {
    const configFile = detectPrekConfig(root);
    const dryRun = options.dryRun === true;

    if (!configFile) {
        return { isError: true, message: "No prek configuration found (.pre-commit-config.yaml, .pre-commit-config.yml, or prek.toml)" };
    }

    logger.info(`Found prek config at ${configFile}`);

    const configPath = join(root, configFile);
    const rawContent: string = readFileSync(configPath);
    const config = loadPrekConfig(configPath);

    if (!config) {
        return { isError: true, message: `Could not parse ${configFile}` };
    }

    const { additionalDeps, config: hookConfig, droppedFilters, manualSteps, skippedHooks } = convertPrekConfig(config);
    const stageNames = Object.keys(hookConfig.stages);

    if (stageNames.length === 0 && skippedHooks.length === 0) {
        return { isError: true, message: `${configFile} has no hooks to migrate` };
    }

    if (!dryRun) {
        // If core.hooksPath points to a prek-managed dir, unset it so installHooks can take over.
        const existingPath = spawnSync("git", ["config", "--local", "core.hooksPath"], { cwd: root, encoding: "utf8" });

        if (existingPath.status === 0) {
            const current = existingPath.stdout?.toString().trim();

            if (current && (current.includes(".prek") || current.includes("prek-hooks"))) {
                spawnSync("git", ["config", "--local", "--unset", "core.hooksPath"], { cwd: root });
            }
        }

        const installResult = installHooks(hooksDirectory);

        if (installResult.isError) {
            return installResult;
        }

        if (installResult.message) {
            logger.info(installResult.message);
        }
    }

    const targetDirectory = join(root, hooksDirectory);

    if (!dryRun) {
        ensureDirSync(targetDirectory);
    }

    if (dryRun) {
        logger.info(`  (would write) ${hooksDirectory}/${HOOK_CONFIG_FILENAME}`);
    } else {
        writeHookConfig(root, hooksDirectory, hookConfig);
        writeConfigReadme(root, hooksDirectory);
        logger.info(`  Wrote ${hooksDirectory}/${HOOK_CONFIG_FILENAME}`);
    }

    let migratedCount = 0;

    for (const stage of stageNames) {
        const body = stageScriptBody(stage);

        if (dryRun) {
            logger.info(`  (would write) ${hooksDirectory}/${stage}`);
        } else {
            writeFileSync(join(targetDirectory, stage), body, { mode: 0o755 });
            logger.info(`  Wrote ${hooksDirectory}/${stage}`);
        }

        migratedCount += 1;
    }

    const { added, skipped: skippedDeps } = dryRun
        ? {
            added: additionalDeps.map((d) => d.name),
            skipped: [] as string[],
        }
        : mergeAdditionalDependencies(root, additionalDeps, options.useEditorconfig);

    if (added.length > 0) {
        const verb = dryRun ? "would add" : "Added";

        logger.info(`${verb} ${added.length} package${added.length === 1 ? "" : "s"} to devDependencies: ${added.join(", ")}`);

        if (!dryRun) {
            logger.info("Run your package manager's install (e.g. `pnpm install`) to pick up the new devDependencies.");
        }
    }

    if (skippedDeps.length > 0) {
        logger.info(`Skipped ${skippedDeps.length} already-declared package${skippedDeps.length === 1 ? "" : "s"}: ${skippedDeps.join(", ")}`);
    }

    if (!dryRun) {
        detachPrek(root, logger);
    }

    // Back up and remove the prek config so it doesn't confuse future runs.
    const backupPath = `${configPath}.bak`;

    if (dryRun) {
        logger.info(`  (would remove) ${configFile} and back it up to ${configFile}.bak`);
    } else {
        if (!isAccessibleSync(backupPath)) {
            writeFileSync(backupPath, rawContent, "utf8");
        }

        unlinkSync(configPath);
        logger.info(`Removed ${configFile} (backup at ${configFile}.bak)`);
    }

    // Surface everything we couldn't translate so the user can act on it.
    if (skippedHooks.length > 0) {
        logger.warn(`Skipped ${skippedHooks.length} hook${skippedHooks.length === 1 ? "" : "s"} that cannot run without prek:`);

        for (const skipped of skippedHooks) {
            logger.warn(`  - ${skipped.repo}::${skipped.hookId} — ${skipped.reason}`);
        }
    }

    if (droppedFilters.length > 0) {
        logger.warn("Partial filter translations:");

        for (const note of droppedFilters) {
            logger.warn(`  - ${note}`);
        }
    }

    if (manualSteps.length > 0) {
        logger.warn("Manual follow-up required:");

        for (const step of manualSteps) {
            logger.warn(`  - ${step}`);
        }
    }

    const verbose = dryRun ? "would migrate" : "Migration complete:";

    return {
        isError: false,
        message: `${verbose} ${migratedCount} stage script${migratedCount === 1 ? "" : "s"} ${dryRun ? "into" : "written to"} ${hooksDirectory}/`,
    };
};

export type { AdditionalDep, ConversionResult, MigrateOptions, PrekConfig, PrekHookEntry, PrekRepoEntry, SkippedHook };
export {
    buildHookEntry,
    convertPrekConfig,
    detectPrekConfig,
    loadPrekConfig,
    mapPrekStage,
    mergeAdditionalDependencies,
    migrateFromPrek,
    normalizeRepoKey,
    parseAdditionalDep,
    parsePrekConfig,
    REMOTE_HOOK_BUILTIN_MAP,
    resolveStages,
    stageScriptBody,
};
