/**
 * CI workflow templates for `vis release init --workflows`.
 *
 * Generates the .github/workflows/*.yml (or .gitlab-ci.yml) files
 * appropriate for the active provider. Templates are parameterized
 * so projects pick their PM, channel branches, and OIDC vs token auth.
 *
 * Visulima's own workflows live at `.github/workflows/vis-release*.yml`
 * and were committed alongside the subsystem; these templates are for
 * **external adopters** running `vis release init` in their own repo.
 */

import type { VisReleaseConfig } from "../types";
import type { RemoteProvider } from "./remote/interface";

export interface WorkflowGenerationOptions {
    /** Channel branches to trigger releases on. Default derived from `release.channels`. */
    branches: string[];
    /** Whether to include the PR-comment workflow. Default true. */
    includeCheck: boolean;
    /** Whether to include the snapshot workflow. Default true. */
    includeSnapshot: boolean;
    /** Package manager — drives which `&lt;pm> install` / `&lt;pm> run build` commands appear. */
    packageManager: "npm" | "pnpm" | "yarn" | "bun";
    /** Active forge provider (drives which file format we emit). */
    provider: RemoteProvider;
    /** Default workflow path prefix. Github: `.github/workflows/`. GitLab: repo root. */
    /** Use OIDC trusted publishing? Default true (npm + pnpm + yarn — bun ignores). */
    useOidc: boolean;
}

export interface GeneratedFile {
    /** File content. */
    content: string;
    /** Repo-relative path to write. */
    path: string;
}

const installCmd = (pm: WorkflowGenerationOptions["packageManager"]): string => {
    switch (pm) {
        case "bun": {
            return "bun install --frozen-lockfile";
        }
        case "npm": {
            return "npm ci";
        }
        case "pnpm": {
            return "pnpm install --frozen-lockfile";
        }
        case "yarn": {
            return "yarn install --immutable";
        }
        default: {
            return `${pm as string} install`;
        }
    }
};

const buildCmd = (pm: WorkflowGenerationOptions["packageManager"]): string => `${pm} run build`;

const execCmd = (pm: WorkflowGenerationOptions["packageManager"]): string => {
    if (pm === "npm") {
        return "npx";
    }

    if (pm === "bun") {
        return "bunx";
    }

    return `${pm} exec`;
};

/**
 * Per-PM bootstrap snippet for GitLab CI's `before_script` block. GitHub
 * Actions has dedicated `setup-*` actions for each PM; GitLab doesn't,
 * so we install the PM via npm or corepack.
 */
const gitlabPmSetup = (pm: WorkflowGenerationOptions["packageManager"]): string => {
    switch (pm) {
        case "bun": {
            return "npm install -g bun";
        }
        case "npm": {
            return "";
        }
        case "pnpm": {
            return "npm install -g pnpm";
        }
        case "yarn": {
            return "corepack enable && corepack prepare yarn@stable --activate";
        }
        default: {
            return "";
        }
    }
};

// ── GitHub Actions templates ───────────────────────────────────────

const githubReleaseYml = (options: WorkflowGenerationOptions): string => `# vis release — primary release workflow.
# Generated by \`vis release init --workflows\`. Edit freely.

name: vis release

on:
    push:
        branches:
${options.branches.map((b) => `            - "${b}"`).join("\n")}
    workflow_dispatch:

concurrency:
    group: vis-release-\${{ github.ref }}
    cancel-in-progress: false

permissions:
    contents: write
    pull-requests: write
${options.useOidc ? "    id-token: write\n" : ""}
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  token: \${{ secrets.VIS_GH_TOKEN || github.token }}
                  persist-credentials: false

            - uses: actions/setup-node@v4
              with:
                  node-version: "22"

${options.packageManager === "pnpm" ? "            - uses: pnpm/action-setup@v4\n" : ""}${options.packageManager === "bun" ? "            - uses: oven-sh/setup-bun@v2\n" : ""}            - run: ${installCmd(options.packageManager)}
            - run: ${buildCmd(options.packageManager)}

            - run: ${execCmd(options.packageManager)} vis release ci release
              env:
                  GH_TOKEN: \${{ github.token }}
                  VIS_GH_TOKEN: \${{ secrets.VIS_GH_TOKEN || github.token }}
${options.useOidc ? "                  # OIDC trusted publishing — no publish token needed when configured on npmjs.com\n" : "                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}\n"}                  GIT_AUTHOR_NAME: "vis-release-bot"
                  GIT_AUTHOR_EMAIL: "vis-release-bot@users.noreply.github.com"
                  GIT_COMMITTER_NAME: "vis-release-bot"
                  GIT_COMMITTER_EMAIL: "vis-release-bot@users.noreply.github.com"
`;

const githubCheckYml = (options: WorkflowGenerationOptions): string => `# vis release ci check — sticky PR comment with release plan.
# Generated by \`vis release init --workflows\`. Edit freely.

name: vis release check

on:
    pull_request:
        types: [opened, synchronize, reopened]

permissions:
    contents: read
    pull-requests: write

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  persist-credentials: false
            - uses: actions/setup-node@v4
              with:
                  node-version: "22"
${options.packageManager === "pnpm" ? "            - uses: pnpm/action-setup@v4\n" : ""}${options.packageManager === "bun" ? "            - uses: oven-sh/setup-bun@v2\n" : ""}            - run: ${installCmd(options.packageManager)}
            - run: ${execCmd(options.packageManager)} vis release ci check
              env:
                  GH_TOKEN: \${{ github.token }}
`;

const githubSnapshotYml = (options: WorkflowGenerationOptions): string => `# vis release ci snapshot — preview release publish + sticky PR comment.
# Generated by \`vis release init --workflows\`. Edit freely.

name: vis release snapshot

on:
    pull_request:
        types: [opened, synchronize, reopened]

concurrency:
    group: vis-release-snapshot-\${{ github.event.pull_request.number }}
    cancel-in-progress: true

permissions:
    contents: read
    pull-requests: write
${options.useOidc ? "    id-token: write\n" : ""}
jobs:
    snapshot:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  persist-credentials: false
            - uses: actions/setup-node@v4
              with:
                  node-version: "22"
${options.packageManager === "pnpm" ? "            - uses: pnpm/action-setup@v4\n" : ""}${options.packageManager === "bun" ? "            - uses: oven-sh/setup-bun@v2\n" : ""}            - run: ${installCmd(options.packageManager)}
            - run: ${buildCmd(options.packageManager)}
            - run: ${execCmd(options.packageManager)} vis release ci snapshot
              env:
                  GH_TOKEN: \${{ github.token }}
${options.useOidc ? "" : "                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}\n"}`;

// ── GitLab CI template ─────────────────────────────────────────────

const gitlabCiYml = (options: WorkflowGenerationOptions): string => `# .gitlab-ci.yml — vis release CI pipeline.
# Generated by \`vis release init --workflows\`. Edit freely.
#
# Required CI/CD variables (Project Settings → CI/CD → Variables):
#   - VIS_GH_TOKEN (or GITLAB_TOKEN) — PAT for force-pushing the version-PR branch
#   - NPM_TOKEN — npm publish auth (until npm OIDC supports GitLab)
#
# Self-hosted GitLab: set release.gitlabHost in vis.config.ts (translates to
# GITLAB_HOST for every glab invocation), or export GITLAB_HOST in the job env.

stages:
    - check
    - release

default:
    image: node:22

variables:
    PM: "${options.packageManager}"

before_script:
${gitlabPmSetup(options.packageManager) ? `    - ${gitlabPmSetup(options.packageManager)}\n` : ""}    - ${installCmd(options.packageManager)}

${
    options.includeCheck
        ? `vis-release-check:
    stage: check
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    script:
        - ${execCmd(options.packageManager)} vis release ci check

`
        : ""
}${
    options.includeSnapshot
        ? `vis-release-snapshot:
    stage: check
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    script:
        - ${buildCmd(options.packageManager)}
        - ${execCmd(options.packageManager)} vis release ci snapshot

`
        : ""
}vis-release:
    stage: release
    # Serialize releases per branch so two close-together pushes don't
    # race on the same registry / staged.json / tag namespace. GitLab's
    # equivalent of GitHub Actions' concurrency.group.
    resource_group: vis-release-$CI_COMMIT_BRANCH
    rules:
${options.branches.map((b) => `        - if: $CI_COMMIT_BRANCH == "${b}"`).join("\n")}
    script:
        - ${buildCmd(options.packageManager)}
        - ${execCmd(options.packageManager)} vis release ci release
`;

// ── Public API ─────────────────────────────────────────────────────

/**
 * Render every workflow file the active provider needs.
 * Caller writes them to disk (handler does the prompting + dry-run logic).
 */
export const generateWorkflowFiles = (config: VisReleaseConfig, overrides: Partial<WorkflowGenerationOptions> = {}): GeneratedFile[] => {
    const provider: RemoteProvider = overrides.provider ?? (config.provider === "github" || config.provider === "gitlab" ? config.provider : "github");

    const channels = config.channels ?? {};
    const branches = overrides.branches ?? Object.keys(channels);

    if (branches.length === 0) {
        branches.push("main");
    }

    const opts: WorkflowGenerationOptions = {
        branches,
        includeCheck: overrides.includeCheck ?? true,
        includeSnapshot: overrides.includeSnapshot ?? true,
        packageManager: overrides.packageManager ?? "pnpm",
        provider,
        useOidc: overrides.useOidc ?? true,
    };

    if (provider === "gitlab") {
        return [{ content: gitlabCiYml(opts), path: ".gitlab-ci.yml" }];
    }

    // GitHub
    const files: GeneratedFile[] = [{ content: githubReleaseYml(opts), path: ".github/workflows/vis-release.yml" }];

    if (opts.includeCheck) {
        files.push({ content: githubCheckYml(opts), path: ".github/workflows/vis-release-check.yml" });
    }

    if (opts.includeSnapshot) {
        files.push({ content: githubSnapshotYml(opts), path: ".github/workflows/vis-release-snapshot.yml" });
    }

    return files;
};
