import assert from "node:assert/strict";
import { test } from "node:test";

import { patchVersionCheck } from "../semantic-release-native-addons.mjs";

const SAMPLE_INDEX_JS = `
/* auto-generated by NAPI-RS */
const a = require("@visulima/task-runner-binding-darwin-arm64");
throw new Error(\`Native binding package version mismatch, expected 1.0.0-alpha.13 but got \${bindingPackageVersion}. ...\`);
const b = require("@visulima/task-runner-binding-linux-x64-gnu");
throw new Error(\`Native binding package version mismatch, expected 1.0.0-alpha.13 but got \${bindingPackageVersion}. ...\`);
`;

test("patchVersionCheck replaces every version-check occurrence", () => {
    const { count, patched } = patchVersionCheck(SAMPLE_INDEX_JS, "1.0.0-alpha.14");

    assert.equal(count, 2);
    assert.match(patched, /expected 1\.0\.0-alpha\.14 but got \$\{bindingPackageVersion\}/);
    assert.doesNotMatch(patched, /expected 1\.0\.0-alpha\.13/);
});

test("patchVersionCheck is idempotent across runs at the same version", () => {
    const first = patchVersionCheck(SAMPLE_INDEX_JS, "1.0.0-alpha.14").patched;
    const second = patchVersionCheck(first, "1.0.0-alpha.14").patched;

    assert.equal(first, second);
});

test("patchVersionCheck does not touch unrelated content", () => {
    const { patched } = patchVersionCheck(SAMPLE_INDEX_JS, "2.0.0");

    assert.match(patched, /\/\* auto-generated by NAPI-RS \*\//);
    assert.match(patched, /require\("@visulima\/task-runner-binding-darwin-arm64"\)/);
});

test("patchVersionCheck handles release-channel versions (alpha, beta, rc)", () => {
    for (const version of ["1.0.0", "1.0.0-alpha.99", "2.3.4-beta.1", "1.0.0-rc.5"]) {
        const { patched } = patchVersionCheck(SAMPLE_INDEX_JS, version);

        assert.ok(patched.includes(`expected ${version} but got \${bindingPackageVersion}`), `failed for ${version}`);
    }
});

test("patchVersionCheck throws when no version-check strings are present", () => {
    assert.throws(() => patchVersionCheck("// no napi loader content here", "1.0.0"), /napi-rs codegen format may have changed/);
});

test("patchVersionCheck throws on empty input", () => {
    assert.throws(() => patchVersionCheck("", "1.0.0"), /napi-rs codegen format may have changed/);
});
