import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";

import { loadMoonTemplate } from "../../src/generate/moon-adapter";
import type { Creation, CreationDirectory, CreationFile } from "../../src/generate/types";

const here = dirname(fileURLToPath(import.meta.url));
const FIXTURE = join(here, "../../__fixtures__/generate/moon-component");

const baseBuiltins = {
    dest_dir: "/tmp/dest",
    dest_rel_dir: "dest",
    working_dir: "/tmp",
    workspace_root: "/tmp",
};

const flatten = (tree: CreationDirectory, prefix = ""): Record<string, CreationFile> => {
    const out: Record<string, CreationFile> = {};

    for (const [key, value] of Object.entries(tree)) {
        const path = prefix ? `${prefix}/${key}` : key;

        if (typeof value === "string" || Buffer.isBuffer(value)) {
            out[path] = value;
        } else if (value && typeof value === "object") {
            Object.assign(out, flatten(value, path));
        }
    }

    return out;
};

describe(loadMoonTemplate, () => {
    it("should parse template.yml metadata", () => {
        expect.assertions(3);

        const template = loadMoonTemplate(FIXTURE, "component");

        expect(template.about.name).toBe("Component");
        expect(template.about.description).toBe("Scaffold a React component");
        expect(template.options).toMatchObject({
            name: { required: true, type: "string" },
            style: { type: "enum", values: ["primary", "secondary"] },
            withTest: { default: true, type: "boolean" },
        });
    });

    it("should render a component with filename interpolation", async () => {
        expect.assertions(3);

        const template = loadMoonTemplate(FIXTURE, "component");
        const creation: Creation = await template.produce({
            builtins: baseBuiltins,
            options: { name: "Button", style: "primary", withTest: true },
        });

        const files = flatten(creation.files ?? {});

        expect(files["Button.tsx"]).toBeDefined();
        expect(files["Button.tsx"]).toContain("export const Button: React.FC<ButtonProps>");
        expect(files["Button.tsx"]).toContain('className="primary"');
    });

    it("should include partial output via {% include %}", async () => {
        expect.assertions(1);

        const template = loadMoonTemplate(FIXTURE, "component");
        const creation = await template.produce({
            builtins: baseBuiltins,
            options: { name: "Card", style: "secondary", withTest: false },
        });

        const files = flatten(creation.files ?? {});

        expect(files["Card.tsx"]).toContain("// Generated by vis generate component — name=Card");
    });

    it("should not emit partial files themselves", async () => {
        expect.assertions(2);

        const template = loadMoonTemplate(FIXTURE, "component");
        const creation = await template.produce({
            builtins: baseBuiltins,
            options: { name: "Card", style: "primary", withTest: false },
        });

        const files = flatten(creation.files ?? {});

        expect(files["partials/_header.tera"]).toBeUndefined();
        expect(files["partials/_header"]).toBeUndefined();
    });

    it("should skip files when frontmatter `if` is false", async () => {
        expect.assertions(2);

        const template = loadMoonTemplate(FIXTURE, "component");
        const withTest = await template.produce({
            builtins: baseBuiltins,
            options: { name: "Card", style: "primary", withTest: true },
        });
        const withoutTest = await template.produce({
            builtins: baseBuiltins,
            options: { name: "Card", style: "primary", withTest: false },
        });

        expect(flatten(withTest.files ?? {})["Card.test.tsx"]).toBeDefined();
        expect(flatten(withoutTest.files ?? {})["Card.test.tsx"]).toBeUndefined();
    });

    it("should copy .raw files verbatim and strip the suffix", async () => {
        expect.assertions(2);

        const template = loadMoonTemplate(FIXTURE, "component");
        const creation = await template.produce({
            builtins: baseBuiltins,
            options: { name: "Card", style: "primary", withTest: false },
        });

        const files = flatten(creation.files ?? {});

        expect(files["README.md"]).toBeDefined();
        expect(files["README.md"]).toContain("{{ raw }}");
    });
});
