name: "Code coverage"
description: "Lint and upload code coverage to codecov"

inputs:
    run-lint:
        description: "Run linting"
        required: true
    codecov-token:
        description: "The token to use for uploading to codecov"
        required: true
    use-affected:
        description: "Use affected projects"
        required: false
        default: "false"
    affected-files:
        description: "The affected files"
        required: false
    exclude-affected-projects:
        description: "The projects to exclude"
        required: false

runs:
    using: "composite"
    steps:
        - name: "Validate codecov.yml"
          id: "lint_codecov"
          if: "inputs.run-lint"
          shell: "bash"
          run: "curl --fail-with-body --data-binary @codecov.yml https://codecov.io/validate"

        - name: "Download Codecov CLI Binary"
          shell: "bash"
          run: "curl -Os https://cli.codecov.io/latest/linux/codecov"

        - name: "Verify Codecov integrity get GPG"
          shell: "bash"
          run: "curl https://keybase.io/codecovsecurity/pgp_keys.asc | gpg --no-default-keyring --keyring trustedkeys.gpg --import"

        - name: "Get Codecov SHAsums"
          shell: "bash"
          run: |
              curl -Os https://cli.codecov.io/latest/linux/codecov.SHA256SUM
              curl -Os https://cli.codecov.io/latest/linux/codecov.SHA256SUM.sig

        - name: "Test Codecov signature"
          shell: "bash"
          run: "gpgv codecov.SHA256SUM.sig codecov.SHA256SUM"

        - name: "Test Codecov SHAsums"
          shell: "bash"
          run: "shasum -a 256 -c codecov.SHA256SUM"

        - name: "Fix Codecov permission"
          shell: "bash"
          run: "sudo chmod +x codecov"

        - name: "Upload affected code coverage to codecov"
          if: "inputs.use-affected == 'true'"
          shell: "bash"
          run: |
              IFS=$'\n' read -r -d '' -a affected_projects < <(pnpm nx show projects --affected --files=${{ inputs.affected-files }} --exclude=${{ inputs.exclude-affected-projects }} && printf '\0')

              # Remove the first two elements of the array
              unset 'affected_projects[0]'
              unset 'affected_projects[1]'

              for project in "${affected_projects[@]}"; do
                  ./codecov --codecov-yml-path codecov.yml --verbose upload-process --fail-on-error --dir "packages/${project}" -t "${CODECOV_TOKEN}" -F "${project}" -n "${project}-${{ github.run_id }}"
              done
          env:
              CODECOV_TOKEN: "${{ inputs.codecov-token }}"

        - name: "Upload code coverage to codecov"
          if: "inputs.use-affected == 'false'"
          shell: "bash"
          run: |
              for dir in packages/*; do
                  ./codecov --codecov-yml-path codecov.yml --verbose upload-process --fail-on-error --dir "${dir}" -t "${CODECOV_TOKEN}" -F "$(basename "${dir}")" -n "$(basename "${dir}")"-${{ github.run_id }}
              done
          env:
              CODECOV_TOKEN: "${{ inputs.codecov-token }}"
