name: "Cleanup caches by a branch"

on: # yamllint disable-line rule:truthy
    pull_request:
        types:
            - "closed"
        branches:
            - "main"
            - "next"
            - "alpha"
            - "beta"

permissions:
    contents: "read"

jobs:
    cleanup-branch-cache:
        uses: "anolilab/workflows/.github/workflows/cleanup-branch-cache.yaml@aa162a984a4909f412bc4dbae712def066a0a681" # v20.2.5 # v19.0.4 # main
        with:
            target-repo: "visulima/visulima"
