name: "Cleanup caches by a branch"

on: # yamllint disable-line rule:truthy
    pull_request:
        types:
            - "closed"
        branches:
            - "main"
            - "next"
            - "alpha"
            - "beta"

permissions:
  contents: read

jobs:
    cleanup-branch-cache:
        uses: "anolilab/workflows/.github/workflows/cleanup-branch-cache.yaml@3c54b71af67bdd990513c4a17fa2fde078db7b74" # main
        with:
            target-repo: "visulima/visulima"
