# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Labeler"

on: # yamllint disable-line rule:truthy
    - "pull_request_target"

jobs:
    triage:
        runs-on: "ubuntu-latest"
        permissions:
            contents: "read"
            pull-requests: "write"
        steps:
            - uses: "actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b" # v6.0.1
              with:
                  repo-token: "${{ secrets.GITHUB_TOKEN }}"
                  configuration-path: "labeler-config.yml"
