name: "Next.js Bundle Analysis"

on: # yamllint disable-line rule:truthy
    pull_request: # yamllint disable-line rule:empty-values
    push:
        branches:
            - "main"
    workflow_dispatch: # yamllint disable-line rule:empty-values

defaults:
    run:
        working-directory: "./"

permissions:
    contents: "read" # to fetch code (actions/checkout)
    pull-requests: "write"

concurrency:
    group: "ci-next-bundle-analysis-${{ github.ref }}-1"
    cancel-in-progress: true

jobs:
    analyze:
        runs-on: "ubuntu-latest"

        steps:
            - name: "Git checkout"
              uses: "actions/checkout@v3"
              env:
                  GIT_COMMITTER_NAME: "GitHub Actions Shell"
                  GIT_AUTHOR_NAME: "GitHub Actions Shell"
                  EMAIL: "github-actions[bot]@users.noreply.github.com"

            - uses: "pnpm/action-setup@v2.2.4"
              with:
                  version: 8

            - name: "Set node version to 16"
              uses: "actions/setup-node@v3"
              with:
                  node-version: "16"
                  cache: "pnpm"

            - name: "Install packages"
              run: "pnpm install --frozen-lockfile"
              env:
                  SKIP_CHECK: "true"

            - name: "Restore Next.js Build"
              uses: "actions/cache@v3"
              id: "restore-build-cache"
              env:
                  cache-name: "cache-next-build"
              with:
                  # if you use a custom build directory, replace all instances of `.next` in this file with your build directory
                  # ex: if your app builds to `dist`, replace `.next` with `dist`
                  path: "examples/nextra/.next/cache"
                  # change this if you prefer a more strict cache
                  key: "${{ runner.os }}-build-${{ env.cache-name }}"

            - name: "Build @visulima/nextra-theme-docs"
              run: "pnpm run build:prod:nextra-theme-docs"

            - name: "Build Next.js App"
              # change this if your site requires a custom build command
              run: "cd examples/nextra && ./node_modules/.bin/next build"

            # Here's the first place where next-bundle-analysis' own script is used
            # This step pulls the raw bundle stats for the current bundle
            - name: "Analyze Bundle"
              run: "cd examples/nextra && npx -p nextjs-bundle-analysis@0.5.0 report"

            - name: "Upload Bundle"
              uses: "actions/upload-artifact@v3"
              with:
                  name: "bundle"
                  path: "examples/nextra/.next/analyze/__bundle_analysis.json"

            - name: "Download Base Branch Bundle Stats"
              uses: "dawidd6/action-download-artifact@v2"
              if: "success() && github.event.number"
              with:
                  workflow: "nextjs-bundle-analysis.yml"
                  branch: "${{ github.event.pull_request.base.ref }}"
                  path: "examples/nextra/.next/analyze/base"

            # And here's the second place - this runs after we have both the current and
            # base branch bundle stats, and will compare them to determine what changed.
            # There are two configurable arguments that come from package.json:
            #
            # - budget: optional, set a budget (bytes) against which size changes are measured
            #           it's set to 350kb here by default, as informed by the following piece:
            #           https://infrequently.org/2021/03/the-performance-inequality-gap/
            #
            # - red-status-percentage: sets the percent size increase where you get a red
            #                          status indicator, defaults to 20%
            #
            # Either of these arguments can be changed or removed by editing the `nextBundleAnalysis`
            # entry in your package.json file.
            - name: "Compare With Base Branch Bundle"
              if: "success() && github.event.number"
              run: "ls -laR examples/nextra/.next/analyze/base && cd examples/nextra && npx -p nextjs-bundle-analysis@0.5.0 compare"

            - name: "Get Comment body"
              id: "get-comment-body"
              if: "success() && github.event.number"
              run: |
                  echo 'body<<EOF' >> $GITHUB_OUTPUT
                  echo '' >>  $GITHUB_OUTPUT
                  echo '## Size changes' >>  $GITHUB_OUTPUT
                  echo '' >>  $GITHUB_OUTPUT
                  echo '<details>' >>  $GITHUB_OUTPUT
                  echo '' >>  $GITHUB_OUTPUT
                  cat examples/nextra/.next/analyze/__bundle_analysis_comment.txt >> $GITHUB_OUTPUT
                  echo '' >>  $GITHUB_OUTPUT
                  echo '</details>' >>  $GITHUB_OUTPUT
                  echo '' >>  $GITHUB_OUTPUT
                  echo 'EOF' >> $GITHUB_OUTPUT

            - name: "Comment"
              uses: "marocchino/sticky-pull-request-comment@v2"
              if: "success() && github.event.number"
              with:
                  header: "next-bundle-analysis"
                  message: "${{ steps.get-comment-body.outputs.body }}"
