name: "Require 'Allow Edits'"

on: ["pull_request_target", "merge_group"] # yamllint disable-line rule:truthy

permissions:
    contents: "read"

jobs:
    check_allow_edits:
        permissions:
            pull-requests: "read" # for ljharb/require-allow-edits to check 'allow edits' on PR

        name: "Require “Allow Edits”"

        runs-on: "ubuntu-latest"

        steps:
            - name: "Harden Runner"
              uses: "step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450" # v2.19.1
              with:
                  egress-policy: "audit"

            - uses: "ljharb/require-allow-edits@13f90bc8cc5de000f2b44a0e2c3a11d108e8cd9f" # v2.0.1
