name: "Scorecards supply-chain security"
on:
    branch_protection_rule: ~
    schedule:
        - cron: "37 14 * * 6"
    push:
        branches: ["main"]
permissions: {}
jobs:
    scorecards:
        permissions:
            security-events: "write"
            id-token: "write"
            actions: "read"
            contents: "read"
        uses: "anolilab/workflows/.github/workflows/scorecards.yml@acba5fb15ac98ad23dec1ad233e40e1bb79c1dae" # v19.0.4
        with:
            branch: "main"
            publish_results: true
