name: "Scorecards supply-chain security"
on:
    branch_protection_rule: ~
    schedule:
        - cron: "37 14 * * 6"
    push:
        branches: ["main"]
permissions: {}
jobs:
    scorecards:
        permissions:
            security-events: "write"
            id-token: "write"
            actions: "read"
            contents: "read"
        uses: "anolilab/workflows/.github/workflows/scorecards.yml@aa162a984a4909f412bc4dbae712def066a0a681" # v20.2.5
        with:
            branch: "main"
            publish_results: true
