name: "Scorecards supply-chain security"
on:
    branch_protection_rule: ~
    schedule:
        - cron: "37 14 * * 6"
    push:
        branches: ["main"]
permissions: {}
jobs:
    scorecards:
        permissions:
            security-events: "write"
            id-token: "write"
            actions: "read"
            contents: "read"
        uses: "anolilab/workflows/.github/workflows/scorecards.yml@992a32d56bf8961a317c8d7aa5ec68af4487ae79" # v20.2.0
        with:
            branch: "main"
            publish_results: true
