# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Semantic Pull Request"

on: # yamllint disable-line rule:truthy
    pull_request_target:
        types:
            - "opened"
            - "reopened"
            - "edited"
            - "synchronize"

permissions: {}

jobs:
    main:
        permissions:
            pull-requests: "write" # to analyze PRs (amannn/action-semantic-pull-request)
            statuses: "write" # to mark status of analyzed PR (amannn/action-semantic-pull-request)
        runs-on: "ubuntu-latest"
        name: "Semantic Pull Request"
        steps:
            - name: "Harden Runner"
              uses: "step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423" # v2.6.0
              with:
                  egress-policy: "audit"

            - name: "Validate PR title"
              id: "lint_pr_title"
              uses: "amannn/action-semantic-pull-request@47b15d52c5c30e94a17ec87eb8dd51ff5221fed9" # v5.3.0
              env:
                  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
              with:
                  types: |
                      feat
                      fix
                      chore
                      refactor
                      docs
                      test
                      ci
                      build
                      infra
                      revert

            - uses: "marocchino/sticky-pull-request-comment@efaaab3fd41a9c3de579aba759d2552635e590fd" # v2.8.0
              # When the previous steps fails, the workflow would stop. By adding this
              # condition you can continue the execution with the populated error message.
              if: "always() && (steps.lint_pr_title.outputs.error_message != null)"
              with:
                  header: "pr-title-lint-error"
                  message: |
                      Hey there and thank you for opening this pull request! 👋🏼

                      We require pull request titles to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/) and it looks like your proposed title needs to be adjusted.

                      Details:

                      ```
                      ${{ steps.lint_pr_title.outputs.error_message }}
                      ```

              # Delete a previous comment when the issue has been resolved
            - if: "${{ steps.lint_pr_title.outputs.error_message == null }}"
              uses: "marocchino/sticky-pull-request-comment@efaaab3fd41a9c3de579aba759d2552635e590fd" # v2.8.0
              with:
                  header: "pr-title-lint-error"
                  message: |
                      Thank you for following the naming conventions! 🙏
