name: "Label Idle Issues"

on: # yamllint disable-line rule:truthy
    schedule:
        - cron: "0 0 * * *"

jobs:
    stale-issues:
        uses: "anolilab/workflows/.github/workflows/stale-issues.yml@3c54b71af67bdd990513c4a17fa2fde078db7b74" # main
        with:
            target-repo: "visulima/visulima"
