name: "Zizmor"
on:
    push:
        branches: ["main", "alpha", "next", "beta"]
    pull_request:
        branches: ["main", "alpha", "next", "beta"]
permissions: {}
jobs:
    zizmor:
        permissions:
            security-events: "write"
            contents: "read"
        uses: "anolilab/workflows/.github/workflows/zizmor.yml@aa162a984a4909f412bc4dbae712def066a0a681" # v20.2.5
        with:
            min_severity: "medium"
